### PR TITLE
[DROOLS-6853] jdk17 compatibility

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6853

Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]

**Comment by mareknovotny** [comment]
there are many errors on not found class from jaxb dependency, btw that jira DROOLS-6853 is in Resolved status, so does this change resolves it or jira is in wrong status?

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
Duplicate classes found in `kie-camel`. 
@tkobayas if you have time to give a look tomrrow in your morning I will appreciate it, otherwise don't worry, I'll give a look in morning.

**Comment by tkobayas** [comment]
@mariofusco Sure, I'll send a PR soon.

**Comment by tkobayas** [comment]
@mariofusco hi, I sent https://github.com/mariofusco/droolsjbpm-integration/pull/3
I confirmed that all projects passed BanDuplicateClasses locally (`mvn -Dfull clean install -DskipTests`)

**Comment by mareknovotny** [comment]
@mariofusco you need to play with https://github.com/kiegroup/droolsjbpm-integration/pull/2736/files#diff-5e9522173d59f2683b8e67e25804e3a5bb5adc0579f1c5bd8c115c7135a7c0d8 as you are changing the jaxb dependencies which are conflicting in FDB. The same error is in that PR CI job

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
The 3 test failures seem totally unrelated
```
org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingServiceTest.testPingSuccess
org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest.simpleTests
org.kie.server.router.repository.FileRepositoryTest.testWatchServiceOnLatelyCreatedConfigFile
```
Now I believe that these PRs are ok to be merged.
@mareknovotny @tkobayas what do you think?

**Comment by tkobayas** [comment]
@mariofusco 
Hmm, still hitting BanDuplicateClasses. This time, drools-wb-webapp. I'll also check other downstream projects and let you know.
```
[2022-03-25T15:10:22.822Z] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
[2022-03-25T15:10:22.822Z] Duplicate classes found:
[2022-03-25T15:10:22.822Z]
[2022-03-25T15:10:22.822Z]   Found in:
[2022-03-25T15:10:22.822Z]     com.sun.xml.bind:jaxb-xjc:jar:2.3.0:provided
[2022-03-25T15:10:22.822Z]     org.glassfish.jaxb:jaxb-xjc:jar:2.3.6:compile
[2022-03-25T15:10:22.822Z]   Duplicate classes:
[2022-03-25T15:10:22.822Z]     com/sun/tools/xjc/XJCTask.class
[2022-03-25T15:10:22.822Z]     com/sun/tools/xjc/generator/bean/field/ArrayField.class
[2022-03-25T15:10:22.822Z]     com/sun/tools/xjc/model/CWildcardTypeInfo.class
[2022-03-25T15:10:22.822Z]     com/sun/tools/xjc/reader/relaxng/TypePatternBinder.class
[2022-03-25T15:10:22.822Z]     com/sun/tools/xjc/reader/xmlschema/bindinfo/BIConversion$User.class
...
[2022-03-25T15:10:22.835Z] [INFO] Drools Workbench - WebApp .......................... FAILURE [ 15.091 s]
[2022-03-25T15:10:22.835Z] [INFO] ------------------------------------------------------------------------
[2022-03-25T15:10:22.835Z] [INFO] BUILD FAILURE
[2022-03-25T15:10:22.835Z] [INFO] ------------------------------------------------------------------------
[2022-03-25T15:10:22.835Z] [INFO] Total time:  17:53 min
[2022-03-25T15:10:22.835Z] [INFO] Finished at: 2022-03-25T11:10:19-04:00
[2022-03-25T15:10:22.835Z] [INFO] ------------------------------------------------------------------------
...
[2022-03-25T15:10:22.835Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (ban-duplicated-classes) on project drools-wb-webapp: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2022-03-25T15:10:22.835Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (ban-duplicated-classes) on project drools-wb-webapp: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

**Comment by tkobayas** [comment]
Hi @mariofusco  I tested downstream projects using `droolsjbpm-build-bootstrap/script/mvn-all.sh clean validate -DskipTests`. Finally, with the following 4 repo fixes, the validation (including BanDuplicateClasses) is successful. (skipping compile and test)

```
[tkobayas drools-wb]$ git diff
diff --git a/drools-wb-webapp/pom.xml b/drools-wb-webapp/pom.xml
index 0ca00de61..08f44fe22 100644
--- a/drools-wb-webapp/pom.xml
+++ b/drools-wb-webapp/pom.xml
@@ -1195,12 +1195,8 @@
 
     <!-- Required for PMML integration. These are provided/optional scope in kie-dmn-core -->
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-impl</artifactId>
-    </dependency>
-    <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-core</artifactId>
+      <groupId>org.glassfish.jaxb</groupId>
+      <artifactId>jaxb-runtime</artifactId>
     </dependency>
 
     <!-- PMML Text Editor -->
@@ -1456,7 +1452,7 @@
     </dependency>
 
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
+      <groupId>org.glassfish.jaxb</groupId>
       <artifactId>jaxb-xjc</artifactId>
       <scope>provided</scope>
     </dependency>
```

```
[tkobayas jbpm-designer]$ git diff
diff --git a/jbpm-designer-backend/pom.xml b/jbpm-designer-backend/pom.xml
index 539e775de..8e586dbb5 100644
--- a/jbpm-designer-backend/pom.xml
+++ b/jbpm-designer-backend/pom.xml
@@ -332,8 +332,8 @@
       <artifactId>xercesImpl</artifactId>
     </dependency>
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-impl</artifactId>
+      <groupId>org.glassfish.jaxb</groupId>
+      <artifactId>jaxb-runtime</artifactId>
     </dependency>
     <dependency>
       <groupId>jakarta.xml.bind</groupId>
```

```
[tkobayas jbpm-wb]$ git diff
diff --git a/jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml b/jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
index 788f95e89..d3dda5983 100644
--- a/jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
+++ b/jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
@@ -453,17 +453,12 @@
 
     <!-- JAXB -->
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-impl</artifactId>
+      <groupId>org.glassfish.jaxb</groupId>
+      <artifactId>jaxb-runtime</artifactId>
       <scope>provided</scope>
     </dependency>
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-core</artifactId>
-      <scope>provided</scope>
-    </dependency>
-    <dependency>
-      <groupId>com.sun.xml.bind</groupId>
+      <groupId>org.glassfish.jaxb</groupId>
       <artifactId>jaxb-xjc</artifactId>
       <scope>provided</scope>
     </dependency>
diff --git a/jbpm-wb-showcase/pom.xml b/jbpm-wb-showcase/pom.xml
index b65a85d17..5edcf0340 100644
--- a/jbpm-wb-showcase/pom.xml
+++ b/jbpm-wb-showcase/pom.xml
@@ -724,13 +724,13 @@
     </dependency>
 
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-impl</artifactId>
+      <groupId>org.glassfish.jaxb</groupId>
+      <artifactId>jaxb-runtime</artifactId>
       <scope>runtime</scope>
     </dependency>
 
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
+      <groupId>org.glassfish.jaxb</groupId>
       <artifactId>jaxb-xjc</artifactId>
       <scope>runtime</scope>
     </dependency>
```

```
[tkobayas kie-wb-distributions]$ git diff
diff --git a/business-central-parent/business-central-distribution-wars/pom.xml b/business-central-parent/business-central-distribution-wars/pom.xml
index 75d4a766e..68c72d15c 100644
--- a/business-central-parent/business-central-distribution-wars/pom.xml
+++ b/business-central-parent/business-central-distribution-wars/pom.xml
@@ -215,11 +215,11 @@
       <artifactId>dom4j</artifactId>
     </dependency>
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
-      <artifactId>jaxb-impl</artifactId>
+      <groupId>org.glassfish.jaxb</groupId>
+      <artifactId>jaxb-runtime</artifactId>
     </dependency>
     <dependency>
-      <groupId>com.sun.xml.bind</groupId>
+      <groupId>org.glassfish.jaxb</groupId>
       <artifactId>jaxb-xjc</artifactId>
     </dependency>
     <dependency>
```

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by tkobayas — APPROVED** [review]
Great!

**Comment by tkobayas** [comment]
In FDB, only found this one. ProjectLibraryIntegrationTest is flaky and not likely related to this PR.
```
[2022-04-04T16:26:02.181Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 220.186 s <<< FAILURE! - in org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
[2022-04-04T16:26:02.182Z] [ERROR] importAndBuildProjectFromStockRepository(org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest)  Time elapsed: 61.56 s  <<< ERROR!
[2022-04-04T16:26:02.182Z] org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: add-project-dropdown (tried for 15 second(s) with 500 milliseconds interval)
```

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
