### PR TITLE
RHPAM-3762 jackson upgraded to 2.12.4

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

https://issues.redhat.com/browse/RHPAM-3762
https://issues.redhat.com/browse/RHDM-1762

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by tiagobento** [comment]
@Ginxo This is already being done as part of #1693. I think we can close this PR.

**Comment by Ginxo** [comment]
@tiagobento @mareknovotny what if we treat this change in a different PR like this and we will rebase https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/543 (I will always support atomic and specific changes).
From FDB we can say `jackson-dataformat-cbor:2.10.4` has been replaced by `jackson-dataformat-cbor:2.12.4`

**Comment by mareknovotny** [comment]
> @tiagobento @mareknovotny what if we treat this change in a different PR like this and we will rebase https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/543 (I will always support atomic and specific changes).
> From FDB we can say `jackson-dataformat-cbor:2.10.4` has been replaced by `jackson-dataformat-cbor:2.12.4`

it good for some changes, but if the upgrade is combined with required code changes like for jackson it doesn't make sense IMHO as you would need to change or exclude other transitive dependencies with short temporary duration as that WF23 upgrade takes more dependencies.

**Comment by Ginxo** [comment]
closed by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1693

**Pull request closed without merging**
