### PR TITLE
Camel to 2.21.3 to fix CxfSoapTest

### PR DESCRIPTION
**Pull request by lucamolteni**

### CODE REVIEW

**Comment by jhrcek** [comment]
@mswiderski @lucamolteni only known failures in kie-server integration tests, but the failing Cxf test is fixed. As far as I'm concerned, this can go in.

**Comment by jhrcek** [comment]
@mswiderski could you please check and merge if ok?

**Comment by jhrcek** [comment]
We definitely need to do something about the CxfSoapTest that is now [failing daily](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/dailyBuild/job/kieAllBuild-master/lastCompletedBuild/testReport/). Upgrading to latest minor bugfix version of camel seems like the most reasonable option to me.

**Comment by mareknovotny** [comment]
So looking at FDB results, all failed tests are known random issues.
I am ok for merging ASAP this upgrade.

**Comment by jiripetrlik** [comment]
+1 for merge

**Pull request merged**
