### PR TITLE
JBPM-8029: Align javaassist for support GwtMockito in Java11

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @mareknovotny, @ge0ffrey, @etirelli,

I upgraded JavaAssist dependency to fix GwtMockito issues on Java 11 (see exception below). I tested it on Stunner repository and this error is fixed, let's try FullDonwnstream build to check is it causes any issues.

Thank you!

Version of JavaAssist is set in jboss-integration bom repository, but we can't execute fulldownstream build from it so, not sure should I upgrade it there, or we can override this dependency in this repo.

<details>
  <summary>ClassNotFoundException in GwtMockito</summary>
  <pre>Error Message
caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
Stacktrace
java.lang.ClassNotFoundException: caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
	at javassist.Loader.findClass(Loader.java:357)
	at com.google.gwtmockito.GwtMockitoTestRunner$GwtMockitoClassLoader.findClass(GwtMockitoTestRunner.java:421)
	at javassist.Loader.loadClass(Loader.java:309)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.google.gwtmockito.GwtMockitoTestRunner.<init>(GwtMockitoTestRunner.java:148)
	at com.ait.lienzo.test.LienzoMockitoTestRunner.<init>(LienzoMockitoTestRunner.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: javassist.NotFoundException: com.google.gwtmockito.GwtMockito
	at javassist.ClassPool.get(ClassPool.java:452)
	at com.ait.lienzo.test.translator.LienzoMockitoClassTranslator.ensureDefrost(LienzoMockitoClassTranslator.java:109)
	at com.ait.lienzo.test.translator.LienzoMockitoClassTranslator.onLoad(LienzoMockitoClassTranslator.java:82)
	at javassist.Loader.findClass(Loader.java:338)
	... 23 more</pre>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@hasys even though `version.org.javassist` is declared in [jboss-integration-platform-bom](https://github.com/jboss-integration/jboss-integration-platform-bom/blob/2a940426e67ef4ab905dc8339374211f549c2d69/pom.xml#L264) (which is not part of the full downstream build) you *could* test the effect of the version bump on most kiegroup repositories by adding `<version.org.javassist>3.22.0-GA</version.org.javassist>` to [kie-parent](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml).

**Comment by hasys** [comment]
@jhrcek thank you for the info, any way fulldownstream already running and we will get results soon.

**Comment by jhrcek** [comment]
@hasys sorry, I though you made the commit in kie-wb-common, so you actually did what I suggested :-)

**Comment by hasys** [comment]
Fulldownstream build failed with known issues only, and currently work in progress (confirmed by @rsynek and @jiripetrlik). 

Since no new issues caused by this change, I think this PR is ready to go.

Thank you! 

<details>
  <summary>List of know issues</summary>
  <pre>org.kie.karaf.itest.DecisionTablesIntegrationTest.org.kie.karaf.itest.DecisionTablesIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.DecisionTablesIntegrationTest
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[1]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[2]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[3]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[4]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[5]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[6]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[9]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[10]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[11]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[13]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[14]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[15]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[18]
org.kie.karaf.itest.KieDMNKarafIntegrationTest.org.kie.karaf.itest.KieDMNKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.KieDMNKarafIntegrationTest
org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
org.kie.karaf.itest.RuntimeManagerFeatureKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest
org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest.org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest
org.kie.karaf.itest.blueprint.KieBlueprintDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest
org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest.org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest
org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest.testKieBaseUpdatedByScanNow
org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest.testKieBaseUpdatedByTimer
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest
org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest.org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJaxbIntegrationTest
org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest.org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationJsonIntegrationTest
org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationXstreamIntegrationTest.org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationXstreamIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.kieserver.KieServerClientKarafIntegrationXstreamIntegrationTest
org.kie.karaf.itest.planner.PlannerCloudBalanceIntegrationTest.org.kie.karaf.itest.planner.PlannerCloudBalanceIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.planner.PlannerCloudBalanceIntegrationTest
org.kie.karaf.itest.pmml.KiePmmlIntegrationTest.org.kie.karaf.itest.pmml.KiePmmlIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.pmml.KiePmmlIntegrationTest
org.jbpm.process.workitem.camel.karaf.itests.CamelWorkitemIntegrationTest.org.jbpm.process.workitem.camel.karaf.itests.CamelWorkitemIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.jbpm.process.workitem.camel.karaf.itests.CamelWorkitemIntegrationTest
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.createFromSolverFactory
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.template
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.templateWithClassLoader
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.benchmarkConfigWithClassLoader
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.uninitializedBenchmarkResult
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.subSingleBenchmarkConfig
org.optaplanner.benchmark.api.PlannerBenchmarkFactoryTest.benchmarkConfig
org.optaplanner.examples.nqueens.app.BrokenNQueensBenchmarkTest.benchmarkBroken8queens
org.optaplanner.examples.nqueens.app.NQueensBenchmarkTest.benchmark64queens
org.optaplanner.examples.nqueens.app.NQueensBenchmarkTest.benchmark64queensSingleThread
org.optaplanner.examples.tennis.app.TennisBenchmarkTest.benchmark</pre>
</details>

**Comment by mareknovotny** [comment]
@mbiarnes look here what javassist version is here with your alignment

**Comment by romartin** [comment]
lemme know @hasys when this is safe and ready to be merged

**Comment by jhrcek** [comment]
@hasys @mareknovotny now that we know that this version bump doesn't break the FDB, wouldn't it make more sense to close this PR and update the property where it is originally declared [jboss-integration-platform-bom](https://github.com/jboss-integration/jboss-integration-platform-bom/blob/2a940426e67ef4ab905dc8339374211f549c2d69/pom.xml#L264)

Or if you want this change asap merge it, but don't forget to do the same later in that repo and then remove this override here.

**Comment by hasys** [comment]
@jhrcek, done. Thank you.

But I am not sure who should be reviewer there. https://github.com/jboss-integration/jboss-integration-platform-bom/pull/449

**Pull request merged**
