### PR TITLE
[BXMSPROD-1077] Upgrade hibernate to 5.3.18.Final

### PR DESCRIPTION
**Pull request by AntStephenson**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1077

### CODE REVIEW

**Comment by AntStephenson** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
We were hit by new docker hub policy in optaweb-employee-rostering demo
`[2020-11-09T20:52:11.881Z] /usr/bin/docker-current: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.`

**Comment by mareknovotny** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]
lgtm, both failed tests are flaky tests not related with the upgrade of h-core

**Pull request merged**
