### PR TITLE
RHDM-1788: changes related to upgrade of sshd-core 2.9.2

### PR DESCRIPTION
**Pull request by mareknovotny**
Upgrading sshd-core to 2.9.2

https://issues.redhat.com/browse/RHDM-1788 and https://issues.redhat.com/browse/RHPAM-3807

** Dependent PRs **: 
* https://github.com/kiegroup/appformer/pull/1374
* https://github.com/kiegroup/kie-wb-common/pull/3801
* https://github.com/kiegroup/jbpm-wb/pull/1587

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by RishiRajAnand — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
:o now 104 failures completely out of the loop previous failures :)

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
there are different test failures, but not related to this change

- org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35406/kie-server-services/services/rest/server'}]
-  org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest
-  org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest
-  org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest.org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest
-  org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest
-  org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

**Review by domhanak — APPROVED** [review]
Well LGTM if we have green builds. Once merged I can double check nightlys and if we have issues we can react.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
```
[2023-04-11T02:49:20.754Z] [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.0.Final:deploy-only (deploy-workbench) on project jbpm-wb-showcase: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jbpm-wb-showcase.war\".WeldStartService" => "Failed to start service
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.guvnor.structure.backend.config.ConfigurationServiceImpl.setup() on org.guvnor.structure.backend.config.ConfigurationServiceImpl@6fccdfb9
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z] [ERROR]     Caused by: java.lang.NullPointerException"}}}}
[2023-04-11T02:49:20.754Z] [ERROR] -> [Help 1]
[2023-04-11T02:49:20.754Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.0.Final:deploy-only (deploy-workbench) on project jbpm-wb-showcase: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jbpm-wb-showcase.war\".WeldStartService" => "Failed to start service
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.guvnor.structure.backend.config.ConfigurationServiceImpl.setup() on org.guvnor.structure.backend.config.ConfigurationServiceImpl@6fccdfb9
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.NullPointerException"}}}}
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2023-04-11T02:49:20.754Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2023-04-11T02:49:20.754Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jbpm-wb-showcase.war\".WeldStartService" => "Failed to start service
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.jbpm.workbench.server.impl.AppSetup.onStartup() on org.jbpm.workbench.server.impl.AppSetup@44e236f3
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z]     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.guvnor.structure.backend.config.ConfigurationServiceImpl.setup() on org.guvnor.structure.backend.config.ConfigurationServiceImpl@6fccdfb9
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.reflect.InvocationTargetException
[2023-04-11T02:49:20.754Z]     Caused by: java.lang.NullPointerException"}}}}
[2023-04-11T02:49:20.754Z]     at org.wildfly.plugin.deployment.AbstractDeployment.execute (AbstractDeployment.java:152)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2023-04-11T02:49:20.754Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2023-04-11T02:49:20.754Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2023-04-11T02:49:20.754Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2023-04-11T02:49:20.754Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2023-04-11T02:49:20.754Z] [ERROR] 
[2023-04-11T02:49:20.754Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2023-04-11T02:49:20.754Z] [ERROR] 
[2023-04-11T02:49:20.754Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2023-04-11T02:49:20.754Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[2023-04-11T02:49:20.754Z] [ERROR] 
[2023-04-11T02:49:20.754Z] [ERROR] After correcting the problems, you can resume the build with the command
[2023-04-11T02:49:20.754Z] [ERROR]   mvn <args> -rf :jbpm-wb-showcase
```

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
ok we have now green FDB, so as @domhanak stated we can merge and do checks on nightly for backports

**Pull request merged**
