### PR TITLE
DROOLS-6100: Add clustering model to pom

### PR DESCRIPTION
**Pull request by kostola**
**JIRA**: [DROOLS-6100](https://issues.redhat.com/browse/DROOLS-6100)
**Referenced Pull Request**: to be merged together with [drools PR](https://github.com/kiegroup/drools/pull/3527) and [droolsjbpm-integration PR](https://github.com/kiegroup/droolsjbpm-integration/pull/2468)

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Review by gitgabrio — APPROVED** [review]
LGTM, thanks!

**Review by jiripetrlik — APPROVED** [review]

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
Jenkins run fdb

**Pull request merged**
