### PR TITLE
BXMSPROD-685: upgrade javassist and GWTMockito to play nice with it

### PR DESCRIPTION
**Pull request by mareknovotny**
merge together with https://github.com/kiegroup/kie-wb-common/pull/3328

### CODE REVIEW

**Comment by mareknovotny** [comment]
this is improved version of reverted one #1217

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
the errors seem related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8138667 and all versions from 3.23.0-GA+ shows the same 

**org.drools.workbench.screens.guided.dtable.client.editor.GuidedDecisionTableGraphEditorPresenterTest**
`java.lang.IllegalAccessError: tried to access class org.kie.workbench.common.widgets.metadata.client.KieMultipleDocumentEditor$MayCloseHandler from class org.drools.workbench.screens.guided.dtable.client.editor.GuidedDecisionTableGraphEditorPresenter`

@manstis  Any Idea if we can change internal interface access ? for org.kie.workbench.common.widgets.metadata.client.KieMultipleDocumentEditor$MayCloseHandler

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@manstis @hasys @romartin could you guys check how the javassist upgrade could be satisfied the IllegalAccessError if at all?

**Comment by hasys** [comment]
Hi @mareknovotny,

this is how kie-wb-common can be fixed without big changes:
image

I guess changes are easy and reasonable. I tested it locally and it works, but I can't create PR since jenkins need this PR, so it's better for you to create it ping me if you need any help. I am going to check workbench screens now.

Thank you!

**Comment by hasys** [comment]
Hi @mareknovotny, this will fix all other tests as well (outside of kie-wb-common as well).

image

So all tests will pass when you create a PR to kie-wb-common with my changes, except `org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest` but this one is not related to GWTMockito, and I don't know maybe it is rundom test and we can skip it.

Thank you!

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
