### PR TITLE
DROOLS-2690 : Create a Scenario asset

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2690

Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/774
https://github.com/kiegroup/kie-wb-common/pull/1972
https://github.com/kiegroup/drools-wb/pull/886

### CODE REVIEW

**Comment by Rikkola** [comment]
Hold it. Need to change the names a bit.

**Comment by kkufova** [comment]
@Rikkola, alright, let me know when I can review again.

**Comment by gitgabrio** [comment]
+1

**Comment by Rikkola** [comment]
Ok. This can be merged.

**Pull request merged**
