### PR TITLE
Use WildFly 10.1.0.Final for GWT SDM

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by manstis** [comment]
If/when this is merged can you please email BSIG as all developers IDE configuration will need changing too.

**Comment by psiroky** [comment]
@manstis not sure if it makes sense to upgrade. I did it just because I was upgrading some other versions. If it means everyone has to mess with their configs, then it is perhaps better to just use the current version.

**Comment by psiroky** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
@manstis @psiroky Can we merge this PR anyway?

**Comment by psiroky** [comment]
@ge0ffrey I don't have anything against merging, just wasn't sure if it worth the trouble.

**Comment by manstis** [comment]
Let's get some clear communication to BSIG first; as once merged everyone will need to update their IDE launch configurations to use WF 10.1.0.Final. When the proposed upgrade has been communicated and we've allowed a day or so for it to sink into peoples psyche we can merge.

**Comment by psiroky** [comment]
E-mail sent to BSIG. Let's wait few more days and then merge.

**Comment by ge0ffrey** [comment]
I think it can be merged now?

**Comment by manstis** [comment]
I think so..

**Pull request merged**
