### PR TITLE
RHPAM-3510: micro upgrades

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]
lgtm. waiting on FDB results :)

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
@mareknovotny Build was UNSTABLE.  [12 test-failures](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/96/testReport/)

**Comment by mbiarnes** [comment]
Linux execute fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
FDB didn't finished due PIM and jdk8 problems with io.quarkus deps and jdk11 compilation. Otherwise the remaining repositories are just opta-webs so we can take a risk of merging IMHO

**Pull request merged**
