### PR TITLE
[7.44.x] BXMSPROD-1077 Upgrade hibernate core to 5.3.18.Final

### PR DESCRIPTION
**Pull request by mareknovotny**
JIRA: https://issues.redhat.com/browse/BXMSPROD-1077

backporting https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/d410ffc3e581ccc70067cf4f63e1c462cd660d47

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by gmunozfe — APPROVED** [review]
Looks good to me

**Review by afalhambra — APPROVED** [review]
LGTM

**Review by AntStephenson — APPROVED** [review]

**Comment by mareknovotny** [comment]
tests are failed due docker hub limited pulls and due timeouts.

**Pull request merged**
