### PR TITLE
security vulnerability:update of org.apache.lucene

### PR DESCRIPTION
**Pull request by mbiarnes**
GitHub: potential security vulnerabilities in dependencies
ATTENTION: this is a major upgrade
found org.apache.lucene in following reps:
kie-wb-common
kie-wb-distributions
appformer
optaweb-employee-rostering
kie-soup
jbpm-designer
optaplanner-wb
jbpm-wb
drools-wb

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
build fails
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:compile (default-compile) on project kie-wb-common-refactoring-backend: Compilation failure
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-build-bootstrap-downstream-pullrequests/downstream-repos/kie-wb-common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[25,39] cannot find symbol
[ERROR]   symbol:   class CharArraySet
[ERROR]   location: package org.apache.lucene.analysis.util
[ERROR] -> [Help 1]

**Comment by mareknovotny** [comment]
@mbiarnes that was probably some clash in the other PR merged changes
I can see now only  failing `org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable`

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
```
         [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:compile (default-compile) on project kie-wb-common-refactoring-backend: Compilation failure
17:04:25 [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-build-bootstrap-downstream-pullrequests/downstream-repos/kie-wb-common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[25,39] cannot find symbol
17:04:25 [ERROR]   symbol:   class CharArraySet
17:04:25 [ERROR]   location: package org.apache.lucene.analysis.util
17:04:25 [ERROR] -> [Help 1]
17:04:25 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:compile (default-compile) on project kie-wb-common-refactoring-backend: Compilation failure
17:04:25 /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-build-bootstrap-downstream-pullrequests/downstream-repos/kie-wb-common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[25,39] cannot find symbol
17:04:25   symbol:   class CharArraySet
17:04:25   location: package org.apache.lucene.analysis.util
```

This probably needs some fixing in downstream repos too

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build.

**Comment by mareknovotny** [comment]
@mbiarnes I think this upgrade is not possible due major version change

**Comment by mbiarnes** [comment]
@mareknovotny so lets close this PR then

**Pull request closed without merging**
