### PR TITLE
JBPM-8529: Designer - Migration path from the legacy process designer

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys , would you mind review this PR?

Depends on:
https://github.com/kiegroup/appformer/pull/708

**Comment by wmedvede** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/962

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
Just one question: how does this PR depends on Appformers one? It looks independent from it.

**Comment by wmedvede** [comment]
> Just one question: how does this PR depends on Appformers one? It looks independent from it.

No, this PR simply declare the following modules version.

        kie-wb-common-stunner-jbpm-designer-integration-shared
	kie-wb-common-stunner-jbpm-designer-integration-api
	kie-wb-common-stunner-jbpm-designer-integration-backend
	kie-wb-common-stunner-jbpm-designer-integration-client

**Comment by wmedvede** [comment]
> Just one question: how does this PR depends on Appformers one? It looks independent from it.

ah, sorry, well, yes we have two things here
1) at code/compile level it doesn't depend, i.e., the appformer PR can be merged separatally etc.

2)then at runtime, this PR is benefited from the small fixes in appformer. Basically because the InlineNotification status in appformer wan't being updated well, and also the Button implementation in appformer wasn't disabling the Button well.

The appformer PR was already merged

**Comment by wmedvede** [comment]
bad luck, full build failed because of this unrelated tests, and artifacts wasn't generated

org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway

Failing for the past 1 build (Since Failed#119 )
Took 10 sec.
Error Message
test timed out after 10000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Pull request merged**
