### PR TITLE
[7.3.x] Raise Narayana version to 5.6.4

### PR DESCRIPTION
**Pull request by sutaakar**
Cherrypick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/504

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
I guess this requires full downstream too, right?

**Comment by sutaakar** [comment]
@mswiderski Yes

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Pull request merged**
