### PR TITLE
JBPM-6274 - adding back xmlgraphics:commons (updated version to 2.2) …

### PR DESCRIPTION
**Pull request by tsurdilo**
…until new ipbom release

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mareknovotny @psiroky I think we went full circle on this one (sorry) :). Changes here:

https://github.com/jboss-integration/jboss-integration-platform-bom/commit/204e1f7ea59679a24182aa757836796b2cca7ae5

are not linked to:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/e84ba7ea79864f5ed4d021666e470c0d17aacff6

until new ipbom release and we need for jbpm-designer (master) to compile on jenkins and locally until then. 
This pr allows designer to compile and run fine until that.

**Comment by mareknovotny** [comment]
maybe we should go forward instead of back and release IP-BOM CR3 and upgrade that here to get rid of the unsync deps.

**Comment by mareknovotny** [comment]
@mbiarnes is it possible now to release ip-bom 8.0.0.CR3 with all updates and upgrade it everywhere it is used?

**Comment by psiroky** [comment]
@mbiarnes this should be reverted once we upgrade to ip-bom 8.0.0.CR3.

**Pull request merged**
