### PR TITLE
Upgrade of sshd-core to 2.9.2

### PR DESCRIPTION
**Pull request by mareknovotny**
Upgrading sshd-core to 2.7.0

https://issues.redhat.com/browse/RHDM-1788 and https://issues.redhat.com/browse/RHPAM-3807

**Merge together with PR:**
* https://github.com/kiegroup/appformer/pull/1374

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
ok, i found that 2.7.0 renamed SessionAware to ServerSessionAware and moved to package org.apache.sshd.server.session at https://github.com/apache/mina-sshd/commit/80c5e16cd23dd4727c3542d64e552ad83e7c05e1

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by AntStephenson — APPROVED** [review]

**Comment by mareknovotny** [comment]
ok, now there are 14 failures, some are not related as i could see on the latest FDB in other PRs at least KIE-Server IT tests failing too and hacep test is there too.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
[Test Result](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/) ("14 failed / +5")

1. [org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.hacep/RemoteStreamingKieSessionImplTest/getListKieSessionObjectsTest/)
2.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34125/kie-server-services/services/rest/server'}]
3.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34125/kie-server-services/services/rest/server'}]
4.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34125/kie-server-services/services/rest/server'}]
5.     [org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.workbench.common.services.backend.compiler.rest.client/MavenRestClientTest/org_kie_workbench_common_services_backend_compiler_rest_client_MavenRestClientTest/)
6.     [org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.workbench.common.services.datamodel.backend.server.builder/BuilderConcurrencyIntegrationTest/org_kie_workbench_common_services_datamodel_backend_server_builder_BuilderConcurrencyIntegrationTest/)
7.     [org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.workbench.common.services.datamodel.backend.server.builder/BuilderKieScannerWarningIntegrationTest/org_kie_workbench_common_services_datamodel_backend_server_builder_BuilderKieScannerWarningIntegrationTest/)
8.     [org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest.org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.workbench.common.services.backend.kmodule/KModuleServiceImplIntegrationTest/org_kie_workbench_common_services_backend_kmodule_KModuleServiceImplIntegrationTest/)
9.     [org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.bc/DeploymentIT/org_kie_bc_DeploymentIT/)
10.     [org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.hacep/PodAsLeaderSnapshotTest/processMessagesAsLeaderAndCreateSnapshotTest/)
11.     [org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/263/testReport/junit/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/)
12.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
13.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
14.     org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
8 failures now:

1. [org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.hacep/PodAsLeaderSnapshotTest/processMessagesAsLeaderAndCreateSnapshotTest/)
2. [org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.workbench.common.services.backend.compiler.rest.client/MavenRestClientTest/org_kie_workbench_common_services_backend_compiler_rest_client_MavenRestClientTest/)
3. [org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.workbench.common.services.datamodel.backend.server.builder/BuilderConcurrencyIntegrationTest/org_kie_workbench_common_services_datamodel_backend_server_builder_BuilderConcurrencyIntegrationTest/)
4. [org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.workbench.common.services.datamodel.backend.server.builder/BuilderKieScannerWarningIntegrationTest/org_kie_workbench_common_services_datamodel_backend_server_builder_BuilderKieScannerWarningIntegrationTest/)
5. [org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest.org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.workbench.common.services.backend.kmodule/KModuleServiceImplIntegrationTest/org_kie_workbench_common_services_backend_kmodule_KModuleServiceImplIntegrationTest/)
6. [org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.bc/DeploymentIT/org_kie_bc_DeploymentIT/)
7. [org.kie.hacep.RemoteKieSessionImplTest.getFactCountTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.hacep/RemoteKieSessionImplTest/getFactCountTest/)
8. [org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/265/testReport/junit/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/)

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
ok again the same 8 failures as in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1898#issuecomment-1066063780:

1. org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest

1. org.kie.hacep.RemoteStreamingKieSessionImplTest.getFactCountTest
2. org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore
3. org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest
4. org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest
5. org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest
6. org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest.org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest
7. org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
this time only 5 failures:

1. org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest
2. org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest
3. org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest.org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderKieScannerWarningIntegrationTest
4. org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest.org.kie.workbench.common.services.backend.kmodule.KModuleServiceImplIntegrationTest
5. org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

**Comment by mareknovotny** [comment]
1.-4. failures shows in deep stacktrace possible relation to this upgrade, but need to find out what it breaks it ;)

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
i know this doesn't work @Ginxo, there is a sshd core dependency conflict in Wildfly for tests

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Pull request closed without merging**
