### PR TITLE
DBACLD-145641: upgrade jgit to address important CVEs

### PR DESCRIPTION
**Pull request by porcelli**
related PR: https://github.com/kiegroup/appformer/pull/1418

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Review by yesamer — APPROVED** [review]

**Pull request merged**
