### PR TITLE
Please do not merge GUVNOR-3193  Change Project from a folder in a repo to a repository

### PR DESCRIPTION
**Pull request by Rikkola**
Please do not merge.
Also no need for review, yet.

Just using the build servers to run the tests since they take few hours locally.

https://issues.jboss.org/browse/GUVNOR-3193

The related PRs:
- https://github.com/kiegroup/kie-soup/pull/7
- https://github.com/AppFormer/uberfire/pull/814
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/496
- https://github.com/kiegroup/drools/pull/1402
- https://github.com/kiegroup/kie-wb-common/pull/1015
- https://github.com/kiegroup/drools-wb/pull/566
- https://github.com/kiegroup/jbpm-designer/pull/643
- https://github.com/kiegroup/jbpm-wb/pull/832
- https://github.com/kiegroup/kie-wb-distributions/pull/573

### CODE REVIEW

**Comment by Rikkola** [comment]
This should still be open. But the "reopen" button is disabled for me.

**Comment by manstis** [comment]
I don't have a "re-open" button either.. however the PR contains zero commits and zero files..

**Comment by Rikkola** [comment]
@manstis Well spotted. So the problem must be my push is bad. I closed the guvnor one so though I accidentally also closed this.

**Comment by Rikkola** [comment]
Ah. This must be closed since it just removed asset-mgmt and that moved to uberfire.

**Pull request closed without merging**
