### PR TITLE
[7.67.x-blue] Bump jsoup from 1.14.2 to 1.15.3

### PR DESCRIPTION
**Pull request by Ginxo**
related to:

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2099
* https://github.com/kiegroup/appformer/pull/1314
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2100
* https://github.com/kiegroup/appformer/pull/1315

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
FDB UNSTABLE. Test results:
-  org.guvnor.ala.build.maven.executor.MavenCliOutputTest.buildAppAndWaitForMavenOutputTest	
- org.guvnor.ala.build.maven.executor.MavenProjectConfigExecutorTest.testAPI
- org.guvnor.ala.build.maven.executor.MavenProjectConfigExecutorTest.testReuseTmpDirectoryAPI

Jenkins run fdb

**Comment by Ginxo** [comment]
Different test failures:

* org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered
 please merge

**Review by lampajr — APPROVED** [review]

**Comment by mareknovotny** [comment]
- org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34212/kie-server-services/services/rest/server'}]
- org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34212/kie-server-services/services/rest/server'}]

**Pull request merged**
