### PR TITLE
DROOLS-2253: Upgrade protobuf-java from 2.6.0 to 2.6.1

### PR DESCRIPTION
**Pull request by dmvolod**
Force update version.com.google.protobuf to be able merge kiegroup/drools#1818 and don't wait for next jboss-integration-platform-bom release.

@mareknovotny , @mariofusco could you please to look at this and merge?

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by dmvolod** [comment]
@mareknovotny do  you know why jenkins execute full downstream build? It's just minor library change and fix bugs only with full backward compatibility. May be some problems with CI infrastructure?

**Comment by mareknovotny** [comment]
@dmvolod we usually do the full build (there are multiple repos relying on dependency management) because of any upgrade can be problematic, even it is presented as only micro version upgrade.

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
Closing as the dependent PR https://github.com/kiegroup/drools/pull/1818 was closed in favor of new implementation and protobuf V3

**Pull request closed without merging**
