### PR TITLE
[JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/RHPAM-4417

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project ha-core-infra: Compilation failure: Compilation failure: 
[2022-08-22T12:13:57.272Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_droolsjbpm_integration/drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtils.java:[115,42] cannot find symbol
[2022-08-22T12:13:57.272Z] [ERROR]   symbol:   method get()
[2022-08-22T12:13:57.272Z] [ERROR]   location: class org.apache.kafka.metadata.BrokerState
[2022-08-22T12:13:57.272Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_droolsjbpm_integration/drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtilTest.java:[104,42] cannot find symbol
[2022-08-22T12:13:57.272Z] [ERROR]   symbol:   method get()
[2022-08-22T12:13:57.272Z] [ERROR]   location: class org.apache.kafka.metadata.BrokerState
[2022-08-22T12:13:57.272Z] [ERROR] -> [Help 1]
[2022-08-22T12:13:57.272Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project ha-core-infra: Compilation failure
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-08-22T12:13:57.272Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-08-22T12:13:57.272Z] Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
[2022-08-22T12:13:57.272Z]     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-08-22T12:13:57.272Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-08-22T12:13:57.272Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-08-22T12:13:57.272Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-08-22T12:13:57.272Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
compiler problem with the new version of kafka-client?

**Comment by afalhambra** [comment]
@mareknovotny, yes, I believe there was an issue with HA, I think @jiripetrlik may know?

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by jiripetrlik** [comment]
@elguardian @mareknovotny 
Hello, I've replied in more detailed message in JIRA: https://issues.redhat.com/browse/RHPAM-4417

**Review by afalhambra — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by elguardian** [comment]
Jenkins run fdb

**Pull request merged**
