### PR TITLE
RHBPMS-4819: upgrade batik

### PR DESCRIPTION
**Pull request by mbiarnes**
DON'T MERGE until https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/601 was merged.

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
@mbiarnes  shouldn't this be more about removing managed batik from here and let it only in IP BOM to not duplicate it ?

**Comment by mbiarnes** [comment]
@mareknovotny This PR should be closed since we can't upgrade batik to a greater version (jboos-ip-bom 7.0.0.Final and greater). We rely on batik 1.6.1-1. Look: https://issues.jboss.org/browse/RHBPMS-4819.

**Comment by mareknovotny** [comment]
@mbiarnes not sure the blockage for batik still applies as @tsurdilo sent cherry picked PR https://github.com/kiegroup/jbpm-designer/pull/700 and we will see if that is possible to do that.

**Comment by mbiarnes** [comment]
should this then be reopened?

**Comment by mareknovotny** [comment]
@mbiarnes could you also remove the xmlgraphics-commons dependency management and its version property? here is the move of them to IP-BOM at https://github.com/jboss-integration/jboss-integration-platform-bom/pull/409

**Comment by mbiarnes** [comment]
@mareknovotny  
we have in https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L94 the version 1.4 - in the jboss-ip-bom PR https://github.com/jboss-integration/jboss-integration-platform-bom/pull/409/files there is version 2.2. Are we OK with this update of org.apache.xmlgraphics.commons?

**Comment by mareknovotny** [comment]
@mbiarnes yes, that was requested by @tsurdilo from the referenced jbpm-designer PR #700

**Comment by mbiarnes** [comment]
@mareknovotny DONE

**Comment by mbiarnes** [comment]
but this only can be merged once we have a new jboss-ip-bom 8.0.0.CR3 with
this changes.

**Comment by mareknovotny** [comment]
@mbiarnes yep, btw why don't we switched to IP-BOM 8.0.0-SNAPSHOT back to development?

**Comment by mbiarnes** [comment]
Good question ;)
But if we do a community release we can't rely on SNAPSHOTs -, so the
jboss-ip-bom has to be released.
Then has to be tested if the build runs properly on errai, kie-suop,
uberfire, dashbuilder and kie reps - this could take days.
IMO it is better to do this update separated.
jboss-ip-bom isn't released as often as i.e kie.
Otherwise, if we would release jboss-ip-bom each time we release kie-  we
would have sometimes no changes between one version and the next.

**Comment by tsurdilo** [comment]
could this be merged now? its needed for jbpm-designer

**Comment by mareknovotny** [comment]
i think so, who could merge it @psiroky ?

**Comment by psiroky** [comment]
I think @tsurdilo has the permissions to merge.

**Comment by tsurdilo** [comment]
@psiroky @mareknovotny thanks guys. yes i have permission but was not sure if its ok to merge or not. thanks again!

**Pull request merged**
