### PR TITLE
[7.67.x] [BXMSPROD-1845] elasticsearch removed from appformer

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1845

Related PRs:

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2101
* https://github.com/kiegroup/appformer/pull/1316
* https://github.com/kiegroup/kie-wb-common/pull/3783
* https://github.com/kiegroup/drools-wb/pull/1559
* https://github.com/kiegroup/jbpm-wb/pull/1573
* https://github.com/kiegroup/kie-wb-distributions/pull/1197
* https://github.com/kiegroup/optaplanner-wb/pull/414

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by rgdoliveira** [comment]
@mareknovotny @lampajr just the PR for main (https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2097) that was merged. Are we going to merge this for 7.13.2?

**Comment by mareknovotny** [comment]
the pr set is not the same as on main branch, so DONT MERGE until it is clear out

**Comment by mareknovotny** [comment]
drafted replacement for all changes in one PR set https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2168

**Comment by mareknovotny** [comment]
replacement for this PR set is green so closing it

**Pull request closed without merging**
