### PR TITLE
remove import order restrictions from checkstyle

### PR DESCRIPTION
**Pull request by hasys**

### CODE REVIEW

**Comment by psiroky** [comment]
I am not going to merge this as I agree with having consistent style even for imports. However, if someone else feels like merging this, then please go ahead, I won't block this.

**Comment by ge0ffrey** [comment]
+1 to merge this. I think a consistent style for imports should be a soft constraint (maybe hard for our developer team), but definitely not a hard constraint for contributors.

**Comment by manstis** [comment]
All code-formatting changes need to be accompanied with at least an Eclipse formatter equivalent.

**Comment by hasys** [comment]
I can synchronize it, just have to decide what we want :). I already tried synchronize Eclipse and IDEA import settings and as I found Eclipse have not so many flexible settings as IDEA, at least this rules will have to be changed:

- java.* and javax.* will be two separate groups (will be blank line between them)
- no exceptions for static imports (no stars allowed at all)

**Comment by ederign** [comment]
@hasys hi! do we have any progress on this?

**Comment by hasys** [comment]
@ederign I guess we can close this PR because no one gatekeeper will merge it :)

**Comment by hasys** [comment]
Already fixed on master. PR for 7.4.x branch: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/591

**Pull request closed without merging**
