### PR TITLE
Updated awaitility version to 4.1.0

### PR DESCRIPTION
**Pull request by pibizza**
This update is required to perform the backport on drools of  the pull request [4147](https://github.com/kiegroup/drools/pull/4147)

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
there is an enforcer error for duplicate classes in jars
```
[2022-02-04T11:03:21.162Z] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
[2022-02-04T11:03:21.162Z] Duplicate classes found:
[2022-02-04T11:03:21.162Z] 
[2022-02-04T11:03:21.162Z]   Found in:
[2022-02-04T11:03:21.162Z]     org.hamcrest:hamcrest-core:jar:1.3:test
[2022-02-04T11:03:21.162Z]     org.hamcrest:hamcrest:jar:2.1:test
[2022-02-04T11:03:21.162Z]   Duplicate classes:
[2022-02-04T11:03:21.162Z]     org/hamcrest/Description.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/TypeSafeDiagnosingMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/StringContains.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Condition$Step.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/MatcherAssert.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/SelfDescribing.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsCollectionContaining.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/BaseDescription.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Condition$1.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsSame.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/DescribedAs.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/CombinableMatcher$CombinableEitherMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/BaseMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/FeatureMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/ShortcutCombination.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/CustomTypeSafeMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/CombinableMatcher$CombinableBothMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/internal/SelfDescribingValueIterator.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsAnything.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/AnyOf.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Condition$NotMatched.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/StringStartsWith.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsNot.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Condition.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/internal/SelfDescribingValue.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/CoreMatchers.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/CombinableMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Condition$Matched.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/internal/ReflectiveTypeFinder.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/StringEndsWith.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/AllOf.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/internal/ArrayIterator.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/DiagnosingMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/Is.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/CustomMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/SubstringMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Matcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/StringDescription.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/TypeSafeMatcher.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/Every.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsEqual.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsNull.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/core/IsInstanceOf.class
[2022-02-04T11:03:21.162Z]     org/hamcrest/Description$NullDescription.class

...
[2022-02-04T11:03:21.164Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (ban-duplicated-classes) on project uberfire-nio2-k8s: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2022-02-04T11:03:21.164Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (ban-duplicated-classes) on project uberfire-nio2-k8s: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-02-04T11:03:21.164Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-02-04T11:03:21.164Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2022-02-04T11:03:21.164Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:260)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-02-04T11:03:21.164Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-02-04T11:03:21.164Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-02-04T11:03:21.164Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-02-04T11:03:21.164Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Review by mareknovotny — CHANGES_REQUESTED** [review]
we need to fix Enforcer error

**Comment by pibizza** [comment]
jenkins execute fdb

**Comment by mareknovotny** [comment]
```
[2022-02-11T14:40:24.592Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project drools-core: Compilation failure: Compilation failure: 
[2022-02-11T14:40:24.592Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_drools/drools-core/src/test/java/org/drools/core/util/BinaryHeapQueueTest.java:[35,20] cannot find symbol
[2022-02-11T14:40:24.592Z] [ERROR]   symbol:   class Factory
[2022-02-11T14:40:24.592Z] [ERROR]   location: package org.hamcrest
[2022-02-11T14:40:24.592Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_drools/drools-core/src/test/java/org/drools/core/util/BinaryHeapQueueTest.java:[239,10] cannot find symbol
[2022-02-11T14:40:24.592Z] [ERROR]   symbol:   class Factory
[2022-02-11T14:40:24.592Z] [ERROR]   location: class org.drools.core.util.BinaryHeapQueueTest.IsTuple
```

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mariofusco** [comment]
jenkins do fdb

**Comment by mariofusco** [comment]
@pibizza this PR causes the following compilation failure, very likely due to the upgrade of hamcrest. Can you please give a look?

```
08:56:07  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project drools-core: Compilation failure: Compilation failure: 
08:56:07  [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_drools/drools-core/src/test/java/org/drools/core/util/BinaryHeapQueueTest.java:[35,20] cannot find symbol
08:56:07  [ERROR]   symbol:   class Factory
08:56:07  [ERROR]   location: package org.hamcrest
08:56:07  [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_drools/drools-core/src/test/java/org/drools/core/util/BinaryHeapQueueTest.java:[239,10] cannot find symbol
08:56:07  [ERROR]   symbol:   class Factory
08:56:07  [ERROR]   location: class org.drools.core.util.BinaryHeapQueueTest.IsTuple
08:56:07  [ERROR] -> [Help 1]
08:56:07  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project drools-core: Compilation failure
```

**Comment by pibizza** [comment]
@mariofusco yes. I am trying to fix this with this patch here https://github.com/kiegroup/drools/pull/4218.

**Comment by pibizza** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
appformer needs some changes too, there is a compilation error

**Comment by pibizza** [comment]
@mareknovotny thanks, I have submitted a patch to fix the other project. Hopefully they should be compiled together.

**Comment by pibizza** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
kie-wb-common repository build shows another issue

```
[2022-03-04T21:47:11.020Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze-only) on project drools-wb-scenario-simulation-editor-backend: Dependency problems found -> [Help 1]
[2022-03-04T21:47:11.020Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze-only) on project drools-wb-scenario-simulation-editor-backend: Dependency problems found
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-03-04T21:47:11.020Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-03-04T21:47:11.020Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-03-04T21:47:11.020Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-03-04T21:47:11.020Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-03-04T21:47:11.020Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-03-04T21:47:11.020Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-03-04T21:47:11.021Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency problems found
[2022-03-04T21:47:11.021Z]     at org.apache.maven.plugins.dependency.analyze.AbstractAnalyzeMojo.execute (AbstractAnalyzeMojo.java:253)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-03-04T21:47:11.021Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-03-04T21:47:11.021Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-03-04T21:47:11.021Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-03-04T21:47:11.021Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-03-04T21:47:11.021Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-03-04T21:47:11.021Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by pibizza** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
so this is a giveup of the upgrade? @pibizza

**Comment by pibizza** [comment]
@mareknovotny Yes. I want to move forward the backport from this whole stuff started. I do not know enough of the dependency structure of various projects to decide how is the right way to fix it, and even if I may end up with something that compiles, this is not going to be the good way. I prefer to stop it and learn a bit more.

**Pull request closed without merging**
