### PR TITLE
[JBPM-9269] ibm jdk: Missing sun.security classes for mock-server tests

### PR DESCRIPTION
**Pull request by gmunozfe**
Merge together with https://github.com/kiegroup/jbpm/pull/1719

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
it seems that 
```
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
```
failures are on master branch I saw these failures also on mysql upgrade PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1381 
Do you know why it fails? @gmunozfe @elguardian

**Comment by gmunozfe** [comment]
> it seems that
> 
> ```
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42153/kie-server-services/services/rest/server'}]
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
> org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
> ```
> 
> failures are on master branch I saw these failures also on mysql upgrade PR #1381
> Do you know why it fails? @gmunozfe @elguardian

@mareknovotny I think it's related to [this PR](https://github.com/kiegroup/drools/pull/3029) at drools, just merged by Enrique

**Comment by gmunozfe** [comment]
Jenkins execute full downstream build

**Pull request merged**
