### PR TITLE
[DROOLS-5783] Make droolsjbpm-integration repo independent from appformer

### PR DESCRIPTION
**Pull request by danielezonca**
https://issues.redhat.com/browse/DROOLS-5783

Description:
The goal of this PR is to cleanup `droolsjbpm-integration` repo from unnecessary relation with other repos (in this case `appformer`). It is a sort of followup of this PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505 that tries to do the same but it has been partially reverted because of some remaining usages

Details of this part of the PR:
- adding `kie-soup-security-utils`
- removing `uberfire-security-backend`
- change `repository-list.txt` accordingly

@mareknovotny @Ginxo @lucamolteni @mariofusco 

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1517
* https://github.com/kiegroup/kie-soup/pull/163
* https://github.com/kiegroup/appformer/pull/1073
* https://github.com/kiegroup/droolsjbpm-integration/pull/2306
* https://github.com/kiegroup/kie-wb-common/pull/3472

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by mariofusco — APPROVED** [review]

**Comment by mareknovotny** [comment]
so FDB stops at known compiler error problem in jbpm-wb repository

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by danielezonca** [comment]
jenkins do fdb

**Comment by danielezonca** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
there were some instability in openstack infra, trigerring again

jenkins do fdb

**Comment by danielezonca** [comment]
jenkins do fdb

**Review by mareknovotny — APPROVED** [review]
all green, merging

**Pull request merged**
