### PR TITLE
[RHPAM-4166] Update protobuf to 3.19.4

### PR DESCRIPTION
**Pull request by AntStephenson**
**Thank you for submitting this pull request**

**JIRA**: [RHPAM-4166](https://issues.redhat.com/browse/RHPAM-4166)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by AntStephenson** [comment]
Jenkins run fdb

**Comment by AntStephenson** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by AntStephenson** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
failures seem existing problems on branch

1. org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest   org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42114/kie-server-services/services/rest/server'}]    org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42114/kie-server-services/services/rest/server'}]
2. org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42114/kie-server-services/services/rest/server'}]    org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:37575/kie-server-services/services/rest/server'}]
3. [org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/260/testReport/junit/org.kie.hacep/RemoteStreamingKieSessionImplTest/getListKieSessionObjectsTest/)
4. [org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/260/testReport/junit/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/)
5. org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
6. org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
7. org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.testProcessWithConditionalEvent[XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
i think the failed test seems as flaky? @mariofusco @danielezonca wdyt?

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
LGTM

**Pull request merged**
