### PR TITLE
Configure checkstyle to check header if needed

### PR DESCRIPTION
**Pull request by hasys**
Hi @psiroky, @manstis, @ge0ffrey,

there are settings for CheckStyle to check is header correct or not. It will work as [here](https://github.com/kiegroup/jbpm-wb/blob/master/pom.xml#L35), but can be configurable for every repository.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Full Downstream Build fail is not caused by this commit. It is ready to review/discuss.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
[PR](https://github.com/kiegroup/kie-wb-common/pull/953) submitted to (hopefully) fix the failing test.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @manstis, @ge0ffrey, @psiroky,
nothing new, just changed order of `module`'s due to conflict with our's selenium tests pom.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @ge0ffrey, this build is finally green.
Are you OK with this PR?

**Comment by psiroky** [comment]
@hasys yay! And it only took like 15 builds to make it green. See, not that bad :D

**Comment by hasys** [comment]
@psiroky right, not so bad :) Also, some problems in Full Downstream build and in PR merge process were applied, so in the future it will be even better :)

**Comment by psiroky** [comment]
@ge0ffrey I will merge this since you are on PTO this week. Please let us know in case there is something that should be fixed.

**Pull request merged**
