### PR TITLE
[7.4.x] RHBPMS-5000: Remove old jBPM-Form-Modeler

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes @cristianonicolai could you please review?

IMPORTANT: Don't merge untils there's a fix for this JBPM-6499 on jbpm-designer (https://github.com/kiegroup/jbpm-designer/pull/682)

This PR is a part of an ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/579
https://github.com/kiegroup/kie-wb-common/pull/1240
https://github.com/kiegroup/jbpm-wb/pull/918
https://github.com/kiegroup/kie-wb-distributions/pull/640
https://github.com/kiegroup/kie-wb-playground/pull/40

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@pefernan Let's get this "full downstream" green, then these can be merged.

**Comment by pefernan** [comment]
@manstis ok... I missed your comment.

**Pull request merged**
