### PR TITLE
[RHPAM-3794] upgrade wildfly elytron to version 1.15.5.Final

### PR DESCRIPTION
**Pull request by rgdoliveira**
Jira: https://issues.redhat.com/browse/RHPAM-3794

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rgdoliveira** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by rgdoliveira** [comment]
There are 3 test failures and they don't seem to be related to this PR

[org.kie.hacep.RemoteKieSessionImplTest.getFactCountTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/251/testReport/junit/org.kie.hacep/RemoteKieSessionImplTest/getFactCountTest/) 

[org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/251/testReport/junit/org.kie.workbench.common.services.refactoring.backend.server.indexing/PackageDescrIndexVisitorLogicTest/visitLogicTest/) also failed in recently PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1878

[org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/251/testReport/junit/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/) also failed in recently PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1878

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

the PackageVisitor test failure should go away as it was fixed in https://github.com/kiegroup/kie-wb-common/pull/3727

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by rgdoliveira** [comment]
@mareknovotny now the only test that failed was: 
[org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/253/testReport/junit/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/)

I believe this test is not related to elytron update and we should merge this PR. WDYT?

**Pull request merged**
