### PR TITLE
remove multithread from drools-wb project build

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools-wb/pull/1424

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
From what I understand it LGTM.

**Review by yesamer — CHANGES_REQUESTED** [review]
@Ginxo Please close it, I provided the fix here https://github.com/kiegroup/drools-wb/pull/1426

**Comment by Ginxo** [comment]
@mareknovotny do we keep this PR in spite of `drools-wb` problem resolution?

**Comment by mareknovotny** [comment]
I think we can close it as original issue is gone

**Pull request closed without merging**
