### PR TITLE
Upgrade to ip-bom 8.0.0.CR2

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/errai/errai/pull/307
https://github.com/kiegroup/kie-soup/pull/15
https://github.com/AppFormer/uberfire/pull/916
https://github.com/dashbuilder/dashbuilder/pull/409
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/615
https://github.com/kiegroup/drools-wb/pull/709

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by ryanzhang** [comment]
@mbarkley Hi, Max
Please bear in mind that 8.0.0.CR2 isn't valid, so we are very much likely need to upgrade it again to 8.0.0.CR3 .

**Comment by mbarkley** [comment]
@ryanzhang What do you mean by "isn't valid" and when will there be a release of 8.0.0.CR3 available?

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbiarnes** [comment]
Jenkins, execute full downstream build.

**Comment by mbiarnes** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

I've added a new PR for droolsjbpm-integration that fixes some test failures.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
There are three test failures left:
org.drools.workbench.screens.testscenario.backend.server.indexing.IndexTestScenarioTest.testIndexTestScenario
org.jbpm.bpmn2.StandaloneBPMNProcessTest.testEventBasedSplitBefore[2]
org.kie.workbench.common.forms.editor.backend.indexing.FormDefinitionIndexerTest.testFormsIndexing

Of these three, StandaloneBPMNProcessTest seems to fail on master (at least when I try to build it locally), and FormDefinitionIndexerTest passes for me locally. IndexTestScenarioTest does not fail on master and I can reproduce it locally.

**Comment by jhrcek** [comment]
@mbarkley some more data to support merge decision:
Taking advantage of test failure [history data](http://janhrcek.cz/random-failures/) I can confirm that IndexTestScenarioTest and FormDefinitionIndexerTest have been failing randomly for long time on master, whereas StandaloneBPMNProcessTest doesn't have the kind of failure I see in the full downstream build for this PR

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Okay, now the only test that fails is the BPMNFileIndexerTest, which is also among the flakey tests (thanks again for that @jhrcek!).

IMO this is ready to merge.

//cc @manstis @krisv @mbiarnes

**Comment by mbiarnes** [comment]
@mbarkley @jhrcek @krisv 
seems that there is only one test failing - +1 to merge this, so we can update finally to jboss-ip-bom 8.0.0.CR2

**Pull request merged**
