### PR TITLE
DROOLS-5440 DMN FEEL built-in functions verifiable documentation

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by mareknovotny** [comment]
https://github.com/kiegroup/kie-docs collects the documentation related things, so having here managed asciidoc deps is weird and there is required only plugin(s) for generating it.

**Comment by tarilabs** [comment]
@mareknovotny there is asciidoc managed by the plugin, so this is only added as a dep since I use it for tests here: https://github.com/kiegroup/drools/pull/2953

**Comment by mareknovotny** [comment]
https://issues.redhat.com/browse/DROOLS-5440 doesn't say anything what and why it is done like this

**Comment by mareknovotny** [comment]
if it is for tests, i would expect scope =test and not compile?

**Comment by tarilabs** [comment]
@mareknovotny 
isn't it what I done here:
https://github.com/kiegroup/drools/pull/2953/files#diff-343abfb491ec8d0d69dde38ce7e76ec7R117

?

**Comment by mareknovotny** [comment]
Sorry, but looking just at change without context is really hard to review ;) no information here until I asked and no information on jira

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
not sure what's the intent of FDB on this one, but anyway

```
13:42:13  Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:3.0.1 from/to mirror-central (http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/groups/kie-all/): Connect to bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081 [bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com/10.8.63.227] failed: Connection refused (Connection refused)
```

unrelated,

🎱 

Jenkins execute full downstream build

**Comment by tarilabs** [comment]
🎱:
🎱 

Jenkins execute full downstream build

**Comment by tarilabs** [comment]
```
Test Result (7 failures / +7)
org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:32865/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:32865/kie-server-services/services/rest/server'}]
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testReadinessCheck
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testLivenessCheck
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
```

unrelated.

**Pull request merged**
