### PR TITLE
BXMSPROD-685:BXMSPROD-685: upgrade of io.undertow

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny only one test failed: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/1800/testReport/ (IMO nothing to do)

**Comment by mareknovotny** [comment]
@mbiarnes yes, this error exists on master too, so I think we can merge it.

**Pull request merged**
