### PR TITLE
JBPM-7685: upgrading narayana-jta to 5.9.0.Final

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/JBPM-7685

This is a sync upgrade for narayana-jta version

* https://github.com/kiegroup/droolsjbpm-integration/pull/1554

### CODE REVIEW

**Comment by mareknovotny** [comment]
this is followup update for spring-boot https://github.com/kiegroup/droolsjbpm-integration/pull/1554

**Comment by rsynek** [comment]
@mareknovotny one of the issues fixed in 5.8.2.Final and 5.9.0.Final is https://issues.jboss.org/browse/JBTM-302, so I will retest with 5.9.0.Final and if no regression appears, I would rather go for 5.9.0.Final.

**Comment by mareknovotny** [comment]
@rsynek really? I see that JIRA was resolved on 09/Apr/13 fixed in  5.0.0.M2  ? That is really strange old thing released this year, I am confused.

**Comment by mareknovotny** [comment]
I would like to look here https://issues.jboss.org/projects/JBTM/versions/12337367 and here https://issues.jboss.org/projects/JBTM/versions/12337778 for the issues related.

**Comment by rsynek** [comment]
@mareknovotny I am sorry, I copy-pasted incomplete link, it should have been https://issues.jboss.org/browse/JBTM-3021

**Comment by mareknovotny** [comment]
Updated to 5.9.0.Final

**Comment by mareknovotny** [comment]
as consequence of reverting #820 I am reopening this PR

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
So job for downstream was running too long

```
Build timed out (after 1,175 minutes). Marking the build as aborted.
Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process!
java.lang.RuntimeException: Error while executing Maven process!
	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:65)
	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:130)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:167)
	at hudson.remoting.Channel.call(Channel.java:907)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
	at com.sun.proxy.$Proxy78.join(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1124)
	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:63)
	... 10 more
```

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
So the same test hanged twice in a row at https://github.com/kiegroup/drools/blob/master/drools-persistence/drools-persistence-jpa/src/test/java/org/drools/persistence/command/SimpleBatchExecutionPersistenceTest.java#L64

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
So now it hanged in jbpm tests. I think there is @rsynek's PR with required merge or co-testing with this https://github.com/kiegroup/jbpm/pull/1217

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
rebased

**Comment by mareknovotny** [comment]
failed tests are in http://janhrcek.cz/random-failures/ and only `org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:44581/kie-server-services/services/rest/server'}]` is not marked as random test failure, but this is suspicious to fail for this type of changes.

**Comment by mareknovotny** [comment]
Once more try out just to eliminate that kie-server IT failureJenkins execute full downstream build

**Comment by mareknovotny** [comment]
ok, random tests failed as before and ther are now different tests from `CxfRestWithImportTest`. So imho not relevant and I will merge narayana upgrade

**Pull request merged**
