### PR TITLE
Drools 5258 - Create kie-pmml-bom

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik 

Scope of this PR is to add the kie-pmml-bom.
Such bom is needed by kie-maven-plugin and will be used by kie-pmml-new module, replacing all the dependency management defined in this latter

### CODE REVIEW

**Comment by mareknovotny** [comment]
@gitgabrio where these new artifacts in kie-pmml-bom lives?

**Comment by gitgabrio** [comment]
> @gitgabrio where these new artifacts in kie-pmml-bom lives?

https://github.com/kiegroup/drools/tree/master/kie-pmml-new

**Comment by mareknovotny** [comment]
@gitgabrio  so we will have the old one there too? Is it planned removal of org.drools:kie-pmml?

**Comment by gitgabrio** [comment]
> @gitgabrio so we will have the old one there too? Is it planned removal of org.drools:kie-pmml?

@mareknovotny 
The old org.drools:kie-pmml is planned to be removed ASAP the new one cover the same use cases. In the meantime, the new one has a different artifact name and the this bom will be used only inside the new kie-pmml and inside kie-maven-plugin (for which it has been created)
This is part of this ticket: https://issues.redhat.com/browse/DROOLS-5258

**Comment by gitgabrio** [comment]
> Looks good to me. @gitgabrio Do you plan to import it somewhere in the Drools repository?

@jiripetrlik 
I'm using it inside kie-pmml-new (replacing all the dependencyManagement it is in there :smile: ) in my current branch. So, yes, it will be used as soon as such branch will be merged

**Comment by gitgabrio** [comment]
@mariofusco @danielezonca 
Could you please approve this? 
It is needed because I would like to create a "draft" PR from this branch
https://github.com/gitgabrio/drools/tree/DROOLS-5258
to let you looking/running the code.
Thanks!

**Pull request merged**
