### PR TITLE
DROOLS-6879 : Update to Wildfly core 17.x

### PR DESCRIPTION
**Pull request by Rikkola**
[DROOLS-6879](https://issues.redhat.com/browse/DROOLS-6879)

Testing if FDB passes with the 17.0.0 Wildfly.

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1918
- https://github.com/kiegroup/appformer/pull/1249
- 
<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb


```
[2022-03-18T11:30:24.541Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/filesystem/WildflyUserFileSystemManager.java:[32,47] cannot find symbol
[2022-03-18T11:30:24.541Z] [ERROR]   symbol:   class PropertiesFileLoader
[2022-03-18T11:30:24.541Z] [ERROR]   location: package org.jboss.as.domain.management.security
[2022-03-18T11:30:24.541Z] [ERROR] -> [Help 1]
[2022-03-18T11:30:24.541Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project uberfire-security-management-wildfly: Compilation failure
[2022-03-18T11:30:24.541Z] /home/jenkins/workspace/KIE/main/fdb/droolsjbpm-build-bootstrap-main.fdb/bc/kiegroup_appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/filesystem/WildflyUserFileSystemManager.java:[32,47] cannot find symbol
[2022-03-18T11:30:24.541Z]   symbol:   class PropertiesFileLoader
[2022-03-18T11:30:24.541Z]   location: package org.jboss.as.domain.management.security

```

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by tomasdavidorg** [comment]
@Rikkola shouldn't we also replace:
- https://github.com/kiegroup/drools/blob/main/build-parent/pom.xml#L134
- https://github.com/kiegroup/kie-tools/blob/main/packages/stunner-editors/errai-bom/pom.xml
- https://github.com/kiegroup/kogito-editors-java/blob/main/errai-bom/pom.xml#L145

or they are not related with the issue?

**Comment by Rikkola** [comment]
@tomasdavidorg We likely should. I will look into this.

**Comment by mareknovotny** [comment]
so all is green, @tomasdavidorg could you review please?

**Comment by mareknovotny** [comment]
we need backport to 7.67.x branches too,please @Rikkola

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
