### PR TITLE
[RHPAM-4505] ClassNotFoundException when creating container in Kie se…

### PR DESCRIPTION
**Pull request by tkobayas**
…rver on WAS

- Use xercesImpl-2.12.0.SP04 instead of 2.12.2

**JIRA**:
https://issues.redhat.com/browse/RHPAM-4505

**referenced Pull Requests**: 

* https://github.com/kiegroup/lienzo-tests/pull/140
* https://github.com/kiegroup/kie-wb-common/pull/3775

Changes by RHPAM-4387 in `drools-wb`, `jbpm-wb`, `kie-wb-distributions` were already reverted in main (7.x)

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it. 

A general local execution could be the following one, where the tool clones all dependent projects starting from the `-sp` one and it locally applies the pull request (if it exists) in order to reproduce a complete build scenario for the provided *Pull Request*.

> **Note:** the tool considers multiple *Pull Requests* related to each other if their branches (generally in the forked repositories) have the same name.

``` shell
$ build-chain-action -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url <pull-request-url> -sp kiegroup/kie-wb-distributions [--skipExecution]
```

> Consider changing `kiegroup/kie-wb-distributions` with the correct starting project.

</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
```
[ERROR]  You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```
:(

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by tkobayas** [comment]
FBD:
```
[2022-09-09T16:47:01.475Z] [INFO] [talledLocalContainer] 12:47:01,000 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service org.wildfly.management.http.extensible: org.jboss.msc.service.StartException in service org.wildfly.management.http.extensible: java.net.BindException: Address already in use /127.0.0.1:37048
...

[2022-09-09T16:48:59.381Z] [INFO] [talledLocalContainer] 12:48:56,852 ERROR [org.jboss.as.cli.CommandContext] (main) The controller is not available at localhost:37048: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://localhost:37048. The connection failed: WFLYPRT0053: Could not connect to remote+http://localhost:37048. The connection failed: Connection refused
[2022-09-09T16:48:59.381Z] [INFO] [talledLocalContainer] The controller is not available at localhost:37048: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://localhost:37048. The connection failed: WFLYPRT0053: Could not connect to remote+http://localhost:37048. The connection failed: Connection refused
[2022-09-09T16:48:59.381Z] [ERROR] Ignoring failures during execution
...

[2022-09-09T16:48:59.381Z] [INFO] Running org.kie.server.integrationtests.generator.CustomCaseIdIntegrationTest
[2022-09-09T16:48:59.381Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in org.kie.server.integrationtests.generator.CustomCaseIdIntegrationTest
[2022-09-09T16:48:59.381Z] [ERROR] initializationError(org.kie.server.integrationtests.generator.CustomCaseIdIntegrationTest)  Time elapsed: 0.006 s  <<< ERROR!
[2022-09-09T16:48:59.381Z] java.lang.RuntimeException: Failed to create JMS client configuration!
[2022-09-09T16:48:59.381Z] Caused by: javax.naming.CommunicationException: WFNAM00018: Failed to connect to remote host
[2022-09-09T16:48:59.381Z] Caused by: java.net.ConnectException: Connection refused
[2022-09-09T16:48:59.381Z]
[2022-09-09T16:48:59.638Z] [INFO]
[2022-09-09T16:48:59.638Z] [INFO] Results:
[2022-09-09T16:48:59.638Z] [INFO]
[2022-09-09T16:48:59.638Z] [ERROR] Errors:
[2022-09-09T16:48:59.638Z] [ERROR]   CustomCaseIdIntegrationTest>RestJmsSharedBaseIntegrationTest.data:61->RestJmsSharedBaseIntegrationTest.createKieServicesJmsConfiguration:142 » Runtime
[2022-09-09T16:48:59.638Z] [INFO]
[2022-09-09T16:48:59.638Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
This is a port conflict that occasionally happens. Not related to this PR.

**Review by baldimir — APPROVED** [review]

**Review by rgdoliveira — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
