### PR TITLE
BXMSPROD-598 thorntail-maven-plugin upgraded to 2.7.0

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-598
Depends on https://github.com/thorntail/thorntail/pull/1362 and 2.6.0 release

### CODE REVIEW

**Comment by mareknovotny** [comment]
we need to check all usages of thorntail in for instance droolsjbpm-integration repo.

Jenkins execute full downstream build

**Comment by Ginxo** [comment]
@mareknovotny it won't work yet since thorntail 2.6.0 is not already available

**Comment by Ginxo** [comment]
The rest of the projects have been checked. Just droolsjbpm-integration applies to it, PR created https://github.com/kiegroup/droolsjbpm-integration/pull/1978

**Comment by mareknovotny** [comment]
hmmm, Thorntail is already released AFAIK see Maven Central - https://search.maven.org/artifact/io.thorntail/thorntail/2.6.0.Final/pom

**Comment by Ginxo** [comment]
@mareknovotny this is community release, the non-community one still pending (probably it will take 2 or 3 months). My mistake with 2.6.0.Final, still to be decided.

**Comment by Ginxo** [comment]
Pointing to 2.7.0.Final

**Comment by mareknovotny** [comment]
this PR is waiting for Thorntail 2.7.0.Final avaibility

**Comment by mareknovotny** [comment]
There were another PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1360 merged for upgrading to 2.7.0.Final

**Pull request closed without merging**
