### PR TITLE
RHDM-1338 org.apache.logging.log4j:log4j-api and log4j-core 2.13.2

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

https://issues.redhat.com/browse/RHDM-1338

Related to:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1461
- https://github.com/kiegroup/kie-soup/pull/156
- https://github.com/kiegroup/appformer/pull/1049

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Review by AntStephenson — APPROVED** [review]

**Comment by mareknovotny** [comment]
So there are too many deps on classpath resolved by maven :(
What if we just exclude log4j deps in appformer?

```
[2020-09-15T16:22:21.550Z] [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.2:compile (gwt-compile) on project kie-wb-common-stunner-showcase-project: Failed to execute command line: Error while executing process. Cannot run program "/opt/tools/jdk1.8.0_202/jre/bin/java": error=7, Argument list too long -> [Help 1]
```

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
community build unstable, prod build argument list too long I don't think it's due to this specific change.

**Comment by mareknovotny** [comment]
FDB failures are known current instability in droolsjbpm-integration repository

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
