### PR TITLE
RHPAM-4525 lucene updraded to 6.6.6

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/RHPAM-4525

**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it. 

A general local execution could be the following one, where the tool clones all dependent projects starting from the `-sp` one and it locally applies the pull request (if it exists) in order to reproduce a complete build scenario for the provided *Pull Request*.

> **Note:** the tool considers multiple *Pull Requests* related to each other if their branches (generally in the forked repositories) have the same name.

``` shell
$ build-chain-action -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url <pull-request-url> -sp kiegroup/kie-wb-distributions [--skipExecution]
```

> Consider changing `kiegroup/kie-wb-distributions` with the correct starting project.

</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by lampajr** [comment]
@Ginxo 
1) It seems that upgrading `lucene` version to `6.6.2` is breaking an elasticsearch check:
  ```
  [2022-09-28T09:55:56.619Z] [INFO] Running org.uberfire.ext.metadata.backend.elastic.index.ElasticSearchIndexProviderTest
  [2022-09-28T09:55:56.874Z] [ERROR] Tests run: 8, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.337 s <<< FAILURE! - in org.uberfire.ext.metadata.backend.elastic.index.ElasticSearchIndexProviderTest
  [2022-09-28T09:55:56.874Z] [ERROR] testWithSort(org.uberfire.ext.metadata.backend.elastic.index.ElasticSearchIndexProviderTest)  Time elapsed: 0.021 s  <<< FAILURE!
  [2022-09-28T09:55:56.874Z] java.lang.AssertionError: Version must be upgraded to [6.6.2] is still set to [6.6.1]
  [2022-09-28T09:55:56.874Z] 	at org.elasticsearch.Version.<clinit>(Version.java:181)
  [2022-09-28T09:55:56.874Z] 	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:159)
  [2022-09-28T09:55:56.874Z] 	at org.elasticsearch.common.ParseField.<clinit>(ParseField.java:35)
  [2022-09-28T09:55:56.874Z] 	at org.elasticsearch.index.query.AbstractQueryBuilder.<clinit>(AbstractQueryBuilder.java:53)
  [2022-09-28T09:55:56.874Z] 	at org.elasticsearch.index.query.QueryBuilders.queryStringQuery(QueryBuilders.java:275)
  ```
  It seems we cannot use a version that is different from the one defined in elasticsearch (which is `6.6.1` since we are using elasticsearch `5.6.15`).

2) Furthermore I see that in `kie-soup` project we are overriding `lucene` version to `6.6.6`: https://github.com/kiegroup/kie-soup/blob/main/pom.xml#L55 
Is it worth updating directly to `6.6.6` and removing the override from kie-soup?

**Comment by Ginxo** [comment]
Jenkins run fdb

**Review by lampajr — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins retest this

**Pull request merged**
