### PR TITLE
excluded appformer from update kie versions

### PR DESCRIPTION
**Pull request by mbiarnes**
since appformer will have it's own version

### CODE REVIEW

**Comment by psiroky** [comment]
@mbiarnes we will need to change the version, one way or the other.

**Comment by mbiarnes** [comment]
@psiroky so the appformer(and dashbuilder) will have the same version as kie?

**Comment by psiroky** [comment]
@mbiarnes ultimately yes. Not sure how long will that take though.

**Comment by psiroky** [comment]
But regardless, we will need the ability to change the appformer versions (to whatever value will be chosen).

**Comment by mbiarnes** [comment]
@psiroky ths is a workaround! we have to think about something more stable. 
we could change the update scripts to use also a appformer version. since kie-soup and kie will always have the same version the only second variable will be the version for appformer.
I only know that the nightly builds will crash until this PR is merged (as workaround) or a more stable PR is raised

**Pull request merged**
