### PR TITLE
Switch nightly build to JDK11

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

### CODE REVIEW

**Comment by almope** [comment]
Jenkins execute fdb

**Comment by almope** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
this only partial switch, right? we still need to use `maven.compiler.release` parameter to be 8

**Comment by almope** [comment]
@mareknovotny It's a full switch to JDK 11 compilation but with the `maven.compiler.release` property, which was merged as part of this PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1756

**Comment by mareknovotny** [comment]
ok, i missed that

**Pull request merged**
