### PR TITLE
Infinispan upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**
see https://github.com/kiegroup/droolsjbpm-build-bootstrap/security/dependabot/pom.xml/org.infinispan:infinispan-core/open

Dependent PRs:
- https://github.com/kiegroup/droolsjbpm-integration/pull/2502

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
replacing dependentbot's original one https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1552

**Comment by adrielparedes** [comment]
@mareknovotny an HA test should be done, I will include @tomasdavidorg in this review.

**Comment by tomasdavidorg** [comment]
jenkins do fdb

**Comment by tomasdavidorg** [comment]
FDB Failed on module `uberfire-metadata-backend-infinispan`.

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    org.checkerframework:checker-qual:jar:2.10.0:compile
    org.checkerframework:checker-compat-qual:jar:2.0.0:compile
  Duplicate classes:
    org/checkerframework/checker/formatter/FormatUtil$ExcessiveOrMissingFormatArgumentException.class
    org/checkerframework/checker/formatter/FormatUtil.class
    org/checkerframework/checker/formatter/FormatUtil$IllegalFormatConversionCategoryException.class
    org/checkerframework/checker/regex/RegexUtil$CheckedPatternSyntaxException.class
    org/checkerframework/checker/units/UnitsTools.class
    org/checkerframework/checker/regex/RegexUtil.class
    org/checkerframework/checker/formatter/FormatUtil$Conversion.class
```

**Comment by tomasdavidorg** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
I am still working on exlusions in the build.

**Comment by mareknovotny** [comment]
after guava upgrade to 30.0-jre i can drop some of PR changes with eclusions, so this ISPN upgrade should be easier

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
replaced by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1662

**Pull request closed without merging**
