### PR TITLE
[JBPM-9549] Upgrade SpringBoot to 2.3.4

### PR DESCRIPTION
**Pull request by elguardian**
Jira https://issues.redhat.com/browse/JBPM-9549

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]
lgtm, waiting on green FDB ;)

**Comment by mareknovotny** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
we need some additional exclusion in jbpm-work-items repository
see 
```
[2021-01-21T21:32:14.773Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project jbpm-workitem-itests: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.

 Found in:
[2021-01-21T21:32:14.773Z]     org.glassfish:jakarta.el:jar:3.0.3:compile
[2021-01-21T21:32:14.773Z]     org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.12.Final:compile
```

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
failure unrelated.

**Comment by yurloc** [comment]
The failure is related because the FDB didn't run completely. It didn't build the optaweb-vehicle-routing repository at all and the change in this PR seems to break the repository. I'm working on a fix (https://github.com/kiegroup/optaweb-vehicle-routing/pull/417) but the job hangs.

**Comment by yurloc** [comment]
Reproduced hanging test locally. It's a Spring Boot issue (see https://github.com/spring-projects/spring-boot/issues/24249). They fixed it in https://github.com/spring-projects/spring-boot/releases/tag/v2.3.7.RELEASE.

Alternative solutions like turning the "deferred" mode manually may be possible (haven't tried that) but I would recommend upgrading to at least Spring Boot 2.3.7.

**Comment by yurloc** [comment]
Another issue is with test execution in `optaweb-employee-rostering` - that's the repository immediately before `optaweb-vehicle-routing` on the repository list. The backend has 0 tests run. This is probably also related to the Spring Boot upgrade. I think it could be caused by `junit-jupiter-engine` being replaced by `junit-vintage-engine` or by good old `junit` in the dependency tree. 

Unfortunately in this scenario Surefire runs 0 tests and completes successfully so you won't notice unless you look at the test report. I've seen this before. This needs to be fixed as well (together with the upgrade, not after that).

**Pull request merged**
