### PR TITLE
[BAPL-2054] Update Kafka to 2.8.0

### PR DESCRIPTION
**Pull request by danielezonca**
**JIRA**:  [BAPL-2054](https://issues.redhat.com/browse/BAPL-2054)

Update Kafka to version 2.8.0

PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1714
- https://github.com/kiegroup/droolsjbpm-integration/pull/2568
- https://github.com/kiegroup/jbpm/pull/1996

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by danielezonca** [comment]
Jenkins run fdb

**Comment by danielezonca** [comment]
The build has 7 failed tests ([report](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/23/testReport/)):

> org.kie.server.services.jbpm.kafka.KafkaServerExtensionProducerTest.testSignalSent
> org.kie.server.services.jbpm.kafka.KafkaServerExtensionProducerTest.testMessageSent
> org.kie.server.services.jbpm.kafka.KafkaServerExtensionProducerTest.testSignalSentImplementation
> org.jbpm.event.emitters.kafka.KafkaEventEmitterTest.testProducer
> org.jbpm.event.emitters.kafka.KafkaEventEmitterTest.testProducerExceptionLoggerAtCallback
> org.jbpm.event.emitters.kafka.KafkaEventEmitterTest.testProducerWrongData
> org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

The last one seems to be a timeout while all the other tests are related to Kafka so it could something to fix.
Both [KafkaServerExtensionProducerTest](https://github.com/kiegroup/droolsjbpm-integration/blob/main/kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java) and [KafkaEventEmitterTest](https://github.com/kiegroup/jbpm/blob/main/jbpm-event-emitters/jbpm-event-emitters-kafka/src/test/java/org/jbpm/event/emitters/kafka/KafkaEventEmitterTest.java) look like using a sort of Kafka mocked classes so I expect it will be simple to fix.
@fjtirado You created both of them, can you please have a look the the failures and provide an advice/fix?
(FYI @elguardian)

Let's do another run in the meantime just to be sure

Jenkins run fdb

**Comment by fjtirado** [comment]
@danielezonca fix is easy just calling this constructor  producer = new MockProducer<>(false, new StringSerializer(), new ByteArraySerializer()); ratjer than default one
Do you want me to clone that bapl (we associate PRs to JBPM jiras, not bapls in v7) to jbpm and provide prs?

**Comment by danielezonca** [comment]
Jenkins run fdb

**Comment by danielezonca** [comment]
14 unrelated failures 

> org.kie.workbench.common.dmn.client.docks.navigator.DecisionNavigatorDockTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.DecisionNavigatorItemsProviderTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.DecisionNavigatorObserverTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.DecisionNavigatorViewTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.drds.DMNDiagramsSessionStateTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.drds.DMNDiagramsSessionTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentFilterTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentTest.testGetFile
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentTest.testGetIcon
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentTest.testGetName
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentsItemTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentsItemViewTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentsTest.initializationError
> org.kie.workbench.common.dmn.client.docks.navigator.included.components.DecisionComponentsViewTest.initializationError

**Review by fjtirado — APPROVED** [review]

**Pull request merged**
