### PR TITLE
BXMSPROD-789 Move archiveArtifacts to success post action

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-789

### CODE REVIEW

**Comment by mareknovotny** [comment]
I guess we need to do that in https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/Jenkinsfile.nightly#L147 too

**Comment by mbiarnes** [comment]
are we not interested in seeing failed tests (junit) and artifacts to download in case the BUILD was UNSTABLE ?

**Comment by Ginxo** [comment]
@mareknovotny done

**Comment by mareknovotny** [comment]
we do @mbiarnes

**Comment by Ginxo** [comment]
replaced by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1319

**Pull request closed without merging**
