### PR TITLE
BXMSPROD-902: added -Dcargo.ignore.failures=true for all fullDownstre…

### PR DESCRIPTION
**Pull request by mbiarnes**
…am builds

### CODE REVIEW

**Comment by mareknovotny** [comment]
@mbiarnes do we have a test run somewhere just to see if nothing nonexpected comes from this ?

**Comment by mbiarnes** [comment]
@mareknovotny https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/mbiarnes/job/singleRepository-Test/118/console

**Comment by mareknovotny** [comment]
@mbiarnes merge conflict, please rebase

**Comment by mareknovotny** [comment]
this was closed/forced push from master instead of rebase #1424

**Pull request closed without merging**
