### PR TITLE
DROOLS-4302: security vulnerability:update of org.springframework

### PR DESCRIPTION
**Pull request by mbiarnes**
first step: upgrade to 4.3.18.RELEASE
second step: upgrade to 5.1.3.RELEASE (see https://issues.jboss.org/browse/DROOLS-4302)

### CODE REVIEW

**Comment by danielezonca** [comment]
@mbiarnes 
Latest stable version I can find of 4.3.x branch is [4.3.24.RELEASE](https://mvnrepository.com/artifact/org.springframework/spring-core/4.3.24.RELEASE) so I think we should update directly to that version. Wdyt?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny only one test https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/30/testReport/junit/org.kie.wb.selenium.ui/ProjectLibraryIntegrationTest/importAndBuildProjectFromStockRepository/ failed
I would merge this

**Comment by mareknovotny** [comment]
Don't you want to update to the latest 4.3.24.RELEASE?

**Comment by mbiarnes** [comment]
> Don't you want to update to the latest 4.3.24.RELEASE?

DONE

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

once more just to check if failed Selenium tests are random:

-  `org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded`
-  `org.kie.wb.selenium.ui.LoginIntegrationTest.loginAndLogout`
- `org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository`
-  `org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective`
-  `org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway`

**Comment by mbiarnes** [comment]
@mareknovotny seems not

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny this time failed nother tests:
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/lastCompletedBuild/testReport/

**Comment by mareknovotny** [comment]
These tests are failing on other PRs with upgrades too

```
- org.kie.server.integrationtests.router.rest.KieServerRouterCommandTest.testDefaultIdentityServiceFromMain
- org.kie.server.integrationtests.router.rest.KieServerRouterControllerRecoveryTest.testRecoveryOfCreatedContainerOnController  
- org.kie.server.integrationtests.router.rest.KieServerRouterUnavailabilityRecoveryTest.testReactToUnavailableServersInRouterContainerBasedOperations
```

**Comment by mareknovotny** [comment]
tagging @MarianMacik here for failures on the kie server router integrations tests

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
already upgraded in kiegroup/droolsjbpm-build-bootstrap/pull/1086

**Pull request closed without merging**
