### PR TITLE
DROOLS-2165: Upgrade revapi-maven-plugin from 0.9.4 to 0.9.5

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by psiroky** [comment]
@MarianMacik are you OK with this upgrade?

**Comment by AntStephenson** [comment]
@MarianMacik did you see Petr's comment? are you OK with this upgrade? Thanks!

**Comment by MarianMacik** [comment]
Well, I would try to run full downstream build first to see if everything is OK, but there is 99% chance that it will be. Wdyt?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny lets see if the same test fail
Jenkins execute full downstream build

**Pull request merged**
