### PR TITLE
AF-2333: Apache mina-core library depMgmt removed

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I4f875d4b88ec51b1aa78d3b62c6753e4878e9006

https://issues.jboss.org/browse/AF-2333

Downstream PR kiegroup/kie-wb-common/pull/3020

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 6 tests failed
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/148/testReport/

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny same tests failed

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

I will run it again as @MarianMacik fixed the 3 kie server router test failures in kiegroup/droolsjbpm-integration/pull/1938 yesterday

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

retrigerring FDB as 3 kie server integrations tests were fixed in kiegroup/droolsjbpm-integration/pull/1938

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
the Nexus seems not properly cached through proxy the mina-core dependency which is upgraded here

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Tests fails due some complexity around getting the transitive dependencies, one here is the upgraded mina-core for https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-ala/kie-wb-common-ala-build-maven/pom.xml#L146-L149

While [GWTCodeServerPortLeaserImpl](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-ala/kie-wb-common-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/gwt/GWTCodeServerPortLeaserImpl.java#L31) uses only one utility class from the mentioned mina-core library. I think we can replace it with standard Java API/Class and fixed the unnecessary dependency there.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

```
Error Message

Synchronization failed for defined timeout: 30000 milliseconds.

Stacktrace

java.util.concurrent.TimeoutException: Synchronization failed for defined timeout: 30000 milliseconds.
	at org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testRegisterKieServerAfterStartup(WebSocketKieControllerStartupIntegrationTest.java:141)

```

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
the failed tests are not related AFAIK, but can someone confirm this?

- org.jbpm.services.cdi.test.DeploymentServiceCDIImplWithSyncTest.testDeploymentOfProcessesBySync   
- org.jbpm.services.cdi.test.DeploymentServiceCDIImplWithSyncTest.testUndeploymentOfProcessesBySync

@MarianMacik WDYT?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
