### PR TITLE
upgraded version.com.fasterxml.jackson

### PR DESCRIPTION
**Pull request by mbiarnes**
Does the same as #1012. But for the PR #1012 the same branch name in appformer https://github.com/kiegroup/appformer/pull/756 didn't work propery.
The PR https://github.com/kiegroup/appformer/pull/756 is green!
The same thing will be repeated here assuming that the two PRs with the same branch name will work now.

### CODE REVIEW

**Comment by mbiarnes** [comment]
once green the PR #1012 should be closed

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny when adding exclusions to different reps (jbpm, droolsjbpm-integration) to prevent failings because of duplicated.classes found the downstream build builds until droolsjbm-integration
and complains about a compilation error: https://gist.github.com/mbiarnes/dc1ca6c1222ec141c738c8495a6a1108 - the com.fasterxml.jackson update will require some fixes.

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1021
https://github.com/kiegroup/appformer/pull/758
https://github.com/kiegroup/droolsjbpm-integration/pull/1882
https://github.com/kiegroup/jbpm/pull/1522

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes we should do upgrade again to 2.9.9.2 as 2.10.pr1 seems not completely backward compatible due our Marshaller impl extension. I will let dependent to create new automatic PR for that version

**Pull request closed without merging**
