### PR TITLE
[RHPAM-3489][RHDM-1623] duplicated version.org.apache.xmlgraphics.commons error fixed

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

Related PRs:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1645

`version.org.apache.xmlgraphics.commons` repeated on:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/548244ff02e5dc8749229e4ff060f29a04532a7e/pom.xml#L302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/548244ff02e5dc8749229e4ff060f29a04532a7e/pom.xml#L163

**JIRA**: 

- https://issues.redhat.com/browse/RHPAM-3489
- https://issues.redhat.com/browse/RHDM-1623

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by AntStephenson — APPROVED** [review]

**Comment by mareknovotny** [comment]
Thanks @Ginxo and please do a backport PR for 7.52.x branch too.

**Review by almope — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
@mareknovotny done https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1645

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
I've checked `business-central-*` and `kie-server*` artifacts produced by https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/fdbp/job/droolsjbpm-build-bootstrap-master.fdbp/2/ and `xmlgraphics-commons-2.6.jar` is there. I think we can merge.

**Pull request merged**
