### PR TITLE
remove springfox

### PR DESCRIPTION
**Pull request by Ginxo**
### Referenced pull requests
* https://github.com/kiegroup/optaweb-employee-rostering/pull/792
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1947

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
is this removal related to a jira? what's is the motivation for it?

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
> is this removal related to a jira? what's is the motivation for it?

to remove `io.springfox` stuff since just `optaweb-employee-rostering` is using it,  it's not recommended to use springfox since https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1935, that's why

**Comment by mareknovotny** [comment]
```
[2022-04-12T15:05:08.810Z] Status: Downloaded newer image for cypress/included:4.12.1
[2022-04-12T15:05:15.763Z] Cypress could not verify that this server is running:
[2022-04-12T15:05:15.763Z] 
[2022-04-12T15:05:15.763Z]   > http://localhost:8180
[2022-04-12T15:05:15.763Z] 
[2022-04-12T15:05:15.763Z] We are verifying this server because it has been configured as your `baseUrl`.
[2022-04-12T15:05:15.763Z] 
[2022-04-12T15:05:15.763Z] Cypress automatically waits until your server is accessible before running tests.
[2022-04-12T15:05:15.763Z] 
[2022-04-12T15:05:15.763Z] We will try connecting to it 3 more times...
[2022-04-12T15:05:19.079Z] We will try connecting to it 2 more times...
[2022-04-12T15:05:21.592Z] We will try connecting to it 1 more time...
[2022-04-12T15:05:21.592Z] 
[2022-04-12T15:05:25.762Z] Cypress failed to verify that your server is running.
[2022-04-12T15:05:25.762Z] 
[2022-04-12T15:05:25.762Z] Please start this server and then run Cypress again.
[2022-04-12T15:05:25.762Z] [ERROR] Command execution failed.
[2022-04-12T15:05:25.763Z] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[2022-04-12T15:05:25.763Z]     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
[2022-04-12T15:05:25.763Z]     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
[2022-04-12T15:05:25.763Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
[2022-04-12T15:05:25.763Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
[2022-04-12T15:05:25.763Z]     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-04-12T15:05:25.763Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-04-12T15:05:25.763Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-04-12T15:05:25.763Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-04-12T15:05:25.763Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-04-12T15:05:25.763Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-04-12T15:05:25.763Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-04-12T15:05:25.763Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-04-12T15:05:25.763Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-04-12T15:05:25.763Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
so the same error like in PR CI run for https://github.com/kiegroup/optaweb-employee-rostering/pull/792

**Comment by Ginxo** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
drools failure executing `maven-javadoc-plugin` at `drools-beliefs/target/apidocs` 
```
reason: class file for javax.xml.bind.annotation.XmlAccessType not found
```

Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
@yurloc @mareknovotny ok to merge?

**Comment by mareknovotny** [comment]
i will wait for @yurloc to approve this

**Comment by yurloc** [comment]
This PR looks good but https://github.com/kiegroup/optaweb-employee-rostering/pull/792 does not. 792 seems to remove Swagger API documentation for no reason.

**Comment by Ginxo** [comment]
moved to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1963

**Pull request closed without merging**
