### PR TITLE
bump to xstream 1.4.17

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by lucamolteni — APPROVED** [review]

**Comment by mareknovotny** [comment]
Is this @mariofusco different from dependenbot's PR #1651 ?

**Comment by mariofusco** [comment]
Replaced by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1651

**Pull request closed without merging**
