### PR TITLE
getProjectTriggering job error solved

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**
I would have to find alternatives to "Build Chain Generate Files / File Generation" from a forked project. Meanwhile please consider the solution for the getProjectTriggering problem and I will treat "Build Chain Generate Files / File Generation" in a different one.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mbiarnes — COMMENTED** [review]
is not a fbd and cdb needed here to se if all works as expected?

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run cdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins run upstream

**Comment by Ginxo** [comment]
@mbiarnes tests performed

- **Upstream OK** `[2020-12-02T11:45:05.993Z] Upstream building droolsjbpm-build-bootstrap project for` https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream/job/droolsjbpm-build-bootstrap-master.upstream/5/consoleText
- **Pull Request OK** `Building of project droolsjbpm-build-bootstrap` https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-master.pr/209/consoleText
- **FDB OK** `Compile downstream build of project [droolsjbpm-build-bootstrap]` rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdb/job/droolsjbpm-build-bootstrap-master.fdb/61/consoleText
- **Compile OK** `Compile downstream build of project [droolsjbpm-build-bootstrap]` https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/compile/job/droolsjbpm-build-bootstrap-master.compile/10/consoleText

**Review by mbiarnes — APPROVED** [review]
LGTM taking in account that all tests you did were gren

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
