### PR TITLE
Work around flaky tests by Surefire automatically rerunning them

### PR DESCRIPTION
**Pull request by triceo**

### CODE REVIEW

**Comment by triceo** [comment]
@manstis , @mswiderski I think that this could help with the flakiness that we're seeing in some jBPM tests and some UI tests. One thing I am not sure about is whether or not these settings are inherited by your repos or if I need to add it manually there as well.

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by mareknovotny** [comment]
retrigerring
Jenkins execute full downstream build!

**Comment by triceo** [comment]
Jenkins execute full downstream build

**Comment by baldimir** [comment]
This reduces the possibility of discovering complicated race conditions. I would suggest to revert this here and apply it to the repositories where it is really needed.

**Pull request merged**
