### PR TITLE
BXMSPROD-1353 nodejs v16.2.0

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1353

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by domhanak** [comment]
I am not sure this is something we want for this stream. @tiagobento Could you please confirm?

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by tiagobento** [comment]
@domhanak I'm not against upgrading dependencies, but that's not something we had planned to do during the upgrades on Kogito Tooling.

**Comment by Ginxo** [comment]
error on appformer-js I wouldn't upgrade to node 16.x for now

**Pull request closed without merging**
