### PR TITLE
Bump version.org.jfree.jfreechart from 1.0.19 to 1.5.0

### PR DESCRIPTION
**Pull request by FredPraca**
This pull request is an upgrade of JFreeChart library.
This also allows to remove jcommon dependency.

Requires these changes on optaplanner repo: https://github.com/kiegroup/optaplanner/pull/576

### CODE REVIEW

**Comment by kie-ci7** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
full downstream run has random failing tests, nothing related. Merging.

    org.drools.compiler.integrationtests.CompositeAgendaTest.testCreateHaltDisposeAgenda
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testContentManagerPerspective
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithoutHeader

I've reported the drools one. @mareknovotny Who needs to know about the selenium ones?

**Comment by mareknovotny** [comment]
fyi @tomasdavidorg failing selenium tests above in @ge0ffrey's comment

**Comment by tomasdavidorg** [comment]
@mareknovotny Thanks. I am already working on it https://issues.jboss.org/browse/BAQE-999

**Pull request merged**
