### PR TITLE
AF-2150: updating freemarker to 2.3.28

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I0a0db79b253ff9c600bc1b98da48f4f38bcb98b9

https://issues.jboss.org/browse/AF-2150

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins execute full downstream build

OptaPlanner uses freemarker too in the module optaplanner-benchmark. If this test succeeds, it's probably fine: PlannerBenchmarkFactoryTest

**Comment by mareknovotny** [comment]
not sure why the FDB was not triggered

jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
Build hanged in openshift-drools-hacep at a test:
**20:53:09** [INFO] Running org.kie.hacep.SnapshotOnDemandTest
and timed out after:
**10:02:19** Build timed out (after 1,066 minutes). Marking the build as aborted.
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
completely same failures in FDB like in #1065 so this doesn't relates to these upgrades IMHO
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
