### PR TITLE
ERRAI-1116: bumped up errai to  4.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
merge together with: 
https://github.com/errai/errai/pull/357
https://github.com/kiegroup/appformer/pull/444

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
everything seems fine, @porcelli, @tiagobento please, merge parent PR in errai to get it done today.

**Comment by tiagobento** [comment]
@mareknovotny https://github.com/errai/errai/pull/357 is merged. Thank you.

**Pull request merged**
