### PR TITLE
BXMSPROD-735 downstream.production xml settings pointing to the nightly one

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-735

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by Ginxo** [comment]
production build moved to https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/upstream-downstream/job/droolsjbpm-build-bootstrap.downstream.production/5/

**Comment by mareknovotny** [comment]
just for ref it moves maven settings from kieAll group to rhba-prod-nightly

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Pull request merged**
