### PR TITLE
BXMSPROD-685: upgrade of org.wildfly.security

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny build failed because of duplicated artifacts https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/1841/console   Found in:
    org.wildfly.security:wildfly-elytron-auth:jar:1.10.4.Final:test
    org.wildfly.security:wildfly-elytron:jar:1.10.4.Final:test

**Comment by mareknovotny** [comment]
yes, this is I noticed while I tried to do kiegroup/droolsjbpm-build-bootstrap/pull/1203 and exclude that upgrade from it
`org.wildfly.security:wildfly-elytron:jar` is a uberjar which bundles all reported duplication there. 
So you need to exclude it or exclude all the jars/deps which is constructed from

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny failed always the same test:
 org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest
because of error message. test timed out after 20000 milliseconds
#1220 
#1221
#1232
+1 to merge all three

**Pull request merged**
