### PR TITLE
AF-1511: Consolidate kie-drools-wb and kie-wb into single Business Central distribution

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by jhrcek** [comment]
@jesuino please rebase onto master (to get on top of my selenium update version to make selenium testing these changes work).

**Comment by jesuino** [comment]
@jhrcek done

**Comment by krisv** [comment]
Do NOT merge before any open items on https://issues.jboss.org/browse/BAPL-1080 are resolved.

**Comment by jesuino** [comment]
Closing this in favor of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/849

**Pull request closed without merging**
