### PR TITLE
BXMSPROD-741: Manage Node, npm and yarn versions

### PR DESCRIPTION
**Pull request by yurloc**
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
@yurloc @mareknovotny If we agree with this we will need to upload the npm, yarn and npm binaries to rcm-guest/staging/rhba/dist/ otherwise it will affect to the prod build process

**Comment by yurloc** [comment]
@Ginxo But this PR doesn't change the versions. It just moves them from multiple child POMs their parent. So I would say there's no need to upload new binaries anywhere because of this PR. Maybe I'm missing something around prod build process.

**Comment by mareknovotny** [comment]
@Ginxo we talked about unifying versions across the all kiegroup repos with @yurloc and then he will ask for upgrade and uploading the new version(s) if needed.

**Pull request merged**
