### PR TITLE
JBPM-5967: Upgrade to lienzo 2.0.291-RELEASE.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @hasys 

This is the upgrade to `lienzo 2.0.291-RELEASE`. As usually, created the PR too for IP BOM:
https://github.com/jboss-integration/jboss-integration-platform-bom/pull/372
Thanks!

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@hasys Could you please approve.

**Pull request merged**
