### PR TITLE
[7.67.x] [RHPAM-4536] backport of Snakeyaml upgrade to 1.31

### PR DESCRIPTION
**Pull request by mareknovotny**
**Thank you for submitting this pull request**

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4536

**referenced Pull Requests**: 
cherry pick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2074

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it. 

A general local execution could be the following one, where the tool clones all dependent projects starting from the `-sp` one and it locally applies the pull request (if it exists) in order to reproduce a complete build scenario for the provided *Pull Request*.

> **Note:** the tool considers multiple *Pull Requests* related to each other if their branches (generally in the forked repositories) have the same name.

``` shell
$ build-chain-action -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url <pull-request-url> -sp kiegroup/kie-wb-distributions [--skipExecution]
```

> Consider changing `kiegroup/kie-wb-distributions` with the correct starting project.

</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
[org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x/job/fdb/job/droolsjbpm-build-bootstrap-7.67.x.fdb/52/testReport/org.kie.server.client/LoadBalancerClientTest/testDefaultLoadBalancerNoServersAvailable/) failure is unrelated

jenkins do fdb

**Review by lampajr — APPROVED** [review]
> [2022-10-06T18:38:01.664Z] [INFO]  ----------------------------------------------
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/droolsjbpm-build-bootstrap]. Execution Result: ok. Time: 13s (13087 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-soup]. Execution Result: ok. Time: 2m 11s (131090 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/droolsjbpm-knowledge]. Execution Result: ok. Time: 40.2s (40232 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/drools]. Execution Result: ok. Time: 33m 39.3s (2019383 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/optaplanner]. Execution Result: ok. Time: 8m 23.1s (503169 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/lienzo-core]. Execution Result: ok. Time: 12.5s (12587 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/lienzo-tests]. Execution Result: ok. Time: 31.5s (31571 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/appformer]. Execution Result: ok. Time: 28m 11.7s (1691747 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-uberfire-extensions]. Execution Result: ok. Time: 12.4s (12445 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/jbpm]. Execution Result: ok. Time: 1h 18m 28.8s (4708877 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/droolsjbpm-integration]. Execution Result: ok. Time: 1h 54m 0.6s (6840672 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-wb-playground]. Execution Result: ok. Time: 58.7s (58735 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-wb-common]. Execution Result: ok. Time: 48m 56.3s (2936311 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/drools-wb]. Execution Result: ok. Time: 18m 51.3s (1131341 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/jbpm-work-items]. Execution Result: ok. Time: 18m 41.8s (1121862 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/jbpm-wb]. Execution Result: ok. Time: 10m 49.1s (649185 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/optaplanner-wb]. Execution Result: ok. Time: 2m 46.2s (166247 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-wb-distributions]. Execution Result: ok. Time: 48m 46.4s (2926403 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/process-migration-service]. Execution Result: skipped. Time: not defined
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/optaweb-employee-rostering]. Execution Result: ok. Time: 9m 9.6s (549678 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/optaweb-vehicle-routing]. Execution Result: ok. Time: 3m 3.2s (183218 ms)
[2022-10-06T18:38:01.664Z] [INFO]  [kiegroup/kie-jpmml-integration]. Execution Result: ok. Time: 50.5s (50577 ms)
[2022-10-06T18:38:01.664Z] [INFO]  ----------------------------------------------

The build seems fine.

**Comment by mareknovotny** [comment]
now different 15 failures in IT, so it is definitely flaky.

testing again for the last time, all other branches were green, without any failuere ;)

jenkins do fdb

**Comment by mareknovotny** [comment]
again 2 failures not related to changes

**Comment by mareknovotny** [comment]
the last try
jenkins run fdb

**Comment by lampajr** [comment]
This time failed for this:
```
[2022-10-10T14:33:42.765Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) on project appformer-js: Could not download Node.js: Could not download http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/v12.16.2/node-v12.16.2-linux-x64.tar.gz: Connect to download.devel.redhat.com:80 [download.devel.redhat.com/10.0.14.183] failed: Connection timed out (Connection timed out) -> [Help 1]
[2022-10-10T14:33:42.765Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) on project appformer-js: Could not download Node.js: Could not download http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/v12.16.2/node-v12.16.2-linux-x64.tar.gz
```

It seems a temporary connectivity issue, let's retry.

jenkins run fdb

**Pull request merged**
