### PR TITLE
JBPM-9958 Jsoup library upgrade

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9958](JBPM-9958)

**referenced Pull Requests**: 

* https://github.com/kiegroup/appformer/pull/1216
* https://github.com/kiegroup/kie-wb-common/pull/3710

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by romartin** [comment]
Hey @bxf12315 @mareknovotny 

I had been trying to see why, once doing this jsoup version upgrade, some test case fails for the editor's formulary generation, and honestly after some time looking at it I can't still see the reason behind this issue.

This way, I propose to ask for help from @pefernan . Please @pefernan , can you give this a quick look? I am around if you want to check this together as well. 

As we discussed before, it's weird... the form definition's `readOnly` field is set to `true`, but it should be `false`:

- Test failed: `org.kie.workbench.common.stunner.forms.backend.service.impl.FormDefinitionGeneratorImplTest`
- I have only found a single usage for the jsoup `Parser` class, and it's only for parsgin the task name, I don' see the relationship between the use of jsoup parsing and the readOnly value, yet. See [1].
- I have putted a breakpoint where the readOnly value is set [2] and just found out that this comes from the test case itself, the model is already set to true, instead of false.

So please @pefernan , any ideas on what else to check or change? I don't still see why, once just changing the jsoup version, this fails, because I checked all code in kie-wb-common-forms, and there is only a single usage of jsoup Parser, as commented above... makes no sense :(

[1] https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/main/java/org/kie/workbench/common/forms/jbpm/server/service/impl/BPMNFormModelGeneratorImpl.java#L219
[2] https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/AbstractFieldDefinition.java#L125

Thanks in advance!!!

**Comment by pefernan** [comment]
@romartin @bxf12315 taking a look!

**Comment by pefernan** [comment]
@romartin @bxf12315 just found that the issue is here: https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/main/java/org/kie/workbench/common/forms/jbpm/server/service/impl/BPMNFormModelGeneratorImpl.java#L219

The TaskName value is stored in the bpmn as string in a CDATA (like `"<![CDATA[taskName]]>"`). We are using Jsoup there to obtain the taskname by parsing the CDATA and get the content (`"<![CDATA[taskName]]>"` -> `"taskName"`). In the previous version, `.toString()` is returning the right CDATA content, but looks like in the new version they changed the `.toString()` implementation and it just returns the CDATA as strubg (`"<![CDATA[taskName]]>"`). The fix here would be changing the `BPMNFormModelGeneratorImpl`, either to use the right Jsoup api to get the content or any other mechanism to obtain the content of the CDATA. This results on the `BPMNFormModelGeneratorImpl` resolves the TaskName as `"<![CDATA[taskName]]>"` instead of `"taskName"` to generate the TaskFormModel.

The problem we see in the test is that https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-backend/src/test/java/org/kie/workbench/common/stunner/forms/backend/service/impl/FormDefinitionGeneratorImplTest.java#L356 identifies the form input is readonly based on the taskname. If you look at the console you may notice there are other test failures like too: 
```
java.lang.AssertionError: 
Expecting
  <org.kie.workbench.common.forms.jbpm.model.authoring.task.TaskFormModel@1114a49e>
to have a property or a field named <"taskName"> with value
  <"full">
but value was:
  <"<![CDATA[full]]>">
```

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
failures are not related:
 * org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingServiceTest.testPingSuccess
 * org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

**Pull request merged**
