### PR TITLE
JBPM-7834: Provide OpenShiftStartupStrategy - WB Integration

### PR DESCRIPTION
**Pull request by rhtevan**
Providing a solution for WorkBench integration with KieServer OpenShiftStartupStrategy by implementing a new ServerTemplateOpenShiftStorage.

Related PRs:

- https://github.com/kiegroup/droolsjbpm-integration/pull/1670

- https://github.com/kiegroup/kie-wb-common/pull/2319

- https://github.com/kiegroup/droolsjbpm-integration/pull/1611

### CODE REVIEW

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
Test failures are not related

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar 
Rebased with master

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar it failed again with this 

[FATAL] Non-resolvable parent POM for org.kie.server:kie-server-controller-openshift:[unknown-version]: Could not find artifact **org.kie.server:kie-server-controller:pom:7.17.0-SNAPSHOT** and 'parent.relativePath' points at wrong local POM @ line 6, column 11

Has it been bumped up to 7.18?

**Comment by rhtevan** [comment]
@sutaakar rebased with master

**Comment by rhtevan** [comment]
upgraded version to 7.18 for the new kie-server-controller-openshift module

**Comment by sutaakar** [comment]
@rhtevan Looks like the stax-api needs to be excluded also from https://github.com/kiegroup/kie-wb-distributions/blob/master/business-central-parent/business-monitoring-webapp/pom.xml#L436

**Comment by rhtevan** [comment]
@sutaakar  Excluded stax-api from both business-central and business-monitoring webapp, (https://github.com/kiegroup/kie-wb-distributions/pull/872/commits/8235f92d349eb68609363ad60d35fbc89f042ad5) and opened another PR (https://github.com/kiegroup/kie-wb-distributions/pull/872)

Please retest, thanks!

**Comment by rhtevan** [comment]
Just listed out dependent PRs:
- https://github.com/kiegroup/jbpm-wb/pull/1280
- https://github.com/kiegroup/kie-wb-distributions/pull/872

**Comment by sutaakar** [comment]
jenkins execute compile downstream build

**Comment by rhtevan** [comment]
@mswiderski  @sutaakar 

Please help merge these PRs which are required for 7.3.0 release. QE has completed test, found no issues so far, and acknowledged that it is ok to merge. 

Related PRs to be merged together
1. https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/904
2. https://github.com/kiegroup/kie-wb-distributions/pull/872
3. https://github.com/kiegroup/jbpm-wb/pull/1280
4. https://github.com/kiegroup/droolsjbpm-integration/pull/1705
5. https://github.com/kiegroup/droolsjbpm-integration/pull/1670
6. https://github.com/kiegroup/kie-wb-common/pull/2319

**Pull request merged**
