### PR TITLE
Upgrade Assertj version to 3.14.0

### PR DESCRIPTION
**Pull request by cuijulian**
Jira: https://issues.jboss.org/browse/PLANNER-1695

Is a prerequisite for: https://github.com/kiegroup/optaweb-vehicle-routing/pull/222

Requires: 
https://github.com/kiegroup/kie-wb-common/pull/3042
https://github.com/kiegroup/drools-wb/pull/1270
https://github.com/kiegroup/drools/pull/2666

### CODE REVIEW

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
@mareknovotny Could you please review this PR when you get a chance: https://github.com/kiegroup/drools/pull/2666

It's the only dependent PR left without approval. After that this PR and it's dependent PR's are good to merge.

**Pull request merged**
