### PR TITLE
RHPAM-4387 xercesImpl to 2.12.2

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: 

https://issues.redhat.com/browse/RHPAM-4387

**Referenced Pull Requests**:

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1987
* https://github.com/kiegroup/kie-wb-common/pull/3742
* https://github.com/kiegroup/drools-wb/pull/1543
* https://github.com/kiegroup/jbpm-wb/pull/1550
* https://github.com/kiegroup/kie-wb-distributions/pull/1169
* https://github.com/kiegroup/lienzo-tests/pull/136

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Related to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1718
I'm afraid https://issues.redhat.com/browse/RHPAM-3825 could happen again. Can you  please @MarianMacik @jstastny-cz provide details about how to reproduce https://issues.redhat.com/browse/RHPAM-3825? Thanks

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Review by AntStephenson — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
FDB 24 test errors:

- most of them on droolsjbpm-integration should be fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/2798
- 1 on `kie_wb_distributions/business-central-tests/business-central-tests-gui` 
```
[2022-07-13T16:42:15.119Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 221.698 s <<< FAILURE! - in org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
[2022-07-13T16:42:15.119Z] [ERROR] importAndBuildProjectFromStockRepository(org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest)  Time elapsed: 61.088 s  <<< ERROR!
[2022-07-13T16:42:15.119Z] org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: add-project-dropdown (tried for 15 second(s) with 500 milliseconds interval)
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
[2022-07-13T16:42:15.119Z] Caused by: org.openqa.selenium.NoSuchElementException: 
[2022-07-13T16:42:15.119Z] Cannot locate an element using By.id: add-project-dropdown
[2022-07-13T16:42:15.119Z] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[2022-07-13T16:42:15.119Z] Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
[2022-07-13T16:42:15.119Z] System info: host: 'eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.71.1.el7.x86_64', java.version: '11.0.15'
[2022-07-13T16:42:15.119Z] Driver info: driver.version: unknown
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2022-07-13T16:42:15.119Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
[2022-07-13T16:42:15.119Z] 
[2022-07-13T16:42:15.119Z]
```
not related with this change

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
btw https://github.com/kiegroup/droolsjbpm-build-bootstrap/security/dependabot/36 says 2.12.sp3 should be the better fix

**Comment by Ginxo** [comment]
Jenkins run fdb

**Review by jstastny-cz — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins run fdb

**Pull request merged**
