### PR TITLE
BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1673

### Referenced pull requests

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1935
* https://github.com/kiegroup/optaplanner/pull/1910
* https://github.com/kiegroup/droolsjbpm-integration/pull/2759
* https://github.com/kiegroup/openshift-drools-hacep/pull/129
* https://github.com/kiegroup/optaweb-employee-rostering/pull/785
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/675

### Additiona PRs for optaplanner 8.x

* https://github.com/kiegroup/optaplanner/pull/1909
* https://github.com/kiegroup/optaplanner-quickstarts/pull/317

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
build error fixed by https://github.com/jboss-integration/rhba-installers/pull/110. Relaunching FDB.
Jenkins run fdb

**Comment by Ginxo** [comment]
solving 
```
[2022-04-02T14:50:47.750Z] Duplicate classes found:
[2022-04-02T14:50:47.750Z] 
[2022-04-02T14:50:47.750Z]   Found in:
[2022-04-02T14:50:47.751Z]     org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.60:compile
[2022-04-02T14:50:47.751Z]     jakarta.el:jakarta.el-api:jar:3.0.3:compile
```
at `org.kie:kie-server-spring-boot-autoconfiguration`

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
The FDBP error is realted to[ jboss-integration/bxms-patch-tools](https://github.com/jboss-integration/bxms-patch-tools) should be solved by
https://github.com/jboss-integration/bxms-patch-tools/pull/210

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
FDPB failed due to 
```
[2022-04-04T17:13:51.609Z] cp: cannot stat ‘..workspace/KIE/main/fdbp/droolsjbpm-build-bootstrap-main.fdbp/bc/jboss_integration_bxms_patch_tools/patch-distributions/rhpam/target/checksums/7.12.0.redhat-00007/decision-central-eap7-deployable.txt’: No such file or directory
```
Can you please @rgdoliveira clarify the proper value for https://github.com/jboss-integration/bxms-patch-tools/blob/f1ebc0837fe59fc910f4070b3ec33a48c9ec29f5/pom.xml#L27

**Comment by rgdoliveira** [comment]
@Ginxo as PME is not run for FDPB, I believe the properties in the update-tool should be https://github.com/jboss-integration/bxms-patch-tools/pull/212

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
ok, the last PR is fixed and green, so this FdB should be ok. Merging as we need to start the build

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
