### PR TITLE
upgraded maven.min.version to 3.5.4

### PR DESCRIPTION
**Pull request by mbiarnes**
**merge not before 29.10.2018** - people has to be informed and a few days for preparations are needed

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by ge0ffrey** [comment]
@mareknovotny Can we get this done now? It's after 29 okt.

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@mareknovotny I think we can merge this now - people had enough time to enter their objections

**Pull request merged**
