### PR TITLE
upgrade of jboss-parent

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes what about that kie-user-bom-parent/pom.xml parent? the version should be in sync there https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/kie-user-bom-parent/pom.xml#L10

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by ge0ffrey** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
We need to add also allowed repositories into enforcer as there is this
https://github.com/jboss/jboss-parent-pom/blob/master/pom.xml#L699-L707 which conflicts with our internal Nexus

**Comment by mbiarnes** [comment]
LGTM

**Comment by mareknovotny** [comment]
> We need to add also allowed repositories into enforcer as there is this
> https://github.com/jboss/jboss-parent-pom/blob/master/pom.xml#L699-L707 which conflicts with our internal Nexus

this is now resolved by upgrading our Nexus

**Comment by mareknovotny** [comment]
it seems that the unexpected triggering is for that phrase? @mbiarnes

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
