### PR TITLE
DROOLS-3727: [DMN Designer] Quick Silver: Minimal standalone preparation

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3727

This is in preparation for merging https://github.com/kiegroup/kie-wb-common/tree/DROOLS-3727.

### CODE REVIEW

**Comment by romartin** [comment]
@manstis also if you've to rename modules... probably would be a good change to also rename our `project` modules? Not sure if the word "project" makes much sense for people....

**Comment by romartin** [comment]
@manstis also the commit name still says "QuickSilver"....

**Comment by manstis** [comment]
Closing until such times as we decide to merge these works....

**Comment by romartin** [comment]
@manstis yes thanks, that will happen soon, at least for me - once we create the 7.4 stream branch, let's go ahead with merging this!! (so two week left...) :+1: 
Sorry anyway for the inconveniences. Thx!!

**Pull request closed without merging**
