### PR TITLE
Remove duplicated dependencies

### PR DESCRIPTION
**Pull request by jhrcek**
Replacement for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/623

Depends on https://github.com/kiegroup/jbpm/pull/1090

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Full downstream build failed, because it found duplicated dependency issue in the newly introduced jbpm-workitems-bpmn2 module . I opened another PR in jbpm to fix that: https://github.com/kiegroup/jbpm/pull/1090

**Comment by jhrcek** [comment]
https://github.com/kiegroup/jbpm/pull/1090 was merged, trying again..
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@psiroky full downstream executed to completion (2 failing tests can't possibly be caused by addition of maven enforcer rule) so I think this is ready to merge.

**Comment by psiroky** [comment]
OK, I'll merge. One thing to note is that any project using the kie-parent (outside of the build chain) will need to do the same fixes (removing the duplicated deps).

**Pull request merged**
