### PR TITLE
Update Java Parser from 3.10.2 to 3.13.10

### PR DESCRIPTION
**Pull request by lucamolteni**

### CODE REVIEW

**Comment by mareknovotny** [comment]
hi @lucamolteni, could you please link here a jira?

**Comment by lucamolteni** [comment]
I've just created it @mareknovotny 

https://issues.jboss.org/browse/DROOLS-4065

**Comment by mareknovotny** [comment]
Thanks for that jira!

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by lucamolteni** [comment]
@mareknovotny take a look at this also https://github.com/kiegroup/drools/pull/2353 I'm trying to run full execute downstream build since yesterday

**Comment by mareknovotny** [comment]
ok, I found that incidentally.

We need to have all PRs mentioned here ;)

**Pull request merged**
