### PR TITLE
Upgrade IP BOM to 8.0.0.CR1

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
This will likely require a full alignment with WildFly 11.

**Comment by mbiarnes** [comment]
@psiroky if there are test failures I would say it is dangerous to upgrade.

**Comment by psiroky** [comment]
@mbiarnes we will need to upgrade, sooner or later. The test failures need to be fixed and then it should be safe.

**Comment by psiroky** [comment]
Superseded by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/601

**Pull request closed without merging**
