### PR TITLE
JBPM-8848: Upgrade of thorntail to 2.5.0.Final

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I945e356b9f7aa424b0bf0ccbeeb60774a33717eb

https://issues.jboss.org/browse/JBPM-8848

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Failed `org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable` and I saw the similar failure in this week on other PRs, @sutaakar or @MarianMacik any idea what this causes to not be stable?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Now failing again `org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable`

**Comment by MarianMacik** [comment]
To be honest, I think that the failing test is not associated with this PR and there is no Thorntail dependency used in it. But I don't see that test failing as a part of other droolsjbpm-integration PRs.

jenkins execute full downstream build

**Comment by mareknovotny** [comment]
the same failures like in another PR completely unrelated to the changes :(

```    

- org.kie.server.integrationtests.router.rest.KieServerRouterCommandTest.testDefaultIdentityServiceFromMain
- org.kie.server.integrationtests.router.rest.KieServerRouterControllerRecoveryTest.testRecoveryOfCreatedContainerOnController
- org.kie.server.integrationtests.router.rest.KieServerRouterUnavailabilityRecoveryTest.testReactToUnavailableServersInRouterContainerBasedOperations
```

**Comment by MarianMacik** [comment]
@mareknovotny Then we can merge it I think.

**Comment by mareknovotny** [comment]
tagging @MarianMacik here for failures on the kie server router integrations tests

**Pull request merged**
