### PR TITLE
 JBPM-6148 - New shared module for common web app resources

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
@psiroky Want to review?

**Comment by cristianonicolai** [comment]
jenkins please retest this.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Fixing downstream issue here: https://github.com/kiegroup/droolsjbpm-integration/pull/1119

**Pull request merged**
