### PR TITLE
JBPM-9231: upgrade to the latest Apache Batik 1.13

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/JBPM-9231

There is new version of Apache Batik 1.13

Merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2183 and https://github.com/kiegroup/jbpm-designer/pull/885

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
test comment

**Comment by mbiarnes** [comment]
test comment

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
test

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Test failures:
```
    org.jbpm.persistence.map.impl.JpaBasedPersistenceTest.processWithNotNullStartDateTest[0]
    org.jbpm.persistence.map.impl.JpaBasedPersistenceTest.processWithNotNullStartDateTest[1]
    org.jbpm.persistence.map.impl.MapBasedPersistenceTest.processWithNotNullStartDateTest
```
any idea why @elguardian, @gmunozfe ?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
