### PR TITLE
[AF-1904]: Upgraded ISPN version to 9.4.x

### PR DESCRIPTION
**Pull request by adrielparedes**
# Description

Upgrading ISPN to last version because it contains some new analyzers we need

@ederign @porcelli @tomasdavidorg 

# Related to

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/938
* https://github.com/kiegroup/appformer/pull/663
* https://github.com/kiegroup/kie-wb-common/pull/2531

### CODE REVIEW

**Comment by kie-ci3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by porcelli** [comment]
ok to test

**Comment by adrielparedes** [comment]
[Upgrade - https://issues.jboss.org/browse/AF-1904](https://trello.com/c/1oeK5qMo/12-upgrade-https-issuesjbossorg-browse-af-1904)

**Comment by mareknovotny** [comment]
fyi there were merged https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/923 which moves the version property to IP BOM parent

**Comment by adrielparedes** [comment]
@mareknovotny yes, I talked about this @mbiarnes and we agreed to add a TODO so next release we are goint to move it again to IP-BOM

**Pull request merged**
