### PR TITLE
DROOLS-4848: removing the additional transaction dependency in javado…

### PR DESCRIPTION
**Pull request by mareknovotny**
…c for jdk11

Change-Id: I0c596eb8ea03e06d2a806751c91fa9cae2bd246e

https://issues.redhat.com/browse/DROOLS-4848

### CODE REVIEW

**Comment by mareknovotny** [comment]
I will remove the jdk 9,10 config later

**Comment by baldimir** [comment]
Approving. Is there an option to test with downstream running with JDK 11?

**Comment by mareknovotny** [comment]
I think it should be possible to create job for that we already have setup our nodes with jdk 9-11 https://github.com/kiegroup/kie-jenkins-scripts/blob/master/jenkins-slaves/ansible/kie-rhel7.yml#L16

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
