### PR TITLE
[7.59.x] RHPAM-3510: micro upgrades (#1735)

### PR DESCRIPTION
**Pull request by mbiarnes**
(cherry picked from commit 14a8039a0509e6c09e91becc201db5bbbc80e7b6)

RHPAM-3510: hibernate upgrade

(cherry picked from commit f358e2a16044d4c617634a8e50a5373641644788)

RHPAM-3510: org.jboss* upgrades

(cherry picked from commit 81c3671b6e8ced545f9d33b83e22e6e40d1a5de6)

RHPAM-3510: org.jboss.weld upgrades

RHPAM-3510: upgrade of micro versions
(cherry picked from commit 1b23cfbb806d467ebcc2f1d5a2f72664eca549e6)

**Thank you for submitting this pull request**

**JIRA**: [RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
backport looks ok. Waiting on green light from CI

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mbiarnes** [comment]
@mareknovotny 9 test failures: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.59.x/job/fdb/job/droolsjbpm-build-bootstrap-7.59.x.fdb/4/testReport/

**Comment by mareknovotny** [comment]
yes, not sure if they are random, but i think so

- org.jbpm.services.cdi.test.DeploymentServiceCDIImplWithSyncTest.testDeploymentOfProcessesBySync
- org.jbpm.services.cdi.test.DeploymentServiceCDIImplWithSyncTest.testDeploymentOfProcessesBySync
- org.jbpm.services.cdi.test.DeploymentServiceCDIImplWithSyncTest.testUndeploymentOfProcessesBySync
- org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.testInstallProject[user: REST_PROJECT]
- org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.testDeleteProject[user: REST_PROJECT]
- org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.testGetRepository[user: NO_REST]
- org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.testGetRepository[user: REST_PROJECT]
- org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: NO_REST]
- org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: REST_ALL]

jenkind do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
failures:

- org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.testGetRepository[user: REST_PROJECT]
- org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: NO_REST]
- org.jbpm.workbench.cm.DeploymentIT.org.jbpm.workbench.cm.DeploymentIT
- org.jbpm.workbench.DeploymentIT.testCaseManagementDeployment

I can see the 2 last items for deployment of **jbpm-wb-case-mgmt-showcase-7.59.1-SNAPSHOT-wildfly23.war** locally too. fyi @bxf12315

**Pull request merged**
