### PR TITLE
PLANNER-1627: TaskAssigningPlanning & TaskAssignigRuntime kie-sever extensions (target architecture)

### PR DESCRIPTION
**Pull request by wmedvede**
- Declares the task assigning modules

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @rsynek @triceo this PR includes basically the declaration of the modules that composes the task assigning stuff. Mainly the already merged modules that where located in the temporal module jbpm-task-assigning.
Would you mind review?

Thanks

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Un-related test failed

org.uberfire.backend.server.io.object.ObjectStorageTest.testWriteAndRead

Failing for the past 2 builds (Since Failed#1792 )
Took 0.86 sec.
Error Message
java.lang.NullPointerException
Stacktrace
java.lang.RuntimeException: java.lang.NullPointerException
	at org.uberfire.backend.server.io.object.ObjectStorageImpl.write(ObjectStorageImpl.java:95)
	at org.uberfire.backend.server.io.object.ObjectStorageImpl.write(ObjectStorageImpl.java:77)
	at org.uberfire.backend.server.io.object.ObjectStorageTest.testWriteAndRead(ObjectStorageTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java

**Comment by triceo** [comment]
I think we should invite to review someone who owns the KIE server now.
Although I have to admit I do not know who that is.

**Comment by wmedvede** [comment]
Hi @krisv your name came up in today's sprint planning meeting as the person candidate for approving/reviewing this Kie Server related PR.
Would you mind have look?

Thanks!

FYI @ge0ffrey

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
Non related DMN desinger for kogito tests failed

Test Result (46 failures / +46)
org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:40696/kie-server-services/services/rest/server'}]
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testConnectorKnowledgeRequirement
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testInputData
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testConnectorAuthorityRequirement
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testBasicModel
...

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
Merging based on the investigation of failed tests in FDB.

**Pull request merged**
