### PR TITLE
upgrade version io.undertow due to security vulnerability reported by…

### PR DESCRIPTION
**Pull request by mbiarnes**
… github
 
Upgrade io.undertow:undertow-core to version 1.3.31 or later. For example:

<dependency>
  <groupId>io.undertow</groupId>
  <artifactId>undertow-core</artifactId>
  <version>[1.3.31,)</version>
</dependency>

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes so why have you closed this ? I haven't time to check FDB test results, were they failing?

**Comment by mbiarnes** [comment]
@mareknovotny this is much better: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/Test-jobs/job/kieAllBuild-and-jboss-ip-bom-upgrade-io.undertow/lastCompletedBuild/testReport/

**Comment by mareknovotny** [comment]
@mbiarnes ok, only 4 tests failing. One looks like a config issue and 3 errors could be a temp/random errors with not starting the container or any other issue I can't recognize.

**Pull request closed without merging**
