### PR TITLE
[AF-2310]: Removed deprecated samples project

### PR DESCRIPTION
**Pull request by adrielparedes**
## Related to: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/jbpm-wb/pull/1401
* https://github.com/kiegroup/drools-wb/pull/1256
* https://github.com/kiegroup/kie-wb-distributions/pull/986
* https://github.com/kiegroup/optaplanner-wb/pull/349

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:
 * https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
 * https://github.com/kiegroup/kie-wb-common/pull/2991

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny org.kie.workbench.common.screens.examples.backend.server.ExamplesServiceImplTest.testExistSpace fails in upstream reps and also in https://github.com/kiegroup/kie-wb-common/pull/2991

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Pull request merged**
