### PR TITLE
RHPAM-1878: upgraded byte-buddy

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
hibernate-core 5.3.7 has dependency to byte-buddy 1.8.17
is there an exclusion needed

**Comment by mareknovotny** [comment]
i think there is not needed to exclude it as it is mandatory dependency for hibernate, management of proper version should be enough

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny see if the same tests fail
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny this have to be rebased

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
There is a enforcer error
```
  Found in:
    org.apache.logging.log4j:log4j-api:jar:2.11.1:compile
    net.bytebuddy:byte-buddy:jar:1.9.4:compile
  Duplicate classes:
    META-INF/versions/9/module-info.class
```

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Pull request merged**
