### PR TITLE
RHDM-373 jackson-databind version update from 2.8.9 to 2.8.11.

### PR DESCRIPTION
**Pull request by pszubiak**
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

### CODE REVIEW

**Comment by pszubiak** [comment]
@mbiarnes @domhanak After a discussion we decided to try version update to 2.8.11 instead 2.8.10 because we don't have productized version of 2.8.10.

**Comment by pszubiak** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
btw there is https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/830
so that will require a rebase

**Comment by pszubiak** [comment]
Update to 2.8.11 is a reason of new 11 org.kie.server.integrationtests.jbpm.* tests failures [1]. Version 2.8.10 doesn't produce such errors and has a CVE fix. After discussion, the decision is to update to 2.8.10.

[1] https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.11.x/job/pullrequest/job/kie-soup-downstream-pullrequests-7.11.x/3/#showFailuresLink

**Pull request closed without merging**
