### PR TITLE
BXMSPROD-361 - upgrade of Apache Camel

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/BXMSPROD-361

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@sutaakar any ide why FDB fails on [org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/112/testReport/junit/org.kie.server.client/LoadBalancerClientTest/testDefaultLoadBalancerNoServersAvailable/)

@tomasdavidorg these selenium tests fails too
```
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
```

**Comment by sutaakar** [comment]
I would like to check the Load balancer issue as it may be caused by some dependency incompatibility

**Comment by sutaakar** [comment]
I tried to run the LoadBalancerClientTest with this PR and the test passed. So I guess it is just a random error.

**Comment by mareknovotny** [comment]
ok, thanks @sutaakar.
just for sake of sanity calling again the FDB
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
ok, so now it failed with different test `org.jbpm.workbench.DeploymentIT.org.jbpm.workbench.DeploymentIT`
so I would consider this as good to merge.

**Pull request merged**
