### PR TITLE
[7.5.x] DROOLS-2165: Upgrade revapi-maven-plugin from 0.9.4 to 0.9.5

### PR DESCRIPTION
**Pull request by mbiarnes**
(cherry picked from commit 6b49066cc74fedd0c3a6efe06660562da1ce6b7b)

### CODE REVIEW

**Comment by psiroky** [comment]
@MarianMacik are you OK with this upgrade?

**Comment by mareknovotny** [comment]
Why are there 2 exactly same PRs? https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/640

**Comment by AntStephenson** [comment]
@MarianMacik did you see Petr's comment? are you OK with this upgrade? Thanks!

@mareknovotny these are raised for different branches.

**Comment by mareknovotny** [comment]
@AntStephenson right, I overlooked target branches, thanks for pointing to that.

**Comment by MarianMacik** [comment]
Again, I would rather execute full downstream build first to see if revapi works. Wdyt?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by AntStephenson** [comment]
@mbiarnes Hi - could you check the test results and see if this upgrade is OK? I realise we have some sporadic test failures.

**Comment by MarianMacik** [comment]
It looks that revapi works as expected so regarding this matter I think it is OK.

**Comment by mareknovotny** [comment]
Why to upgrade to version 0.9.5? Is there added `@threadSafe` somewhere in that plugin version/release. I couldn't find it. Am I blind or looking in wrong place - https://github.com/revapi/revapi/commits/revapi-maven-plugin-0.9.5?

**Comment by mareknovotny** [comment]
closing as 7.5.x is at the end of life

**Pull request closed without merging**
