### PR TITLE
Upgrade of commons-beanutils to 1.9.4

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I224ffee183cb7f8aec20a65b417e60c72db509a8

https://issues.redhat.com/browse/BXMSPROD-639

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
The PR related to 1.9.4 `commons-beanutils` change https://github.com/apache/commons-beanutils/pull/7
LGTM

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
failed tests are already exists on master branch :(

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes please take a look and merge if you approve this

**Pull request merged**
