### PR TITLE
BAQE-439 Introduce dependency on Tomcat DBCP for DB connection pooling

### PR DESCRIPTION
**Pull request by rsynek**
@AntStephenson could you please review?

### CODE REVIEW

**Comment by AntStephenson** [comment]
Approved pending a green build

**Comment by rsynek** [comment]
@AntStephenson increased Narayana version to the latest release - makes sense to do it as a part of 
BAQE-439.

**Comment by ryanzhang** [comment]
For some reason, nightly build start to pull org.apache.tomcat:catalina:jar:9.0.10 which does not exist?
What should be the expected tomcat catalina version? should we define it as well?

**Comment by ryanzhang** [comment]
I put another PR to fix the issue I mentioned https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/773

**Pull request merged**
