### PR TITLE
KOGITO-6285 bump antlr4 version

### PR DESCRIPTION
**Pull request by tarilabs**
7.x of https://github.com/kiegroup/drools/pull/4034

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
```
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/kiegroup/droolsjbpm-build-bootstrap/pulls/1828
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1893)
```

😮 

Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins run fdb

**Comment by tarilabs** [comment]
```
15:32:39  + npm install -g @kie/build-chain-action@2.3.26 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
15:32:39  npm ERR! code ETARGET
15:32:39  npm ERR! notarget No matching version found for @kie/build-chain-action@2.3.26.
15:32:39  npm ERR! notarget In most cases you or one of your dependencies are requesting
15:32:39  npm ERR! notarget a package version that doesn't exist.
15:32:39  
15:32:39  npm ERR! A complete log of this run can be found in:
15:32:39  npm ERR!     /home/jenkins/.npm/_logs/2021-11-22T14_32_39_690Z-debug.log
```

🤷 

Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by tarilabs** [comment]
Jenkins run fdb

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
HELLOOO
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by tarilabs** [comment]
jenkins run fdb

**Comment by mareknovotny** [comment]
FDB is running but somthing just postponed the launch so there were like 5 builds due previous comments :(
running one will update the status when it finishes even now it is red (cancelled) https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/179/

**Comment by tarilabs** [comment]
```
09:52:01  [ERROR]  You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```

nice.

Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by tarilabs** [comment]
```
08:52:00  [ERROR]  You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```

Jenkins run cdb

**Review by danielezonca — APPROVED** [review]

**Comment by tarilabs** [comment]
the fbd failure unrelated: ` Build finished. 68611 tests run, 832 skipped, 1 failed. `
```
Test Result (1 failure / +1)
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
```

**Comment by tarilabs** [comment]
```
[2021-11-23T22:15:24.926Z] [INFO] KIE Server :: Spring :: Boot :: Sample ............. FAILURE [  2.407 s]
[2021-11-23T22:15:24.926Z] [INFO] KIE Server :: Spring :: Boot :: Keycloak Sample .... SUCCESS [01:26 min]
[2021-11-23T22:15:24.926Z] [INFO] KIE Server :: Spring :: Boot :: Integration Tests Sample SUCCESS [01:12 min]
[2021-11-23T22:15:24.926Z] [INFO] KIE Server :: Spring :: Boot :: Kafka :: Sample .... SUCCESS [01:27 min]
[2021-11-23T22:15:24.926Z] [INFO] KIE :: Spring :: Boot :: KIE Server Audit Data Replication Auto Configuration :: jBPM SUCCESS [01:13 min]
[2021-11-23T22:15:24.926Z] [INFO] Parent for container tests for Camel integration ... SUCCESS [  0.914 s]
[2021-11-23T22:15:24.926Z] [INFO] camel-container-tests-model ........................ SUCCESS [ 34.027 s]
[2021-11-23T22:15:24.926Z] [INFO] API for container tests for Camel integration ...... SUCCESS [ 27.264 s]
[2021-11-23T22:15:24.926Z] [INFO] WAR for container tests for Camel integration ...... SUCCESS [ 40.776 s]
[2021-11-23T22:15:24.926Z] [INFO] Container tests for Camel integration .............. SUCCESS [  6.823 s]
[2021-11-23T22:15:24.926Z] [INFO] OptaPlanner core GWT wrapper for OptaPlanner Workbench SUCCESS [ 35.395 s]
[2021-11-23T22:15:24.926Z] [INFO] Drools :: High Availability ........................ SUCCESS [  0.720 s]
[2021-11-23T22:15:24.926Z] [INFO] Drools :: High Availability :: HA-Remote ........... SUCCESS [ 44.150 s]
[2021-11-23T22:15:24.926Z] [INFO] Drools :: High Availability :: HA-Core ............. SUCCESS [ 44.448 s]
[2021-11-23T22:15:24.926Z] [INFO] Drools :: High Availability :: HA-Core-Infra ....... SUCCESS [ 45.021 s]
[2021-11-23T22:15:24.926Z] [INFO] Drools and jBPM integration distribution ........... SUCCESS [ 25.660 s]
[2021-11-23T22:15:24.926Z] [INFO] BPMS distribution .................................. SUCCESS [ 23.830 s]
[2021-11-23T22:15:24.926Z] [INFO] BRMS distribution .................................. SUCCESS [ 29.553 s]
[2021-11-23T22:15:24.926Z] [INFO] ------------------------------------------------------------------------
[2021-11-23T22:15:24.926Z] [INFO] BUILD FAILURE
[2021-11-23T22:15:24.926Z] [INFO] ------------------------------------------------------------------------
[2021-11-23T22:15:24.926Z] [INFO] Total time:  15:06 min (Wall Clock)
[2021-11-23T22:15:24.926Z] [INFO] Finished at: 2021-11-23T17:15:24-05:00
[2021-11-23T22:15:24.926Z] [INFO] ------------------------------------------------------------------------
[2021-11-23T22:15:24.926Z] [ERROR] Failed to execute goal on project kie-server-spring-boot-sample: Could not resolve dependencies for project org.kie:kie-server-spring-boot-sample:jar:7.63.0-SNAPSHOT: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory) -> [Help 1]
[2021-11-23T22:15:24.926Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project kie-server-spring-boot-sample: Could not resolve dependencies for project org.kie:kie-server-spring-boot-sample:jar:7.63.0-SNAPSHOT: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
[2021-11-23T22:15:24.926Z] Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.kie:kie-server-spring-boot-sample:jar:7.63.0-SNAPSHOT: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:209)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
[2021-11-23T22:15:24.926Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
[2021-11-23T22:15:24.926Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-11-23T22:15:24.926Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-11-23T22:15:24.926Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
[2021-11-23T22:15:24.926Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.rnorth.duct-tape:duct-tape:jar:1.0.8 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
[2021-11-23T22:15:24.926Z] Caused by: java.io.FileNotFoundException: /home/jenkins/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar.part (No such file or directory)
[2021-11-23T22:15:24.926Z]     at java.io.FileInputStream.open0 (Native Method)
[2021-11-23T22:15:24.926Z]     at java.io.FileInputStream.open (FileInputStream.java:219)
[2021-11-23T22:15:24.926Z]     at java.io.FileInputStream.<init> (FileInputStream.java:157)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy (DefaultFileProcessor.java:162)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy (DefaultFileProcessor.java:150)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.internal.impl.DefaultFileProcessor.move (DefaultFileProcessor.java:251)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:482)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
[2021-11-23T22:15:24.926Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2021-11-23T22:15:24.926Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2021-11-23T22:15:24.926Z]     at java.lang.Thread.run (Thread.java:829)
```

cdb failure looks unrelated.

**Pull request merged**
