### PR TITLE
upgraded errai final version

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Is there a problem with test https://github.com/kiegroup/jbpm/blob/master/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/CaseLogCleanupCommandTest.java#L181 reported as https://issues.redhat.com/browse/JBPM-9187  @elguardian @gmunozfe ?

**Comment by mareknovotny** [comment]
reported also https://issues.redhat.com/browse/DROOLS-5430 for *org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest* failure
All 3 ProcessMigrationTest fails on 
```
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
```

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
