### PR TITLE
AF-2281: Remove unused activemq dependencies

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Tests failures are unrelated. The two selenium tests should be fixed now by https://github.com/kiegroup/kie-wb-distributions/pull/966.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
@mareknovotny I think this is ready to be merged.

**Comment by mareknovotny** [comment]
THere is that test failure, I know this is not related, but still this was failing on different occasions, could we fix that test ?

**Pull request merged**
