### PR TITLE
Cargo 1.6.9 is released

### PR DESCRIPTION
**Pull request by sutaakar**
@mswiderski Please take a look when you have time. No major changes are expected.
@MarianMacik FYI

### CODE REVIEW

**Comment by sutaakar** [comment]
jenkins execute full downstream build

**Comment by MarianMacik** [comment]
@sutaakar jbpm-container looks good, so should be OK.

**Comment by sutaakar** [comment]
FYI this update bring support for WildFly13.

**Comment by mswiderski** [comment]
@sutaakar thanks, maybe it's time to upgrade wildfly then... @porcelli @ederign @manstis could you please put this on the roadmap so for next release (7.11) we could have this (upgrade to wildfly 13) done?

**Pull request merged**
