### PR TITLE
BXMSPROD-746: Upgrade Node, npm and Yarn

### PR DESCRIPTION
**Pull request by yurloc**
https://issues.redhat.com/browse/BXMSPROD-746

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
I would like to check the lock files structure didn't change between those versions before merging please. I plan to have it ready during 04/27.

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
@yurloc @mareknovotny both package-lock.json and yarn.lock files for old and new versions are identical. So https://www.npmjs.com/package/lock-treatment-tool does not need to be updated.

**Comment by yurloc** [comment]
Last FDB finished with 6 unrelated test failures.

**Comment by mareknovotny** [comment]
@jomarko any idea why selenium tests are not properly setup ? 
```
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest
    org.kie.wb.selenium.ui.LoginIntegrationTest.org.kie.wb.selenium.ui.LoginIntegrationTest
    org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest
    org.drools.eclipse.editors.rete.ReteooLayoutFactoryTest.testLayoutRowList
    org.drools.eclipse.editors.rete.ReteooLayoutFactoryTest.testCalculateReteRows
```

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by jomarko** [comment]
@mareknovotny I contacted @Ginxo . We are working of this. We think the new downstream job miss `-Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin` when running actual mvn command.

We reran one of jobs manually. If that help. We will open a PR.

**Comment by Ginxo** [comment]
@jomarko @mareknovotny Jira created https://issues.redhat.com/browse/BXMSPROD-757

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
artifacts uploaded to rcm-guest

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
the selenium test failures are related to https://issues.redhat.com/browse/BXMSPROD-757 https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1292

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by ge0ffrey** [comment]
@mareknovotny @Ginxo Can we have this merged asap? We believe it's breaking optaweb-employee-rostering builds and we're promoting that during a DevNation talk on Friday.

**Comment by Ginxo** [comment]
Jenkins execute compile downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
@ge0ffrey I would prefer to wait for https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/droolsjbpm-build-bootstrap.downstream/46/

**Comment by Ginxo** [comment]
@ge0ffrey @yurloc this are the logs
```
[INFO] Installing node version v11.6.0
[INFO] Downloading http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/node/v11.6.0/node-v11.6.0-linux-x64.tar.gz to /home/jenkins/.m2/repository/com/github/eirslett/node/11.6.0/node-11.6.0-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] Unpacking /home/jenkins/.m2/repository/com/github/eirslett/node/11.6.0/node-11.6.0-linux-x64.tar.gz into /home/jenkins/workspace/KIE/master/upstream-downstream/droolsjbpm-build-bootstrap.downstream/kiegroup_appformer/appformer-js/target/node/tmp
[INFO] Copying node binary from /home/jenkins/workspace/KIE/master/upstream-downstream/droolsjbpm-build-bootstrap.downstream/kiegroup_appformer/appformer-js/target/node/tmp/node-v11.6.0-linux-x64/bin/node to /home/jenkins/workspace/KIE/master/upstream-downstream/droolsjbpm-build-bootstrap.downstream/kiegroup_appformer/appformer-js/target/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 6.9.0
[INFO] Downloading http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/npm/npm-6.9.0.tgz to /home/jenkins/.m2/repository/com/github/eirslett/npm/6.9.0/npm-6.9.0.tar.gz
```
so it seems it's not taking the expected versions

**Comment by yurloc** [comment]
@Ginxo good catch. I just reproduced it locally on `appformer/appformer-js`. Investigating.

**Comment by yurloc** [comment]
@Ginxo I made a mistake. I reproduced it because I forgot to `git pull` in `appformer` so I was using 7.37.0-SNAPSHOT. After I pulled it was correctly installing:
```
[INFO] Installing node version v12.16.2
[INFO] Unpacking /home/jlocker/.m2/repository/com/github/eirslett/node/12.16.2/node-12.16.2-linux-x64.tar.gz into /home/jlocker/src/github.com/kiegroup/appformer/appformer-js/target/node/tmp
[INFO] Copying node binary from /home/jlocker/src/github.com/kiegroup/appformer/appformer-js/target/node/tmp/node-v12.16.2-linux-x64/bin/node to /home/jlocker/src/github.com/kiegroup/appformer/appformer-js/target/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 6.14.4
[INFO] Downloading https://registry.npmjs.org/npm/-/npm-6.14.4.tgz to /home/jlocker/.m2/repository/com/github/eirslett/npm/6.14.4/npm-6.14.4.tar.gz
```

**Comment by yurloc** [comment]
LOL, so the build checks out the source branch of this PR (which is on 7.37.0-SNAPSHOT) but all other repositories are checked out with master.
```
 > git fetch --no-tags --progress https://github.com/yurloc/droolsjbpm-build-bootstrap.git +refs/heads/node-npm-yarn-upgrade:refs/remotes/origin/node-npm-yarn-upgrade # timeout=10
Checking out Revision 79f0613d65eee8eb7b67d32fabcb6536bd96e499 (node-npm-yarn-upgrade)
Commit message: "BXMSPROD-746: Upgrade Yarn to the latest release"
```
```
 > git fetch --no-tags --progress https://github.com/kiegroup/appformer.git +refs/heads/master:refs/remotes/origin/master # timeout=10
Fetching without tags
Checking out Revision 36d3e1b265f59e117192df9fb44137c1297c878f (master)
```

```

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] KIE (Drools, jBPM, OptaPlanner) user BOM parent .... SUCCESS [  2.393 s]
[INFO] KIE :: Build tools ................................. SUCCESS [  1.480 s]
[INFO] KIE BOM (Bill Of Materials) ........................ SUCCESS [  0.011 s]
[INFO] KIE Soup BOM (Bill Of Materials) ................... SUCCESS [  0.010 s]
[INFO] UberFire BOM (Bill Of Materials) ................... SUCCESS [  0.009 s]
[INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.010 s]
[INFO] OptaPlanner BOM (Bill Of Materials) ................ SUCCESS [  0.009 s]
[INFO] jBPM BOM (Bill Of Materials) ....................... SUCCESS [  0.010 s]
[INFO] UberFire Extensions BOM (Bill Of Materials) ........ SUCCESS [  0.011 s]
[INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.011 s]
[INFO] Narayana Integration BOM (Bill Of Materials) ....... SUCCESS [  0.009 s]
[INFO] KIE (Drools, jBPM, OptaPlanner) Platform BOM ....... SUCCESS [  0.010 s]
[INFO] KIE (Drools, jBPM, OptaPlanner) parent 7.37.0-SNAPSHOT SUCCESS [  9.995 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.232 s
[INFO] Finished at: 2020-05-05T06:04:55-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by yurloc** [comment]
@Ginxo rebasing the PR. But this is an issue in my opinion. The PR build should clone the upstream repo (not the fork) with the source branch merged to master. Same what you get if you run
```
git fetch origin pull/1282/merge:PR1282 && git co PR1282
```

**Comment by Ginxo** [comment]
@yurloc the general behaviour is to take the source branche from the user repos and in case they don't exist it will take the master from the target repo. I think it's ok in my opinion.

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
@yurloc same `v11.6.0` version again...

**Comment by mareknovotny** [comment]
I fetched this PR locally and build it with correctly set all versions here set up. We need to look for why the old versions are retained.

**Comment by Ginxo** [comment]
@yurloc @mareknovotny @ge0ffrey I would merge this PR. Please keep https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1305 open. I create a JIRA to investigate the maven problem https://issues.redhat.com/browse/BXMSPROD-778

**Comment by mareknovotny** [comment]
@Ginxo well, if we merge this, I guess the #1305 will lose its testing ability as the version properties will be in master. But I agree this PR can be merged to prove our checking, always can be reverted if it still doesn't play with the new versions of NPM, node or yarn.

**Comment by Ginxo** [comment]
@mareknovotny In case we launch https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1305 FDB job it will keep getting yurloc:TEST-node-npm-yarn-upgrade-2 branch so the testing ability should remain the same. I will close it and create a new testing scenario in case we lose it.

**Comment by yurloc** [comment]
I also think #1305 becomes useless after merging this. We'll need to open a new pair of PRs, one here that introduces a change in `kie-parent`, for example a new property, and another PR to `kie-soup` or `appformer` (because they're right after `droolsjbpm-build-bootsrap`), which must fail if the new property doesn't exist.

**Comment by Ginxo** [comment]
@yurloc the current FDB executions (for the new jobs) are taking the right node/npm/yarn versions https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/deployedRep/job/appformer/388/

**Pull request merged**
