### PR TITLE
[7.5.x] RHBPMS-5000: Remove old jBPM-Form-Modeler

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes @cristianonicolai could you please review?

IMPORTANT: Don't merge untils there's a fix for this JBPM-6499 on jbpm-designer (https://github.com/kiegroup/jbpm-designer/pull/681)

This PR is a part of an ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/580
https://github.com/kiegroup/kie-wb-common/pull/1241
https://github.com/kiegroup/jbpm-wb/pull/919
https://github.com/kiegroup/kie-wb-distributions/pull/641
https://github.com/kiegroup/kie-wb-playground/pull/41

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
@pefernan I have noticed one thing. When you don't have any form for given process/task, on runtime the form is automatically generated. But when there is an old form present instead of dynamic form there is an empty form on runtime. I think it would be better to unify this behavior and generate the dynamic form also when there is only old form present. WDYT?

**Comment by pefernan** [comment]
@jsoltes I have some problems with computer I'll reach you when back to work to talk about this.

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Full build is green here: https://github.com/kiegroup/jbpm-wb/pull/919

**Pull request merged**
