### PR TITLE
RHPAM-670 Upgrade wildfly swarm to 2018.3.3 (for matching Product 7.1.0)

### PR DESCRIPTION
**Pull request by ryanzhang**

### CODE REVIEW

**Comment by ryanzhang** [comment]
Jenkins execute full downstream build

**Comment by ryanzhang** [comment]
Have to retest this because the error in verification job seems to relate to environment issue.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by ryanzhang** [comment]
Jenkins execute full downstream build

**Comment by ryanzhang** [comment]
@mareknovotny Could you please review this change and the failed testcase?
The 2 failed case doesn't seem to relate to the wildfly swarm upgrade.

**Comment by mareknovotny** [comment]
I ran the tests locally and tests fail due enforcer rule

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    org.kie:kie-wb-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
    org.yaml:snakeyaml:jar:1.17:compile
    org.kie:kie-wb-monitoring-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
    org.kie:kie-drools-wb-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
  Duplicate classes:
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockNode.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectBlockMappingSimpleValue.class
    org/yaml/snakeyaml/reader/StreamReader.class
    org/yaml/snakeyaml/tokens/CommentToken.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlOmap.class
    org/yaml/snakeyaml/constructor/SafeConstructor.class
    org/yaml/snakeyaml/tokens/BlockSequenceStartToken.class
    org/yaml/snakeyaml/emitter/ScalarAnalysis.class
    org/yaml/snakeyaml/tokens/FlowSequenceEndToken.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFirstBlockMappingKey.class
    org/yaml/snakeyaml/Yaml$NodeIterable.class
    org/yaml/snakeyaml/representer/BaseRepresenter.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseIndentlessSequenceEntry.class
    org/yaml/snakeyaml/nodes/Tag.class
    org/yaml/snakeyaml/constructor/Constructor$ConstructYamlObject.class
    org/yaml/snakeyaml/events/CollectionStartEvent.class
    org/yaml/snakeyaml/DumperOptions$FlowStyle.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectDocumentStart.class
    org/yaml/snakeyaml/parser/ParserImpl$1.class
    org/yaml/snakeyaml/tokens/FlowMappingEndToken.class
    org/yaml/snakeyaml/introspector/PropertyUtils$1.class
    org/yaml/snakeyaml/reader/UnicodeReader.class
    org/yaml/snakeyaml/Yaml$SilentEmitter.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseImplicitDocumentStart.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowSequenceEntryMappingValue.class
    org/yaml/snakeyaml/tokens/DocumentStartToken.class
    org/yaml/snakeyaml/emitter/Emitter.class
    org/yaml/snakeyaml/nodes/ScalarNode.class
    org/yaml/snakeyaml/events/StreamEndEvent.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlStr.class
    org/yaml/snakeyaml/serializer/Serializer.class
    org/yaml/snakeyaml/scanner/ScannerException.class
    org/yaml/snakeyaml/events/MappingStartEvent.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowSequenceEntryMappingEnd.class
    org/yaml/snakeyaml/events/CollectionEndEvent.class
    org/yaml/snakeyaml/introspector/PropertyUtils.class
    org/yaml/snakeyaml/extensions/compactnotation/CompactConstructor$ConstructCompactObject.class
    org/yaml/snakeyaml/emitter/Emitable.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentString.class
    org/yaml/snakeyaml/resolver/Resolver$1.class
    org/yaml/snakeyaml/constructor/Constructor$ConstructSequence.class
    org/yaml/snakeyaml/events/Event.class
    org/yaml/snakeyaml/reader/ReaderException.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseDocumentContent.class
    org/yaml/snakeyaml/events/ImplicitTuple.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlMap.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFirstFlowSequenceItem.class
    org/yaml/snakeyaml/tokens/DocumentEndToken.class
    org/yaml/snakeyaml/introspector/MissingProperty.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockMappingValue.class
    org/yaml/snakeyaml/nodes/NodeTuple.class
    org/yaml/snakeyaml/serializer/AnchorGenerator.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlInt.class
    org/yaml/snakeyaml/constructor/BaseConstructor$RecursiveTuple.class
    org/yaml/snakeyaml/events/SequenceEndEvent.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFlowMappingSimpleValue.class
    org/yaml/snakeyaml/extensions/compactnotation/PackageCompactConstructor.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockSequenceFirstEntry.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentSet.class
    org/yaml/snakeyaml/Yaml$EventIterable.class
    org/yaml/snakeyaml/error/Mark.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowMappingValue.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentPrimitiveArray.class
    org/yaml/snakeyaml/representer/Represent.class
    org/yaml/snakeyaml/DumperOptions$Version.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFirstBlockSequenceItem.class
    org/yaml/snakeyaml/external/biz/base64Coder/Base64Coder.class
    org/yaml/snakeyaml/introspector/Property.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentEnum.class
    org/yaml/snakeyaml/events/ScalarEvent.class
    org/yaml/snakeyaml/tokens/StreamEndToken.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentBoolean.class
    org/yaml/snakeyaml/tokens/FlowMappingStartToken.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentArray.class
    org/yaml/snakeyaml/scanner/SimpleKey.class
    org/yaml/snakeyaml/scanner/ScannerImpl.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFlowSequenceItem.class
    org/yaml/snakeyaml/resolver/Resolver.class
    org/yaml/snakeyaml/Yaml$YamlIterable.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowMappingKey.class
    org/yaml/snakeyaml/events/StreamStartEvent.class
    org/yaml/snakeyaml/representer/Representer.class
    org/yaml/snakeyaml/events/SequenceStartEvent.class
    org/yaml/snakeyaml/tokens/Token.class
    org/yaml/snakeyaml/serializer/Serializer$1.class
    org/yaml/snakeyaml/nodes/Node.class
    org/yaml/snakeyaml/Yaml$1.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentNull.class
    org/yaml/snakeyaml/serializer/NumberAnchorGenerator.class
    org/yaml/snakeyaml/parser/VersionTagsTuple.class
    org/yaml/snakeyaml/tokens/AliasToken.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentMap.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectBlockMappingKey.class
    org/yaml/snakeyaml/Yaml$2.class
    org/yaml/snakeyaml/composer/ComposerException.class
    org/yaml/snakeyaml/util/UriEncoder.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowMappingFirstKey.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectDocumentRoot.class
    org/yaml/snakeyaml/introspector/GenericProperty.class
    org/yaml/snakeyaml/tokens/BlockEntryToken.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectBlockMappingValue.class
    org/yaml/snakeyaml/Yaml$3.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectBlockSequenceItem.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectDocumentEnd.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockSequenceEntry.class
    org/yaml/snakeyaml/tokens/Token$ID.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentList.class
    org/yaml/snakeyaml/tokens/TagTuple.class
    org/yaml/snakeyaml/tokens/KeyToken.class
    org/yaml/snakeyaml/DumperOptions.class
    org/yaml/snakeyaml/events/DocumentEndEvent.class
    org/yaml/snakeyaml/events/NodeEvent.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlPairs.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseStreamStart.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowSequenceEntry.class
    org/yaml/snakeyaml/extensions/compactnotation/CompactConstructor.class
    org/yaml/snakeyaml/introspector/FieldProperty.class
    org/yaml/snakeyaml/constructor/Constructor$ConstructMapping.class
    org/yaml/snakeyaml/scanner/Constant.class
    org/yaml/snakeyaml/external/com/google/gdata/util/common/base/Escaper.class
    org/yaml/snakeyaml/resolver/ResolverTuple.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFirstDocumentStart.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockMappingFirstKey.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowMappingEmptyValue.class
    org/yaml/snakeyaml/parser/Production.class
    org/yaml/snakeyaml/introspector/MethodProperty.class
    org/yaml/snakeyaml/parser/ParserImpl.class
    org/yaml/snakeyaml/external/com/google/gdata/util/common/base/PercentEscaper.class
    org/yaml/snakeyaml/emitter/EmitterState.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentNumber.class
    org/yaml/snakeyaml/tokens/BlockEndToken.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlTimestamp.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFlowMappingValue.class
    org/yaml/snakeyaml/tokens/FlowSequenceStartToken.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructUndefined.class
    org/yaml/snakeyaml/tokens/ScalarToken.class
    org/yaml/snakeyaml/representer/BaseRepresenter$1.class
    org/yaml/snakeyaml/constructor/Constructor$ConstructScalar.class
    org/yaml/snakeyaml/constructor/Construct.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowSequenceEntryMappingKey.class
    org/yaml/snakeyaml/tokens/DirectiveToken.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlFloat.class
    org/yaml/snakeyaml/tokens/ValueToken.class
    org/yaml/snakeyaml/constructor/CustomClassLoaderConstructor.class
    org/yaml/snakeyaml/parser/ParserException.class
    org/yaml/snakeyaml/tokens/FlowEntryToken.class
    org/yaml/snakeyaml/DumperOptions$ScalarStyle.class
    org/yaml/snakeyaml/tokens/StreamStartToken.class
    org/yaml/snakeyaml/extensions/compactnotation/CompactData.class
    org/yaml/snakeyaml/tokens/WhitespaceToken.class
    org/yaml/snakeyaml/constructor/BaseConstructor.class
    org/yaml/snakeyaml/scanner/Scanner.class
    org/yaml/snakeyaml/constructor/Constructor.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlNull.class
    org/yaml/snakeyaml/util/ArrayStack.class
    org/yaml/snakeyaml/representer/SafeRepresenter.class
    org/yaml/snakeyaml/tokens/TagToken.class
    org/yaml/snakeyaml/composer/Composer.class
    org/yaml/snakeyaml/TypeDescription.class
    org/yaml/snakeyaml/serializer/SerializerException.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlBool.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectStreamStart.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseDocumentEnd.class
    org/yaml/snakeyaml/events/MappingEndEvent.class
    org/yaml/snakeyaml/scanner/ScannerImpl$Chomping.class
    org/yaml/snakeyaml/external/com/google/gdata/util/common/base/UnicodeEscaper$1.class
    org/yaml/snakeyaml/external/com/google/gdata/util/common/base/UnicodeEscaper.class
    org/yaml/snakeyaml/tokens/BlockMappingStartToken.class
    org/yaml/snakeyaml/events/AliasEvent.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseFlowSequenceFirstEntry.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentUuid.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentByteArray.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentDate.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectNothing.class
    org/yaml/snakeyaml/introspector/BeanAccess.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFirstFlowMappingKey.class
    org/yaml/snakeyaml/constructor/AbstractConstruct.class
    org/yaml/snakeyaml/emitter/Emitter$1.class
    org/yaml/snakeyaml/tokens/AnchorToken.class
    org/yaml/snakeyaml/nodes/AnchorNode.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseDocumentStart.class
    org/yaml/snakeyaml/emitter/Emitter$ExpectFlowMappingKey.class
    org/yaml/snakeyaml/representer/Representer$RepresentJavaBean.class
    org/yaml/snakeyaml/external/com/google/gdata/util/common/base/UnicodeEscaper$2.class
    org/yaml/snakeyaml/representer/SafeRepresenter$IteratorWrapper.class
    org/yaml/snakeyaml/Yaml.class
    org/yaml/snakeyaml/emitter/EmitterException.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlSeq.class
    org/yaml/snakeyaml/nodes/NodeId.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlSet.class
    org/yaml/snakeyaml/events/Event$ID.class
    org/yaml/snakeyaml/constructor/SafeConstructor$1.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlBinary.class
    org/yaml/snakeyaml/nodes/MappingNode.class
    org/yaml/snakeyaml/constructor/ConstructorException.class
    org/yaml/snakeyaml/constructor/SafeConstructor$ConstructYamlNumber.class
    org/yaml/snakeyaml/error/YAMLException.class
    org/yaml/snakeyaml/representer/SafeRepresenter$RepresentIterator.class
    org/yaml/snakeyaml/DumperOptions$LineBreak.class
    org/yaml/snakeyaml/nodes/SequenceNode.class
    org/yaml/snakeyaml/events/DocumentStartEvent.class
    org/yaml/snakeyaml/parser/ParserImpl$ParseBlockMappingKey.class
    org/yaml/snakeyaml/parser/Parser.class
    org/yaml/snakeyaml/constructor/Constructor$1.class
    org/yaml/snakeyaml/error/MarkedYAMLException.class
    org/yaml/snakeyaml/nodes/CollectionNode.class

  Found in:
    org.kie:kie-wb-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
    org.kie:kie-wb-monitoring-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
    org.kie:kie-drools-wb-webapp:jar:swarm:7.7.1-SNAPSHOT:compile
  Duplicate classes:
    org/jboss/modules/AbstractLocalLoader.class
    org/jboss/modules/xml/XmlPullParser.class
    org/jboss/modules/DefaultBootModuleLoaderHolder.class
    org/jboss/modules/FilteredResourceLoader.class
    org/wildfly/swarm/bootstrap/modules/GradleResolver.class
    org/jboss/modules/ref/References$2.class
    org/jboss/modules/IterableLocalLoader.class
    org/jboss/modules/FileResourceLoader.class
    org/wildfly/swarm/bootstrap/env/WildFlySwarmManifest.class
    org/jboss/modules/IteratorUtils$1.class
    org/jboss/modules/filter/ClassFilter.class
    __redirected/__TransformerFactory.class
    org/jboss/modules/ModularURLStreamHandlerFactory$1.class
    org/jboss/modules/ModuleFinder.class
    org/jboss/modules/xml/JDKSpecific.class
    org/jboss/modules/ref/PhantomReference.class
    org/jboss/modules/_private/ModulesPrivateAccess.class
    org/jboss/modules/AssertionSetting.class
    org/jboss/modules/NativeLibraryResourceLoader.class
    org/jboss/modules/Module$1.class
    org/wildfly/swarm/bootstrap/modules/BootstrapClasspathModuleFinder.class
    org/wildfly/swarm/bootstrap/util/BootstrapProperties.class
    org/jboss/modules/PropertyWriteAction.class
    org/jboss/modules/ModuleSpec$AliasBuilder.class
    org/jboss/modules/maven/MavenArtifactUtil.class
    __redirected/__XMLInputFactory.class
    org/jboss/modules/PropertyReadAction.class
    org/jboss/modules/filter/SetPathFilter.class
    org/jboss/modules/PathResourceLoader.class
    org/jboss/modules/ref/StrongReference.class
    org/jboss/modules/ClassLoaderLocalLoader.class
    org/jboss/modules/Module$3$1.class
    org/jboss/modules/filter/BooleanClassFilter.class
    org/jboss/modules/xml/PolicyExpander$2.class
    org/jboss/modules/AbstractResourceLoader.class
    org/wildfly/swarm/bootstrap/modules/ClasspathModuleFinder.class
    org/jboss/modules/JarFileResourceLoader.class
    org/jboss/modules/ModularURLStreamHandlerFactory.class
    org/jboss/modules/management/ObjectProperties$Property.class
    org/jboss/modules/Module$Visited.class
    org/jboss/modules/FastCopyHashSet$KeyIterator.class
    org/wildfly/swarm/bootstrap/modules/FunctionalModuleFinder.class
    org/jboss/modules/AliasModuleSpec.class
    org/jboss/modules/management/DependencyInfo.class
    org/wildfly/swarm/bootstrap/Main.class
    org/jboss/modules/ModuleLoader$TempMBeanReg.class
    org/jboss/modules/ModuleSpec.class
    org/jboss/modules/maven/MavenSettings.class
    org/jboss/modules/xml/PolicyExpander.class
    org/jboss/modules/IterableResourceLoader.class
    org/jboss/modules/log/NoopModuleLogger.class
    org/jboss/modules/maven/MavenSettings$Profile.class
    org/jboss/modules/Module$4.class
    org/jboss/modules/Environment$Holder$1.class
    org/jboss/modules/JarModuleFinder.class
    org/jboss/modules/filter/BooleanPathFilter.class
    org/jboss/modules/Environment$Holder.class
    org/jboss/modules/FileEntryResource$1.class
    org/jboss/modules/SecurityActions.class
    org/jboss/modules/LayeredModulePathFactory$1.class
    org/jboss/modules/ModuleLoader$RealMBeanReg$1.class
    __redirected/__SAXParserFactory.class
    org/wildfly/swarm/bootstrap/util/MavenArtifactDescriptor$Builder.class
    org/jboss/modules/Version.class
    org/jboss/modules/management/ObjectProperties.class
    org/jboss/modules/ModularContentHandlerFactory.class
    org/jboss/modules/JDKSpecific$2.class
    org/jboss/modules/xml/ModuleXmlParser.class
    org/jboss/modules/ConcurrentClassLoader.class
    org/jboss/modules/FilteredLocalLoader.class
    __redirected/__DocumentBuilderFactory.class
    __redirected/__XMLEventFactory.class
    org/jboss/modules/PreMain.class
    org/jboss/modules/ModuleLoader$2.class
    org/jboss/modules/ResourceLoaders.class
    org/wildfly/swarm/bootstrap/logging/BootstrapLogger$Level.class
    org/jboss/modules/Version$1.class
    org/jboss/modules/Version$Iterator.class
    org/jboss/modules/ModuleClassLoader$Configuration.class
    org/jboss/modules/FastCopyHashSet.class
    org/jboss/modules/URLResource.class
    org/jboss/modules/FileEntryResource.class
    __redirected/__JAXPRedirected.class
    org/jboss/modules/ref/Reference$Type.class
    org/jboss/modules/ModuleLoader.class
    org/jboss/modules/IteratorUtils.class
    org/jboss/modules/FilteredIterableLocalLoader.class
    org/jboss/modules/Main.class
    org/jboss/modules/xml/XmlPullParserException.class
    org/jboss/modules/JDKSpecific$Hack.class
    org/jboss/modules/management/ModuleLoaderMXBean.class
    org/wildfly/swarm/bootstrap/modules/UberJarMavenResolver.class
    org/jboss/modules/security/ImmediatePermissionFactory.class
    org/wildfly/swarm/bootstrap/util/TempFileManager.class
    org/wildfly/swarm/bootstrap/modules/ContainerModuleFinder.class
    org/wildfly/swarm/bootstrap/util/MavenArtifactDescriptor.class
    org/jboss/modules/ModuleLoader$3.class
    org/jboss/modules/security/FactoryPermissionCollection.class
    org/jboss/modules/Paths.class
    org/jboss/modules/security/ModularProtectionDomain.class
    org/wildfly/swarm/bootstrap/logging/InitialLoggerManager.class
    org/jboss/modules/LocalDependency.class
    org/jboss/modules/Linkage$State.class
    org/jboss/modules/ModuleLoader$RealMBeanReg.class
    org/wildfly/swarm/bootstrap/env/MavenDependencyResolution.class
    org/jboss/modules/Utils.class
    __redirected/__XMLReaderFactory.class
    org/jboss/modules/Version$Serialized.class
    org/jboss/modules/ModuleLoader$1.class
    org/jboss/modules/LocalModuleFinder.class
    org/jboss/modules/filter/ClassFilters.class
    org/jboss/modules/maven/ArtifactCoordinates.class
    org/jboss/modules/filter/PathFilters$1.class
    org/jboss/modules/Module.class
    org/jboss/modules/LayeredModulePathFactory.class
    org/jboss/modules/ModuleDependencySpec.class
    org/jboss/modules/JDKSpecific$1.class
    org/jboss/modules/filter/PathFilters.class
    org/jboss/modules/ModuleLoader$FutureModule.class
    org/jboss/modules/FileEntryResource$2.class
    org/jboss/modules/filter/EqualsPathFilter.class
    org/jboss/modules/maven/MavenResolver.class
    org/jboss/modules/ClassPathModuleLoader.class
    org/jboss/modules/security/PermissionFactory$1.class
    org/wildfly/swarm/bootstrap/env/DependencyResolution.class
    org/jboss/modules/xml/ModuleXmlParser$ResourceRootFactory.class
    org/wildfly/swarm/bootstrap/modules/NestedJarResourceLoader.class
    org/jboss/modules/Metrics.class
    org/jboss/modules/ModuleIdentifier.class
    __redirected/__XMLOutputFactory.class
    org/jboss/modules/ModuleLoadException.class
    org/wildfly/swarm/bootstrap/modules/AbstractSingleModuleFinder.class
    org/wildfly/swarm/bootstrap/env/SystemDependencyResolution.class
    org/jboss/modules/ResourceLoader.class
    org/jboss/modules/ModularURLStreamHandlerFactory$2.class
    org/wildfly/swarm/bootstrap/env/ApplicationEnvironment.class
    org/wildfly/swarm/bootstrap/logging/BackingLoggerManager.class
    org/jboss/modules/ref/Reapable.class
    org/wildfly/swarm/bootstrap/modules/MavenResolvers.class
    org/jboss/modules/filter/GlobPathFilter.class
    org/jboss/modules/security/LoadedPermissionFactory.class
    org/jboss/modules/ModuleSpec$2.class
    org/jboss/modules/maven/MavenSettings$NonProxyHost.class
    org/jboss/modules/LocalModuleFinder$1.class
    org/wildfly/swarm/bootstrap/env/FractionManifest.class
    org/jboss/modules/LocalLoaders.class
    org/jboss/modules/ModuleLoader$MXBeanImpl.class
    org/wildfly/swarm/bootstrap/logging/BackingLogger.class
    org/jboss/modules/JarEntryResource.class
    org/jboss/modules/ref/WeakReference.class
    org/jboss/modules/DependencySpec$3.class
    org/wildfly/swarm/bootstrap/modules/MultiMavenResolver.class
    org/jboss/modules/JarFileResourceLoader$CodeSigners.class
    org/jboss/modules/ref/Reference.class
    org/jboss/modules/log/StreamModuleLogger.class
    org/jboss/modules/ModuleLoader$4.class
    org/jboss/modules/DefaultBootModuleLoaderHolder$1.class
    org/jboss/modules/DependencyTreeViewer.class
    org/wildfly/swarm/bootstrap/logging/BootstrapLogger.class
    org/jboss/modules/LayeredModulePathFactory$LayersConfig.class
    org/wildfly/swarm/bootstrap/env/ManifestComparator.class
    org/jboss/modules/Environment.class
    org/jboss/modules/FastCopyHashSet$1.class
    org/jboss/modules/FilteredIterableResourceLoader.class
    org/wildfly/swarm/bootstrap/modules/BootstrapModuleFinder.class
    org/jboss/modules/PathResource.class
    org/wildfly/swarm/bootstrap/env/DependencyTree.class
    org/jboss/modules/ModuleDependency.class
    org/jboss/modules/filter/InvertingPathFilter.class
    org/jboss/modules/JarModuleLoader.class
    org/jboss/modules/ModuleClassLoader.class
    org/jboss/modules/security/ModularPermissionFactory.class
    org/wildfly/swarm/bootstrap/env/ApplicationEnvironment$Mode.class
    org/wildfly/swarm/bootstrap/performance/Accumulator.class
    org/jboss/modules/ref/References$ReaperThread.class
    org/jboss/modules/ModuleNotFoundException.class
    org/jboss/modules/JDKSpecific.class
    org/jboss/modules/StartTimeHolder.class
    __redirected/__XPathFactory.class
    org/jboss/modules/ModuleClassLoaderDependency.class
    org/wildfly/swarm/bootstrap/performance/Performance.class
    org/jboss/modules/xml/PolicyExpander$1.class
    org/jboss/modules/NativeLibraryResourceLoader$Identification.class
    org/jboss/modules/ModuleClassLoaderFactory.class
    org/jboss/modules/log/ModuleLogRecord.class
    org/wildfly/swarm/bootstrap/logging/LevelNode.class
    org/jboss/modules/security/UninitializedPermission.class
    org/jboss/modules/ref/References.class
    org/wildfly/swarm/bootstrap/MainInvoker.class
    org/jboss/modules/filter/MultiplePathFilterBuilder.class
    org/jboss/modules/IterableModuleFinder.class
    org/jboss/modules/DependencySpec$1.class
    org/jboss/modules/Module$3.class
    org/jboss/modules/ResourceLoaderSpec.class
    org/wildfly/swarm/bootstrap/modules/BootstrapModuleFinder$1.class
    org/wildfly/swarm/bootstrap/util/BootstrapUtil.class
    org/jboss/modules/ConcreteModuleSpec.class
    org/jboss/modules/filter/PathClassFilter.class
    org/jboss/modules/log/ModuleLogger.class
    org/wildfly/swarm/bootstrap/env/WildFlySwarmManifest$1.class
    org/wildfly/swarm/bootstrap/modules/ApplicationModuleFinder.class
    org/jboss/modules/ModuleClassLoader$1.class
    org/jboss/modules/Resource.class
    org/jboss/modules/Linkage.class
    org/jboss/modules/management/ModuleInfo.class
    org/jboss/modules/NativeLibraryResourceLoader$Identification$1.class
    org/jboss/modules/PathUtils.class
    org/jboss/modules/Module$2.class
    org/jboss/modules/JDKPaths.class
    org/jboss/modules/filter/ChildPathFilter.class
    org/jboss/modules/ModuleSpec$Builder.class
    org/jboss/modules/xml/ModuleXmlParser$DefaultResourceRootFactory.class
    org/jboss/modules/xml/MXParser.class
    org/wildfly/swarm/bootstrap/modules/DynamicModuleFinder.class
    org/jboss/modules/ref/Reaper.class
    org/jboss/modules/maven/DefaultMavenResolver.class
    org/jboss/modules/LocalLoader.class
    org/jboss/modules/ref/References$1.class
    org/jboss/modules/ModuleLoader$MBeanReg.class
    org/jboss/modules/ref/SoftReference.class
    __redirected/__SchemaFactory.class
    org/wildfly/swarm/bootstrap/performance/ContextualizedEvent.class
    org/jboss/modules/DependencySpec.class
    org/jboss/modules/maven/JDKSpecific.class
    org/jboss/modules/filter/AggregatePathFilter.class
    org/jboss/modules/DependencySpec$2.class
    __redirected/__DatatypeFactory.class
    org/jboss/modules/maven/MavenSettings$Proxy.class
    org/jboss/modules/JarFileResourceLoader$1.class
    org/wildfly/swarm/bootstrap/logging/InitialBackingLogger.class
    org/jboss/modules/filter/MultiplePathFilter.class
    org/jboss/modules/LocalModuleLoader.class
    org/jboss/modules/filter/PathFilter.class
    org/jboss/modules/ModuleSpec$1.class
    org/jboss/modules/ModulesPolicy.class
    org/wildfly/swarm/bootstrap/modules/NestedJarResourceLoader$1.class
    org/jboss/modules/ModuleClassLoader$2.class
    org/jboss/modules/Dependency.class
    org/jboss/modules/ClassifyingModuleLoader.class
    org/jboss/modules/SecurityActions$2.class
    __redirected/__RedirectedUtils.class
    org/jboss/modules/ClassSpec.class
    org/wildfly/swarm/bootstrap/modules/BootModuleLoader.class
    org/jboss/modules/NamedClassLoader.class
    org/wildfly/swarm/bootstrap/performance/TimedEvent.class
    org/jboss/modules/management/ResourceLoaderInfo.class
    org/jboss/modules/security/PermissionFactory.class
    org/jboss/modules/PackageSpec.class
    __redirected/__RedirectedUtils$1.class
    org/wildfly/swarm/bootstrap/util/JarFileManager.class
    org/jboss/modules/log/JDKModuleLogger.class
    org/jboss/modules/ModuleLoadError.class
    org/jboss/modules/SecurityActions$1.class

  Found in:
    xml-apis:xml-apis-ext:jar:1.3.04:compile
    org.w3c.css:sac:jar:1.3:compile
  Duplicate classes:
    org/w3c/css/sac/helpers/ParserFactory.class
    org/w3c/css/sac/SiblingSelector.class
    org/w3c/css/sac/CharacterDataSelector.class
    org/w3c/css/sac/DescendantSelector.class
    org/w3c/css/sac/SelectorList.class
    org/w3c/css/sac/NegativeCondition.class
    org/w3c/css/sac/Condition.class
    org/w3c/css/sac/ConditionFactory.class
    org/w3c/css/sac/ConditionalSelector.class
    org/w3c/css/sac/ElementSelector.class
    org/w3c/css/sac/LangCondition.class
    org/w3c/css/sac/SACMediaList.class
    org/w3c/css/sac/NegativeSelector.class
    org/w3c/css/sac/PositionalCondition.class
    org/w3c/css/sac/InputSource.class
    org/w3c/css/sac/DocumentHandler.class
    org/w3c/css/sac/ErrorHandler.class
    org/w3c/css/sac/CSSParseException.class
    org/w3c/css/sac/Locator.class
    org/w3c/css/sac/CombinatorCondition.class
    org/w3c/css/sac/CSSException.class
    org/w3c/css/sac/SelectorFactory.class
    org/w3c/css/sac/Selector.class
    org/w3c/css/sac/AttributeCondition.class
    org/w3c/css/sac/ProcessingInstructionSelector.class
    org/w3c/css/sac/LexicalUnit.class
    org/w3c/css/sac/Parser.class
    org/w3c/css/sac/SimpleSelector.class
    org/w3c/css/sac/ContentCondition.class
```

The CI PR Builder doesn't run the needed profile for wildfly-swarm, so running it manually:

```
mvn -e -nsu -fae -B -T2 -Pkie-wb,sourcemaps clean install -Dfull=true -Dcontainer=wildfly-swarm  -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dmaven.test.redirectTestOutputToFile=true -Dgwt.compiler.localWorkers=1
```

**Comment by mareknovotny** [comment]
Beside the enforcer failures there are test failures too, need to find out what is the root issue there

**Comment by mareknovotny** [comment]
so with the help of @jakubschwan I was able to run wildfly-swarm profile and verified that at least the rest tests works fine with upgraded 2018.3.3.

**Pull request merged**
