### PR TITLE
KOGITO-5016: Remove Kogito-related modules from v7 stream

### PR DESCRIPTION
**Pull request by caponetto**
**Thank you for submitting this pull request**

**JIRA**: [KOGITO-5016](https://issues.redhat.com/browse/KOGITO-5016)

**referenced Pull Requests**:

- https://github.com/kiegroup/appformer/pull/1135
- https://github.com/kiegroup/kie-wb-common/pull/3632
- https://github.com/kiegroup/drools-wb/pull/1488
- https://github.com/kiegroup/jbpm-wb/pull/1490
- https://github.com/kiegroup/kie-wb-distributions/pull/1099

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
Thank you @caponetto , excellent worl.
Is this still required? https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L493

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
@yesamer Yes. It is being used by `kie-wb-common-dmn-webapp-kogito-marshaller`, which is the only module I couldn't remove.

**Comment by yesamer** [comment]
@caponetto Ok, keep in mind version `1.2.1` of that project is based on GWT 2.8.2. So dependencies related to that  GWT version will be downloaded and used. If possible, I would suggest updating it to `1.3.0` as we did in `kogito-java-editors`, in order to have a unique GWT version everywhere.

**Review by yesamer — APPROVED** [review]
Thank you @caponetto

**Comment by caponetto** [comment]
@yesamer I agree but I suggest treating this upgrade in another JIRA. 
In fact, we already have PRs for that. Please see https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1606.

**Comment by yesamer** [comment]
> @yesamer I agree but I suggest treating this upgrade in another JIRA.
> In fact, we already have PRs for that. Please see #1606.

**Comment by yesamer** [comment]
> @yesamer I agree but I suggest treating this upgrade in another JIRA.
> In fact, we already have PRs for that. Please see #1606.

Totally agree! (sorry I closed it by mistake )

**Comment by romartin** [comment]
Hey @caponetto @tiagobento 

First of all, thanks for this work!! It's really important to do this refactor ASAP, so appreciated! :+1: 

In general looks good, although on the BPMN side, there are a few modules that are still making no sense to be present in the 7.x stream, as they're only related to kogito, those can be also removed here. Those are:

- [bpmn-emf](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf) & [bpmn-marshalling](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling) ==> Those modules contain the "client side" BPMN marshallers stuff, and as this stream is targeting BC, the BPMN marshallers being used are only backend side

- [bpmn-kogito-runtime](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime) ==> It's the webapp used for kogito space. It's supposed that ti's no longer necessary as we'll generate it from the new [kogito-editors-java](https://github.com/kiegroup/kogito-editors-java) stream. Also this kogito webapp use the client side marshallers, so everything here is out from scope for the BC (7.x) stream

I don't want to put everything on you guys, that refactor is geat and we can consider doing it in another iteration if necessary. So if you don't have time or don't feel confient to remove above 3 modules for BPMN, please just create a ticket and we'll properly work on it, np at all!! 

Thanks again for the great job here!!

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Hi @romartin, thanks for letting me know about these modules.
I've removed `kie-wb-common-stunner-bpmn-emf` and `kie-wb-common-stunner-bpmn-marshalling`.
Please see: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1637/commits/da747e7eb1e0044443687ade063f2f8b945f6889 and https://github.com/kiegroup/kie-wb-common/pull/3632/commits/6d617969d142f8b8e4e727803be1ef2633f4f864.
`kie-wb-common-stunner-bpmn-kogito-runtime` was already removed.

**Comment by caponetto** [comment]
Jenkins seems unstable. I'll wait a bit before running the FDB.

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by romartin** [comment]
great, thanks @caponetto !  Everything looks ready to me, go! :+1:

**Review by romartin — APPROVED** [review]

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins retest this

**Review by tomasdavidorg — APPROVED** [review]

**Comment by yesamer** [comment]
Jenkins retest this

**Review by karreiro — APPROVED** [review]
Thank you, @caponetto.

**Comment by karreiro** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Despite ❌, [the last](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-master.pr/39/console) `Linux - Pull Request` has completed successfully.

**Comment by caponetto** [comment]
Despite ❌, [the last](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/fdb/job/droolsjbpm-build-bootstrap-master.fdb/13/) `Linux - Full Downstream Build` has completed successfully.

**Comment by caponetto** [comment]
We've got some conflicts due to the version bump. I'll rebase the branches shortly.

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Pull request merged**
