### PR TITLE
RHDM-44 Remove the drools-verifier from drools-bom

### PR DESCRIPTION
**Pull request by ryanzhang**
See https://issues.jboss.org/browse/RHDM-44

### CODE REVIEW

**Comment by ryanzhang** [comment]
@etirelli  Edson, Could you please review on this? I think we should remove that from drools-bom.

**Comment by etirelli** [comment]
@ryanzhang once tests pass, yes, we can merge this.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Interesting that uberfire repository is still in the PR builder log:

`Cloning repository git://github.com/AppFormer/uberfire.git`

We need to remove it

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
do we still want to remove drools-verifier from BOM in master?

I am a little confused by this PR and status of the JIRA https://issues.jboss.org/browse/RHDM-44.

@etirelli what we need to do here?  

Is removal from DROOLS-BOM enough? 

Why we still have the drools-verifier module in build and repository if we don'ŧ use it?

**Comment by Rikkola** [comment]
@mareknovotny We don't use it, but I suspect it has been used by university students and some other open source projects. Still I'm about to make a PR that removes this and replaces it with a new one. If those users miss it, I'll add it back.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
@mareknovotny So that drools-verifier is there for anyone who would like to use it, but we do not use it anywhere. I'm also removing it with my PRs here. https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800.

It can still be found from the git history and if some community users really need it I can add it back later.

**Comment by mareknovotny** [comment]
ok, I will close this PR then for the @Rikkola's PRs

**Pull request closed without merging**
