### PR TITLE
RHPAM-3094 & RHDM-1414 xerces to 2.12.0.SP03

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: 
* https://issues.redhat.com/browse/RHPAM-3094
* https://issues.redhat.com/browse/RHDM-1414

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
xercesImpl-2.12.0.SP03.jar is present on "Linux - Full Downstream Production Build"

**Review by almope — APPROVED** [review]

**Comment by mareknovotny** [comment]
i think we can't upgrade now this, SP03 is forked release of Xerces. We had some other discussions with @tarilabs about downgrading from SP02 to 2.12.0 version

**Comment by mareknovotny** [comment]
@Ginxo please dont do upgrade here, but in our build config to force the SP03 version there only.
There will be exclusion of XercesImpl completely by https://github.com/kiegroup/droolsjbpm-integration/pull/2324

**Comment by mareknovotny** [comment]
so thinking more about my last comment, maybe it would be best to merge it and if the PR kiegroup/droolsjbpm-integration#2324 removes the usage we can remove the depMgmt completely if safe

**Comment by tarilabs** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1536#issuecomment-734725144

well anyway WB projects are using this `xercesImpl` too, while "my" PR only focuses on `kie-camel` so yeah I would progress this on separate tracks

**Pull request merged**
