### PR TITLE
[7.59.x] AF-2880 : Support Elytron in Business Central 

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[AF-2880](https://issues.redhat.com/browse/AF-2880)

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1776
* https://github.com/kiegroup/kie-soup/pull/231
* https://github.com/kiegroup/appformer/pull/1199
* https://github.com/kiegroup/droolsjbpm-integration/pull/2611
* https://github.com/kiegroup/jbpm-wb/pull/1518
* https://github.com/kiegroup/kie-wb-distributions/pull/1132

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins execute fdb

**Comment by mareknovotny** [comment]
merging as decided on mtg, all failures identified in Karaf IT needs to be fixed or ignored in followup investigation and work for main branch PRs

**Pull request merged**
