### PR TITLE
[TEST] Upgrade Node, npm and Yarn, attempt #2

### PR DESCRIPTION
**Pull request by yurloc**

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build.

**Comment by Ginxo** [comment]
@yurloc please keep it open for https://issues.redhat.com/browse/BXMSPROD-778

**Pull request closed without merging**
