### PR TITLE
JBPM-7951 Update tomcat-dbcp to 9.0.13

### PR DESCRIPTION
**Pull request by rsynek**
Once ready, should be merged together with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1638
https://github.com/kiegroup/jbpm/pull/1375

### CODE REVIEW

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
i guess this enforcer failure is not due this change, but it originates in master branch:
`[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    javax.activation:javax.activation-api:jar:1.2.0:test
    javax.activation:activation:jar:1.1.1:compile
  Duplicate classes:
    javax/activation/DataContentHandlerFactory.class
    javax/activation/ObjectDataContentHandler.class
    javax/activation/DataContentHandler.class
    javax/activation/CommandObject.class
    javax/activation/SecuritySupport$2.class
    javax/activation/FileTypeMap.class
    javax/activation/CommandInfo.class
    javax/activation/MailcapCommandMap.class
    javax/activation/DataHandler$1.class
    javax/activation/UnsupportedDataTypeException.class
    javax/activation/URLDataSource.class
    javax/activation/SecuritySupport$4.class
    javax/activation/MimeTypeParameterList.class
    javax/activation/SecuritySupport$1.class
    javax/activation/DataSource.class
    javax/activation/DataHandlerDataSource.class
    javax/activation/CommandMap.class
    javax/activation/MimeTypeParseException.class
    javax/activation/DataHandler.class
    javax/activation/MimeType.class
    javax/activation/FileDataSource.class
    javax/activation/ActivationDataFlavor.class
    javax/activation/MimetypesFileTypeMap.class
    javax/activation/SecuritySupport$5.class
    javax/activation/SecuritySupport$3.class
    javax/activation/SecuritySupport.class
    javax/activation/DataSourceDataContentHandler.class
`

**Comment by rsynek** [comment]
@mareknovotny yes, it was caused by https://github.com/kiegroup/droolsjbpm-knowledge/pull/364 and should be fixed by now by https://github.com/kiegroup/droolsjbpm-knowledge/commit/0f93c0bc506070391520f3a48d42e2d0b0d8f8d5

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
@mareknovotny some are known unstable tests, some are not. But none of them seems be connected with this upgrade.

I wonder what's up with the build - e.g. the PlannerBenchmarkFactoryTest does not fail locally.

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by MarianMacik** [comment]
jenkins execute full downstream build

**Pull request merged**
