### PR TITLE
Add neovisionaries internationalization dependency management

### PR DESCRIPTION
**Pull request by cuijulian**
Jira: https://issues.jboss.org/browse/PLANNER-1695

Merge before https://github.com/kiegroup/optaweb-vehicle-routing/pull/239

### CODE REVIEW

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Could you please add a comment for the new dependency, that this dependency is primary used in optaweb-vehicle-rooting repository? Just for simple overview

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by yurloc** [comment]
FDB completed, 1 unrelated test failed => OK to merge.

Failed test: org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest

**Pull request merged**
