### PR TITLE
[RHPAM-4111]-Certify Spring Boot 2.4.x

### PR DESCRIPTION
**Pull request by yurloc**
### JIRA
https://issues.redhat.com/browse/RHPAM-4111

### Referenced pull requests
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1872
- https://github.com/kiegroup/droolsjbpm-integration/pull/2693
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/641
- https://github.com/kiegroup/optaweb-employee-rostering/pull/755

Closes #1860.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yurloc** [comment]
jenkins do fdb

**Comment by yurloc** [comment]
FDB progress:
- Started 4 hr 35 min ago
- Estimated remaining time: 6 hr 37 min.

**Comment by yurloc** [comment]
```
Argument(s) are different! Wanted:
taskAssigningPlanningKieServerExtension.createRuntimeClient(
    "http://testserver:8080/kie-server/services/rest/server",
    "RUNTIME_USER",
    "kieserver1!",
    1234L
);
-> at org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore(TaskAssigningPlanningKieServerExtensionTest.java:294)
Actual invocations have different arguments:
taskAssigningPlanningKieServerExtension.createRuntimeClient(
    "http://testserver:8080/kie-server/services/rest/server",
    "RUNTIME_USER",
    "RUNTIME_PWD",
    1234L
);
-> at org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtension.initRuntimeClient(TaskAssigningPlanningKieServerExtension.java:446)
taskAssigningPlanningKieServerExtension.createTaskAssigningService(
    org.kie.server.services.taskassigning.planning.TaskAssigningServiceConfig@4ed7fb78
);
-> at org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtension.init(TaskAssigningPlanningKieServerExtension.java:161)

	at org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore(TaskAssigningPlanningKieServerExtensionTest.java:294)
	at org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore(TaskAssigningPlanningKieServerExtensionTest.java:267)
```
This seems to be related to:
- https://github.com/kiegroup/drools/pull/4139 
- https://github.com/kiegroup/droolsjbpm-integration/pull/2690

so unrelated to the Spring Boot upgrade.

**Comment by yurloc** [comment]
Otherwise FDB looks good.

- `org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest` failure is unrelated,
- `org.kie.bc.DeploymentIT` I have no idea but it's out of scope of my expertise. I am not going to investigate that.

@VaniHaripriya @mareknovotny Please take over, my work is done.

You can merge this whole PR group if you're fine with the build results.

If more changes are need, you can clone the OptaWeb fixes from
- https://github.com/yurloc/optaweb-vehicle-routing/tree/RHPAM-4111,
- and https://github.com/yurloc/optaweb-employee-rostering/tree/RHPAM-4111,
and continue from the original PR (#1860).

**Comment by VaniHaripriya** [comment]
Thanks @yurloc , this looks good to me.

**Review by VaniHaripriya — APPROVED** [review]

**Pull request merged**
