### PR TITLE
DROOLS-764: remove dependency to commons-lang:commons-lang

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1016
https://github.com/kiegroup/kie-wb-common/pull/2788

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
build was unstable, three test failed
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/43/testReport/
+1 to merge

**Comment by mareknovotny** [comment]
so once more tryout
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
ok, now finally only `org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway` failed so I am merging it

**Pull request merged**
