### PR TITLE
remove log4j version declaration

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute cdb

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
we can merge it after https://github.com/kiegroup/kie-soup/pull/239 is merged too.

**Comment by jomarko** [comment]
I do not think we can merge this, we use this property for `log4j-to-slfj4` artifacts, see
- log4j-to-slf4j
- https://github.com/kiegroup/kogito-tooling/blob/d93fd654d43526b35ef8c98bd9cfa832c4dca3a3/packages/dashbuilder/appformer/pom.xml
- https://github.com/kiegroup/kogito-editors-java/blob/1ee5a4215e3801a1db4a7f8328abb7b34276b74d/pom.xml
- https://github.com/kiegroup/appformer/blob/b68d6678eed250982b833bc8103171d367275065/pom.xml

**Review by jomarko — CHANGES_REQUESTED** [review]
We use this property for `log4j-to-slf4j` artifacts.

**Comment by mareknovotny** [comment]
good catch @jomarko, i haven't noticed this

**Pull request closed without merging**
