### PR TITLE
BXMSPROD-1235: upgrade apache batik 1.14 and xml commons to 2.6

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/BXMSPROD-1235

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
failures are related to master branch status in jbpm and related integration tests

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
8 SB Kie server tests failed, these should not be related as there is one expected wrong result and a deployment error for the rest.

- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojo
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojo
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoMalformedData
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testSubprocessMessage
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignal
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsTransactional
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessage
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsAndMessagesTransactional
- org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundaryMessageMultipleProcesses

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
now failed 2 Selenium tests in DMNBackwardCompatibilityIT test class, but it is actually 1 test method failing causing the other error in the same method? not sure:
- org.kie.workbench.common.dmn.showcase.client.backward.compatibility.DMNBackwardCompatibilityIT.testDMN13Assets
- org.kie.workbench.common.dmn.showcase.client.backward.compatibility.DMNBackwardCompatibilityIT.testDMN13Assets

**Comment by mareknovotny** [comment]
@karreiro any idea why these tests above could fail?

**Comment by mareknovotny** [comment]
jenkins do fdb

trying for 3rd time FDB

**Comment by karreiro** [comment]
@mareknovotny the tests above fail when a DMN asset on DMN 1.3 spec cannot be converted to a DMN 1.2 spec. I believe it may be a false negative.

**Comment by mareknovotny** [comment]
ok, thanks @karreiro for confirmation

**Review by mbiarnes — APPROVED** [review]
LGTM

**Pull request merged**
