### PR TITLE
RHBPMS-5184: upgrades POI due OOM

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/RHBRMS-3118

### CODE REVIEW

**Comment by manstis** [comment]
@mareknovotny How does this POI version compare to {{master}}? IIRC @jomarko raised some JIRAs for XLS Decision Tables that could not compile due to OOM issues.. I wonder if this change would resolve those too. @jomarko WDYT? Do you recall?

**Comment by mareknovotny** [comment]
@ge0ffrey probably found this too? https://github.com/jboss-integration/jboss-integration-platform-bom/pull/413

**Comment by jomarko** [comment]
@manstis I reported https://issues.jboss.org/browse/RHPAM-520, checking behavior on master with https://github.com/jboss-integration/jboss-integration-platform-bom/pull/413 and on 6.5.x with this PR.

**Comment by mareknovotny** [comment]
Could this be merged?

**Comment by jomarko** [comment]
Just for record, I checked 6.5.x with and without this PR, it doesn't bring difference in behavior in the context of https://issues.jboss.org/browse/RHPAM-520.

**Pull request merged**
