### PR TITLE
BXMSPROD-685: upgrade of different dependency versions

### PR DESCRIPTION
**Pull request by mbiarnes**
upgrade of:
org.apache.ws.xmlschema
org.hibernate
org.hibernate.commons.annotations
org.jboss.classfilewriter
org.eclipse.yasson

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
  Found in:
    org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.1.Final:compile
    javax.xml.bind:jaxb-api:jar:2.3.1:test
Who can be the culprit here? I mean what upgrade is resp. for this?

**Comment by mareknovotny** [comment]
> @mareknovotny
> Found in:
> org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.1.Final:compile
> javax.xml.bind:jaxb-api:jar:2.3.1:test
> Who can be the culprit here? I mean what upgrade is resp. for this?

What is the question @mbiarnes  I don't follow this

**Comment by mbiarnes** [comment]
@mareknovotny I mean I upgraded several versions:
org.apache.ws.xmlschema
org.hibernate
org.hibernate.commons.annotations
org.jboss.classfilewriter
org.eclipse.yasson

What can be the "guilty" upgrade for this failure?

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

there were some CI infra network problems

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes the new push was not correct REBASE, it now includes already merged commits :(

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
`java.lang.OutOfMemoryError: GC overhead limit exceeded` in business-central-tests-gui module in kie-wb-distributions

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny Build was successful - in post actions the job failed
Only one test failed: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/droolsjbpm-build-bootstrap.downstream/78/testReport/

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
I took your changes from here to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1320 so I think we can close this PR

**Pull request closed without merging**
