### PR TITLE
Upgrade to jetty 9.4.20

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I89fd73f3a85f3bb72e19c7bd6660c01935c0e555

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 21 test failures https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/149/testReport/

**Comment by mareknovotny** [comment]
yes, this will not work as there are changed impl details in jetty upgraded version, I think i would close this PR

**Pull request closed without merging**
