### PR TITLE
BXMSPROD-313: removed com.squareup.okhttp3 since the upgraded version…

### PR DESCRIPTION
**Pull request by mbiarnes**
… is coming from jboss-ip-bom

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny same test failures as in #940

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Pull request merged**
