### PR TITLE
PLANNER-1606 Remove optaplanner-webexamples

### PR DESCRIPTION
**Pull request by triceo**

### CODE REVIEW

**Comment by triceo** [comment]
@mareknovotny Not sure who has the rights to merge in this repo. Could you please take care of it?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
full downstream build complains about errai, completely not related.

Jenkins execute full downstream build until it's green.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
