### PR TITLE
Upgrade h2database to 1.4.200

### PR DESCRIPTION
**Pull request by cuijulian**
This PR is a prerequisite for:

- https://github.com/kiegroup/jbpm/pull/1556
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/220

### CODE REVIEW

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@cuijulian maybe we should rebase before building again?

**Comment by mareknovotny** [comment]
@cuijulian  this needs to be rebased https://github.com/kiegroup/optaweb-vehicle-routing/pull/220

`PR 220 for repo GitHubRepository{owner='kiegroup', name='optaweb-vehicle-routing'} is not automatically mergeable`

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Is this PR still active or we can close it as abandoned?

**Comment by cuijulian** [comment]
> Is this PR still active or we can close it as abandoned?

It's indeed abandoned. Closing it now, thanks for catching it.

**Pull request closed without merging**
