### PR TITLE
Upgrade build chain to typescript version - second try

### PR DESCRIPTION
**Pull request by shubhbapna**
This reverts #2198 

To be merged after: 
* https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/259

### CODE REVIEW

**Comment by mareknovotny** [comment]
can we see the test on this PR? the current check here actually doesn't run the changed version.

**Comment by shubhbapna** [comment]
We need to test the jenkins change to verify although I am not sure how to do that

**Comment by shubhbapna** [comment]
@mareknovotny pls refer https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/259#issuecomment-1407823530

**Comment by lampajr** [comment]
@mareknovotny @shubhbapna Since we merged https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/263 I think we should merge this too, otherwise Jenkins pull requests job will fail.

I think we should also backport this to `7.67.x` and `7.67.x-blue` branches, wdyt?

**Review by lampajr — APPROVED** [review]

**Comment by shubhbapna** [comment]
+1 added the backport labels.

**Pull request merged**
