### PR TITLE
BXMSPROD-685: upgraded org.javassist

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
it seems that mockito doesn't like this javassist upgrade

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
failing only the timed out org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest

**Comment by mareknovotny** [comment]
reverted by 867bf9b2

**Pull request merged**
