### PR TITLE
Remove duplicated dependencies

### PR DESCRIPTION
**Pull request by jhrcek**
The (optional) climax of the duplicate dependencies cleanup - prevent it in the future by mandatory enforcer execution. Let's see if all the repos build.. 

Depends on 
https://github.com/kiegroup/kie-wb-common/pull/1302
https://github.com/kiegroup/droolsjbpm-integration/pull/1289
https://github.com/kiegroup/drools-wb/pull/718
https://github.com/kiegroup/kie-wb-distributions/pull/656

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
1 failure [OrganizationalUnitAccessIntegrationTest|http://janhrcek.cz/random-failures/#/class/org.kie.wb.test.rest.security.OrganizationalUnitAccessIntegrationTest/method/org.kie.wb.test.rest.security.OrganizationalUnitAccessIntegrationTest] - failed in the past with the same error and seems unrelated to this PR. Trying again.. 
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Also there seems to be a bug in jenkins which is showing that test method name is the same as test class name, which doesn't make sense: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-build-bootstrap-downstream-pullrequests/148/testReport/junit/org.kie.wb.test.rest.security/OrganizationalUnitAccessIntegrationTest/org_kie_wb_test_rest_security_OrganizationalUnitAccessIntegrationTest/

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Test failures can't be related to the changes in this PR (enabling enforcer rule)
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@manstis @psiroky now that the dependencies of this PR have been merged, let's decide if we want to prevent adding duplicated dependencies by automated enforcer check.

If we merge this the build will fail when someone adds dependency declaration that already exists (in the same) pom.xml. We can probably live without this check, since we're using managed dependencies anyway (versions are centralized), but I like the idea of preventing possible misconfigurations before merging. Opinions?

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Full downstream build failing
```
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/droolsjbpm-build-bootstrap-downstream-pullrequests/upstream-repos/uberfire). Please verify you invoked Maven from the correct directory.
```
@psiroky I suppose the CI configuration is still being refactored after uberfire rename/move?

**Comment by psiroky** [comment]
@jhrcek not exactly, although related. Please rebase this PR to fix the error above.

**Comment by jhrcek** [comment]
Rebased. Jenkins execute full downstream build

**Comment by psiroky** [comment]
@jhrcek not sure if I missed something, but the PR does not seem be reabased.

**Comment by jhrcek** [comment]
Right, closing this in favor of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/639

**Pull request closed without merging**
