### PR TITLE
Disable illegalTransitiveDependencyCheck

### PR DESCRIPTION
**Pull request by danielezonca**
Try to disable IllegalTransitiveDependencyCheck for now and see if FDC is green

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins execute compile downstream build

**Comment by danielezonca** [comment]
jenkins execute compile downstream build

**Comment by danielezonca** [comment]
@gitgabrio 
Thanks for the suggestion!
Done

**Comment by rsynek** [comment]
@danielezonca I can see the compile downstream build is failing due to missing dependencies. Is it another issue we have or does the JBoss public repo have a bad day? For example, the drools-wb-globals-editor-api is missing the JAR file for the latest snapshot: https://repository.jboss.org/nexus/content/groups/public/org/drools/drools-wb-globals-editor-api/7.24.0-SNAPSHOT/

**Comment by danielezonca** [comment]
jenkins execute compile downstream build

**Pull request merged**
