### PR TITLE
Synchronizations for Eclipse Formatter

### PR DESCRIPTION
**Pull request by hasys**
@manstis, @psiroky, @porcelli, @tarilabs, @sutaakar, @jhrcek, @markcoble,

Hi guys. There are big changes in Eclipse formatter. It is _almost_ synchronized with IDEA formatter now. At least formatting "ping-pong" will be reduced to minimum.

Also there are addition setting (**format changed code only**) for Eclipse (have to be set up manually) to help minimize format changes in PRs.

Some known problem areas for now are:
- Long Class declaration (Eclipse and IDEA have different alignments styles for long class declarations like `public class SomeMegaLongClass extends FirstOne, SecondOne, ThirdOne implements ALotOfDifferentInterfaces`, at least I didn't success to synchronize it.
- Long method invocation chain  like `clazz.method1().longMethodName2().anotherOne().andOneMore().andSoOn()`(the same situation - IDEA and Eclipse have different tabulation styles here as well.
- Inner classes - Eclipse will reformat it with same style as normal classes, IDEA preserve user formatting

But again it can create some difference only in case of Eclipse user will write/modify according lines.

Also I removed excludes from star notation, because Eclipse is not support excludes and add space between `java` and `javax` packages due to the same reason. It's mean we have to disable import order in style check plugin, or reformat existing repositories + update IDEA formaters.

If it is OK to you, in my opinion this PR is good enough for repository with IDEA users and time to time PRs from Eclipse users.

If it will be merged any Eclipse user can write his/her code with this formatter and forgot about formatting wars.

### CODE REVIEW

**Comment by tarilabs** [comment]
Thank you for this.

I have a question, please?

Disclaimer: this or any update which will get merged in the autoformatter I will apply inside my IDE, just let me know when ready and I will do so. I prefer to mention this disclaimer beforehand, to avoid risk of being pointed in triggering a formatting war which is not my intention =)

With this premised, I'd like to know if this means Eclipse will now autoformat multiple parameters in method call from like this:
```
new MyClass(f, x, null, null, 3, null, a);
```
to like this:
```
new MyClass(f,
            x,
            null,
            null,
            3,
            null,
            a);
```
which is a style that benefits mainly IntelliJ users, but my main concern is that it was one of the main source of difference (at least in my experience) where I've interacted on a repo with users coming from different IDE, please?
Or is the viceversa being applied?
Because this formatting difference I can really understand is troubling reviewing code when using the git diff, if compared for instance to other format styling differences.

/cc @mswiderski which I believe mentioned to me recently he's using Eclipse.

**Comment by mswiderski** [comment]
@tarilabs correct, I do use eclipse and frankly speaking moving completely away from intellij so this does concerns me :) Anyway, I don't have much preferences for this code formatters as long as they are aligned.
With that said, please mention me when this is merged so I apply this locally and I'd most likely go for complete repo reformat to avoid later on issues with PRs.

**Comment by manstis** [comment]
This is really for the Eclipse Users to comment on.

But in reply to @tarilabs comment; the multi-line split is nothing to do with IDEA but was proposed to simplify debugging function calls when parameters are function calls themselves. I just checked with an Eclipse project and using split-lines I could (IMO) step into nested function calls more easily than when they're on the same line. Mark is a keen advocate of the multi-line split (and I have grown to prefer it). 

That said I agree with @mswiderski completely.. Make them consistent; make everyone use them (like them or not - and TBH I had a personal preferences over what I now use to be _complaint_). More effort has been spent and continues to be spent discussing code formatting than perhaps more fundamental matters.

**Comment by tarilabs** [comment]
@manstis 

> This is really for the Eclipse Users to comment on. But in reply to tarilabs [...] the multi-line split is nothing to do with IDEA but [...] step into nested function calls more easily than when they're on the same line. 

Thank you for the feedback.

I have no comments. 

I would like to refocus this thread to my original intention, that is to know whether the formatter would be idempotent with regards to this multi-line split, please?
As in my experience during strict enforcement request, this case was one of the main differences which manifested in the diff, if compared to others.
Thanks.

**Comment by hasys** [comment]
Hi @tarilabs, thank you for review. Can I ask you to test this formatter in case you have any open/in progress PR to kie-wb-common repository or similar with styles integration?

@manstis, as I mentioned before they are not 100% identical. For now I found only 2 ways how to make it 100% identical: 
- add maven plugin to perform formatting in compile time (@markcoble can provide more info)
- Use  use Eclipse Code Formatter plugin in IntelliJ IDEA (in this case plugin will perform formatting with same engine as Eclipse does).

The only question do we really want to do formatters 100% identical.

**Comment by tarilabs** [comment]
Hi @hasys I tried to comply as requested, I don't have an open PR where to try this, but I tried on a project on drools which I'm currently working on with @mariofusco .

Given the following "unformatted" source method which is code generated from the project I mentioned:
```
private org.drools.model.Rule rule_beta() {
    final org.drools.model.Variable<org.drools.modelcompiler.Person> var_$p1 = variableOf(type(org.drools.modelcompiler.Person.class));
    final org.drools.model.Variable<org.drools.modelcompiler.Person> var_$p2 = variableOf(type(org.drools.modelcompiler.Person.class));
    org.drools.model.Rule rule = rule("beta").view(expr(var_$p1, (_this) -> _this.getName().equals("Mark")).indexedBy(java.lang.String.class, org.drools.model.Index.ConstraintType.EQUAL, _this -> _this.getName(), "Mark").reactOn("name", "age"), expr(var_$p2, (_this) -> !_this.getName().equals("Mark")).indexedBy(java.lang.String.class, org.drools.model.Index.ConstraintType.NOT_EQUAL, _this -> _this.getName(), "Mark").reactOn("name"), expr(var_$p2, var_$p1, (_this, $p1) -> _this.getAge() > $p1.getAge()).indexedBy(int.class, org.drools.model.Index.ConstraintType.GREATER_THAN, _this -> _this.getAge(), $p1 -> $p1.getAge()).reactOn("age")).then(c -> c.on(var_$p1, var_$p2).execute(($p1, $p2) -> {
        System.out.println($p2.getName() + " is older than " + $p1.getName());
    }));
    return rule;
}
```

With the previous Eclipse formatter, I didn't notice specific difference, I believe it would have left it unchanged (or just removing spaces between the `(` and the first parameter, but I removed them from the original source code generation directly already).

Using the Eclipse formatter you are proposing with this PR gets it to:
```
private org.drools.model.Rule rule_beta() {
    final org.drools.model.Variable<org.drools.model.Person> var_$p1 = variableOf(type(org.drools.model.Person.class));
    final org.drools.model.Variable<org.drools.model.Person> var_$p2 = variableOf(type(org.drools.model.Person.class));
    org.drools.model.Rule rule = rule("beta").view(expr(var_$p1,
                                                        (_this) -> _this.getName().equals("Mark")).indexedBy(java.lang.String.class,
                                                                                                             org.drools.model.Index.ConstraintType.EQUAL,
                                                                                                             _this -> _this.getName(),
                                                                                                             "Mark").reactOn("name",
                                                                                                                             "age"),
                                                   expr(var_$p2,
                                                        (_this) -> !_this.getName().equals("Mark")).indexedBy(java.lang.String.class,
                                                                                                              org.drools.model.Index.ConstraintType.NOT_EQUAL,
                                                                                                              _this -> _this.getName(),
                                                                                                              "Mark").reactOn("name"),
                                                   expr(var_$p2,
                                                        var_$p1,
                                                        (_this, $p1) -> _this.getAge() > $p1.getAge()).indexedBy(int.class,
                                                                                                                 org.drools.model.Index.ConstraintType.GREATER_THAN,
                                                                                                                 _this -> _this.getAge(),
                                                                                                                 $p1 -> $p1.getAge()).reactOn("age")).then(c -> c.on(var_$p1,
                                                                                                                                                                     var_$p2).execute(($p1, $p2) -> {
                                                                                                                                                                         System.out.println($p2.getName() +
                                                                                                                                                                                            " is older than " + $p1
                                                                                                                                                                                                                   .getName());
                                                                                                                                                                     }));
    return rule;
}
```

while as far as I know the IntelliJ IDEA (current) formatter gives:
```
    private org.drools.model.Rule rule_beta() {
        final org.drools.model.Variable<org.drools.model.Person> var_$p1 = variableOf(type(org.drools.model.Person.class));
        final org.drools.model.Variable<org.drools.model.Person> var_$p2 = variableOf(type(org.drools.model.Person.class));
        org.drools.model.Rule rule = rule("beta")
                .view(
                        expr(var_$p1, (_this) -> _this.getName().equals("Mark"))
                                .indexedBy(java.lang.String.class, org.drools.model.Index.ConstraintType.EQUAL, _this -> _this.getName(), "Mark")
                                .reactOn("name", "age"),
                        expr(var_$p2, (_this) -> !_this.getName().equals("Mark"))
                                .indexedBy(java.lang.String.class, org.drools.model.Index.ConstraintType.NOT_EQUAL, _this -> _this.getName(), "Mark")
                                .reactOn("name"),
                        expr(var_$p2, var_$p1, (_this, $p1) -> _this.getAge() > $p1.getAge())
                                .indexedBy(int.class, org.drools.model.Index.ConstraintType.GREATER_THAN, _this -> _this.getAge(), $p1 -> $p1.getAge())
                                .reactOn("age"))
                .then(c -> c.on(var_$p1, var_$p2)
                            .execute(($p1, $p2) -> { System.out.println($p2.getName() + " is older than " + $p1.getName()); })
        );
        return rule;
    }
```

It would look like the Eclipse formatter you are proposing is not recognizing the indentation level should  "rollback", if you notice the code goes in a "straight diagonal line" from topleft to bottomright in indentation.
Is this something you could take a quick check at, please?
Do you think this problem is addressable?

In this case, if the Eclipse formatter has to break lines, I would prefer it is also able to rollback indentation levels similar to IntelliJ IDEA version.

Just to add a couple of additional points.

- Personally, I reiterate I don't believe it is necessary to have them 100% aligned, because personally I don't believe we should enforce _strictly_ the application of the code style. While I appreciate having this code style because it does some helpful formatting for me, which I use, I don't believe is good applying it "blindly" on incoming PR. I know here we share different perspective on this point, I just wanted to mention mine. As mentioned above, and actually as I just did, this formatter is already imported in my IDE =)

- I tried your setting for "on save formatting" in Eclipse, works as expected - thanks I never noticed that option!

- Still on the "on save formatting" in Eclipse topic, indeed helpful only for "changed line only", as I tried `CTRL+SHIFT+F` on code written by @mariofusco which uses IntelliJ it would cause the ~"weird" behavior mentioned above. I believe this is crucial if the difference is so great.

- Can you point to me to the source code of either the maven plugin or the IntelliJ IDEA plugin which apply the code formatter from Eclipse engine, please? I'm asking as I would like to embed the formatter directly in the code generation I mentioned above. So the java code output from the project I'm working on with @mariofusco hopefully to emit java source code which is already compliant with the kiegroup formatter. Thanks!

**Comment by manstis** [comment]
@tarilabs FYI when I format the same code you asked Mario to format in IDEA I get this:
```
    private org.drools.model.Rule rule_beta() {
        final org.drools.model.Variable<org.drools.model.Person> var_$p1 = variableOf(type(org.drools.model.Person.class));
        final org.drools.model.Variable<org.drools.model.Person> var_$p2 = variableOf(type(org.drools.model.Person.class));
        org.drools.model.Rule rule = rule("beta").view(expr(var_$p1,
                                                            (_this) -> _this.getName().equals("Mark")).indexedBy(java.lang.String.class,
                                                                                                                 org.drools.model.Index.ConstraintType.EQUAL,
                                                                                                                 _this -> _this.getName(),
                                                                                                                 "Mark").reactOn("name",
                                                                                                                                 "age"),
                                                       expr(var_$p2,
                                                            (_this) -> !_this.getName().equals("Mark")).indexedBy(java.lang.String.class,
                                                                                                                  org.drools.model.Index.ConstraintType.NOT_EQUAL,
                                                                                                                  _this -> _this.getName(),
                                                                                                                  "Mark").reactOn("name"),
                                                       expr(var_$p2,
                                                            var_$p1,
                                                            (_this, $p1) -> _this.getAge() > $p1.getAge()).indexedBy(int.class,
                                                                                                                     org.drools.model.Index.ConstraintType.GREATER_THAN,
                                                                                                                     _this -> _this.getAge(),
                                                                                                                     $p1 -> $p1.getAge()).reactOn("age")).then(c -> c.on(var_$p1,
                                                                                                                                                                         var_$p2).execute(($p1, $p2) -> {
            System.out.println($p2.getName() + " is older than " + $p1.getName());
        }));
        return rule;
    }
```
This, I believe, is consistent with the ```droolsjbpm-build-bootstrap``` IDEA code formatting conventions.

Perhaps you've just highlighted that Mario uses something different?

**Comment by tarilabs** [comment]
@manstis I'm officially jealous now your formatter doesn't go crazy on the code block with the sysout line =)

**Comment by hasys** [comment]
Hi @manstis, @tarilabs sorry for the delay, I had PTO.
@tarilabs 

> @manstis I'm officially jealous now your formatter doesn't go crazy on the code block with the sysout line =)

It it because line size limits. Eclipse force to not overflow line width. I extended it to 220 symbols, so every line over 220 symbols will `go crazy`. I can extend it even more, if you like.

@manstis what do you think what is remain to merge this PR?

**Comment by manstis** [comment]
@hasys IDK that's up to the Eclipse people to say I guess.

Also I believe @mdproctor wants to change the formatter anyway :-(

**Comment by mswiderski** [comment]
+1 from my end as the sooner we have it aligned the better even if there will some adjustments later on

**Comment by tarilabs** [comment]
> Also I believe @mdproctor wants to change the formatter anyway :-(

I think it's actually more a request about not imposing strictly a very specific settings.
And personally I believe is a very valid point as well.

**Comment by mswiderski** [comment]
any conclusions here? can we get this merged?

**Comment by hasys** [comment]
Hi @mswiderski, 

sorry I was OOO, on  training. I will update code styles with latest Mark's wishes and prepare PR with changes for other repositories (space between java and javax imports) soon. And after that we will be ready to merge and use it.

**Comment by mswiderski** [comment]
@hasys how is this going? any chance to get this merged?

**Comment by ge0ffrey** [comment]
@hasys Does this take into account the recent changes of #547 ?

+1 for anything that brings the eclipse formatter more inline with the intellij one.

**Comment by hasys** [comment]
Hi @ge0ffrey, @mswiderski, @tarilabs
I updated this PR according to new rules in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/547
For now it's done, but we need two more actions:

1. It will be appreciated by me if someone (or several) of Eclipse user will test this formatter, because Eclipse doesn't work it for me well and addition tests will be really useful
2. If Eclipse formatter is OK - Update all repositories with enabled _**check-style**_ plugin for align Import statements (Eclipse doesn't support grouping **java** and **javax** packages, so we have to add new line everywhere between java.* and javax.* packages. Or just disable **import order check**.

**Comment by tarilabs** [comment]
I have updated my IDE locally with the codestyle, as requested.
I will need some time to monitor the behavior but I will feedback. Thanks

**Comment by hasys** [comment]
@tarilabs, thank you! Just a reminder please, don't forget to use *Format edited lines*, *Organize imports* [described here](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/502/files#diff-04c6e90faac2675aa89e2176d2eec7d8R753), as well as other Eclipse settings from [droolsjbpm-build-bootstrap/README.md](https://github.com/hasys/droolsjbpm-build-bootstrap/blob/8d8740189b959123be7fb5bffe2500a4e6649b6b/README.md)

**Comment by tarilabs** [comment]
I'm not sure what I'm doing wrong.
But I updated the codestyle as above as per latest commit, and indeed I have the options of the save action setup as mandated.
Still, if I write:

```
        AtomicLong.class.getPackage().getName().replaceAll(".", "/");
```

it forces to align the parameters resulting in:

```
        AtomicLong.class.getPackage().getName().replaceAll(".",
                                                           "/");
```

is it only me?

**Comment by hasys** [comment]
Hi @tarilabs, my bad, sorry. I made some mistake during formatter export. Have to be fixed now. Thank you!

**Comment by ge0ffrey** [comment]
I am merging this as this is a step forwards. Even if additional improvements are found out along the way - and those should be PR'ed too - this new situation has no regression over the old situation.

**Comment by ge0ffrey** [comment]
> If Eclipse formatter is OK - Update all repositories with enabled check-style plugin for align Import statements (Eclipse doesn't support grouping java and javax packages, so we have to add new line everywhere between java.* and javax.* packages. Or just disable import order check.

Wasn't there a checkstyle PR somewhere that removed that import order check? Was anyone opposing that or was it just that no one was keen on taking responsibility to merge that?

I agree that the checkstyle rules need to be in sync with the eclipse ones, so this needs to be solved, somehow. As for how we fix it: Personally I don't care much about the import section of java files (unlike the rest of the file), so I am ok with both proposals... Please open a separate PR for that.

**Comment by ge0ffrey** [comment]
@hasys thanks, nice work :)

**Pull request merged**
