### PR TITLE
AF-2442: Review Lienzo dependency in Dashbuilder

### PR DESCRIPTION
**Pull request by jesuino**
Review Lienzo dependency in Dashbuilder
--
Merge with:
https://github.com/kiegroup/appformer/pull/916

### CODE REVIEW

**Comment by jesuino** [comment]
@mareknovotny Thanks! Fixed in my last commit, would you please review again?

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
jenkins retest this

**Comment by jesuino** [comment]
The failing tests seems to be unrelated, but I will fire FDB again

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
I think we can merge as the 2 failed tests are random failures I can recognize

**Pull request merged**
