### PR TITLE
Clean pom

### PR DESCRIPTION
**Pull request by mbiarnes**
missing dependencies that were in uberfire-parent and are migrated to kie-parent

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1037
https://github.com/kiegroup/appformer/pull/777

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
@sutaakar any idea why `org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable` should be failing? see http://janhrcek.cz/random-failures/#/class/org.kie.server.client.LoadBalancerClientTest/method/testDefaultLoadBalancerNoServersAvailable there is only once failed in May.

**Comment by sutaakar** [comment]
@mareknovotny I have no idea. Is it reproducible?

**Comment by mareknovotny** [comment]
@sutaakar I haven't tried locally, but the linked PR for Appformer was run with FDB too and it doesn'ŧ show this failure so random it seems

**Comment by sutaakar** [comment]
It seems that it may be caused by very rare race condition.

**Comment by sutaakar** [comment]
@mareknovotny  I would consider it as a random failure.

**Pull request merged**
