### PR TITLE
[DROOLS-6794] upgrade netty version to 4.1.73

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6794

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
@mareknovotny trying to upgrade to 4.1.73

**Review by mareknovotny — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
The failure in `org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore `is unrelated with this change.

**Pull request merged**
