### PR TITLE
BXMSPROD-685: upgrade of org.jboss-weld

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes the new push was not correct REBASE, it now includes already merged commits :(

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
failure in test reported as https://issues.redhat.com/browse/DROOLS-5321

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny Build was successful - in post actions the job failed
Only one test failed: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/droolsjbpm-build-bootstrap.downstream/79/testReport/

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes the upgrade of weld were reverted, please look at it again

**Pull request merged**
