### PR TITLE
RHPAM-2943: keycloak upgrade to 9.0.3

### PR DESCRIPTION
**Pull request by mareknovotny**
this PR and followup on fixing Enforcer ban-duplicated-classes:

- https://github.com/kiegroup/appformer/pull/979
- https://github.com/kiegroup/jbpm-wb/pull/1438
- https://github.com/kiegroup/kie-wb-distributions/pull/1035

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
# 174 cancelled since it's not taking a free machine

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
so now it seems faillures unrelated to change

**Pull request merged**
