### PR TITLE
Bump version.org.keycloak from 4.8.3.Final to 9.0.3

### PR DESCRIPTION
**Pull request by mareknovotny**
This is just rebased branch on below change by @dependentbot

Bumps `version.org.keycloak` from 4.8.3.Final to 9.0.3.

Updates `keycloak-core` from 4.8.3.Final to 9.0.3
- [Release notes](https://github.com/keycloak/keycloak/releases)
- [Commits](https://github.com/keycloak/keycloak/compare/4.8.3.Final...9.0.3)

Updates `keycloak-common` from 4.8.3.Final to 9.0.3
- [Release notes](https://github.com/keycloak/keycloak/releases)
- [Commits](https://github.com/keycloak/keycloak/compare/4.8.3.Final...9.0.3)

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@mareknovotny we should probably add QE (@tomasdavidorg @jakubschwan) to check if everything keeps working on OCP. Looks a simple fix, but it goes from 4.x to 9.x

**Comment by tomasdavidorg** [comment]
@jesuino I can't remember but why was the previous PR for keycloak update reverted?

**Comment by mareknovotny** [comment]
@jesuino @tomasdavidorg https://issues.redhat.com/browse/AF-2224 I think there were some problems due RHSSO product was not public with that major version I guess

**Comment by mareknovotny** [comment]
Thanks @tomasdavidorg so we can merge it as FDB shows only timed test from drools-hacep

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
