### PR TITLE
KOGITO-4343: bump gwt-jsonix-schema-compiler version

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.redhat.com/browse/KOGITO-4343

Related PRs:
https://github.com/kiegroup/gwt-jsonix-schema-compiler/pull/11
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1606
https://github.com/kiegroup/kie-wb-common/pull/3570
https://github.com/kiegroup/kie-wb-common/pull/3562
https://github.com/kiegroup/kie-wb-common/pull/3582

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by yesamer — APPROVED** [review]
@treblereel Changes in this PR are fine, approved. Thank you.
Please consider FDB is failing on `drools-wb` compilation.
Probably this because the build is considering master version and not your PR branch https://github.com/kiegroup/drools-wb/pull/1466. 
To fix that, you need to use the same branch names for all your PRs. 
Eg. For this PR you used `treblereel:KOGITO-4343`, while for the one in `drools-wb` you used `treblereel:KOGITO-4343_main`. 
You need to have the same branch name to link them all during a build.

**Review by karreiro — APPROVED** [review]
Thank you, @treblereel :-)

**Comment by mareknovotny** [comment]
could you clean dependent PRs mentioned in description? I can see some were already closed, so it this PR is valid it should point to only valid PRs

**Comment by winklerm** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
what are we doing with this old PR? @treblereel @tiagobento

**Comment by treblereel** [comment]
@mareknovotny let's close it as outdated

**Pull request closed without merging**
