### PR TITLE
[ 7.67.x-blue] update infinispan to 14.0.18

### PR DESCRIPTION
**Pull request by cimbalek**

### CODE REVIEW

**Comment by cimbalek** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins do fdb

**Comment by baldimir** [comment]
There are compilation failures in uberfire repository in the downstream build. I guess this needs more alignment in the uberfire repository. Also there is a newer redhat version 14.0.27.Final-redhat-00002, so we may try to get that version instead of 14.0.18. What do you think please?

**Comment by baldimir** [comment]
I was able to fix the failures. Please @cimbalek ping me on chat and we can discuss that.

**Comment by baldimir** [comment]
I submitted another PR, please see https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2485

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by baldimir** [comment]
Closing as replaced by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2485

**Pull request closed without merging**
