### PR TITLE
BXMSPROD-685: upgrade of org.jboss.remoting

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny
BUILD was unstable, one test failed https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/1821/testReport/
+1 to merge

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny failed always the same test:
 org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest
because of error message. test timed out after 20000 milliseconds
#1220 
#1221
#1232
+1 to merge all three

**Pull request merged**
