### PR TITLE
[7.48.x] [RHDM-1574] Consume Mvel version to 2.4.12+

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 

https://issues.redhat.com/browse/RHDM-1574

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
This FDB error doesn't seem to be related to this PR.
~~~
org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable

Failing for the past 1 build (Since Unstable#1 )
Took 0.51 sec.
Error Message
No servers available even though one was started as load balancer was not refreshed
Stacktrace
java.lang.AssertionError: No servers available even though one was started as load balancer was not refreshed
	at org.junit.Assert.fail(Assert.java:89)
	at org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable(LoadBalancerClientTest.java:261)
	...
~~~

**Comment by mareknovotny** [comment]
jenkins do fdb

trying to confirm that failure is random

**Comment by tkobayas** [comment]
FDB error is different from the previous one and doesn't seem to be related to this PR. Will run fdb one more time, just in case.
```
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testDeleteSpace[user: NO_REST]

Failing for the past 1 build (Since Unstable#2 )
Took 1 sec.
Error Message
SERVER_ERROR: Request failed because of NoSuchFileException: null
Stacktrace
org.kie.wb.test.rest.client.ClientRequestTimedOutException: SERVER_ERROR: Request failed because of NoSuchFileException: null
	at org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testDeleteSpace(SpaceAccessIntegrationTest.java:45)
Standard Output
 >>> testDeleteSpace[user: NO_REST] <<< 
```

**Comment by tkobayas** [comment]
Jenkins run fdb

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
