### PR TITLE
Raise Cargo version to 1.6.11

### PR DESCRIPTION
**Pull request by sutaakar**
Contains container id for WildFly14

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
12 failures in kie-server integration tests (don't seem to be related to this change, but running full build anyway) 
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
12 failures in kie-server integration tests (don't seem to be related to this change, but running full build anyway) 
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
```
12:13:06 Caused by: java.io.IOException: Backing channel 'kie-ci-rhos-rhel7-xlarge-xmem-13967' is disconnected.
12:13:06 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:212)
12:13:06 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
12:13:06 	at com.sun.proxy.$Proxy73.isAlive(Unknown Source)
12:13:06 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
12:13:06 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
12:13:06 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:63)
12:13:06 	... 10 more
12:13:06 Caused by: java.io.IOException: Unexpected termination of the channel
12:13:06 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
12:13:06 Caused by: java.io.EOFException
```

Jenkins execute full downstream build

**Comment by jhrcek** [comment]
The usual assortment of 7 kie-server errors. I'd consider this ready to merge.

**Comment by jhrcek** [comment]
@adrielparedes FYI the cargo plugin has been updated everywhere (2 independent places in our repos that declare cargo version). After rebasing onto master your wildfly14 changes should hopefully work

**Pull request merged**
