### PR TITLE
Upgrade of mysql client to 8.0.27

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/RHPAM-4031

Upgrade of mysql connector to 8.0.27

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
Failures:


- [org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest.testAsyncKafkaWIH[0: SINGLETON]](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/testReport/org.jbpm.workitem.springboot.samples/KafkaProxyAsyncSampleTest/testAsyncKafkaWIH_0__SINGLETON_/)	30 sec	[1](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/)
 - [org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/testReport/org.kie.workbench.common.services.refactoring.backend.server.indexing/PackageDescrIndexVisitorLogicTest/visitLogicTest/)	64 ms	[1](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/)
 - [org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/testReport/org.kie.server.services.taskassigning.planning/TaskAssigningPlanningKieServerExtensionTest/initRuntimeClientWithKeyStore/)

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by gmunozfe** [comment]
Failures seem unrelated, let's try again
jenkins do fdb

**Review by elguardian — APPROVED** [review]

**Comment by mareknovotny** [comment]
ok, 1 failure down, the [org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/droolsjbpm-build-bootstrap-main.fdb/249/testReport/org.kie.workbench.common.services.refactoring.backend.server.indexing/PackageDescrIndexVisitorLogicTest/visitLogicTest/) is known on main

so the remaining test is not related as mentioned above and I will merge it

**Pull request merged**
