### PR TITLE
Removing git-gwtbootstrap from the kie-parent-pom

### PR DESCRIPTION
**Pull request by RishiRajAnand**
- Removing git-gwtbootstrap from dependancies since we already are using gwtbootstrap3 (https://github.com/gwtbootstrap3/gwtbootstrap3).

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
It seems gwt-bootstrap is a leftover dependency. The plan is to remove this, run a full downstream build, if that succeeds that would imply that it is not used by any of the module and we can decide to remove it then.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by RishiRajAnand** [comment]
jenkins execute full downstream build

**Comment by RishiRajAnand** [comment]
test case failure unrelated

**Comment by RishiRajAnand** [comment]
jenkins execute full downstream build

**Pull request merged**
