### PR TITLE
[7.67.x-blue] [BXMSPROD-1845] elasticsearch removed from appformer

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1845

Related PRs:

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2102
* https://github.com/kiegroup/appformer/pull/1317
* https://github.com/kiegroup/kie-wb-common/pull/3782
* https://github.com/kiegroup/drools-wb/pull/1560
* https://github.com/kiegroup/jbpm-wb/pull/1574
* https://github.com/kiegroup/kie-wb-distributions/pull/1198
* https://github.com/kiegroup/optaplanner-wb/pull/415

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by rgdoliveira** [comment]
@mareknovotny @lampajr just the PR for main (https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2097) that was merged. Are we going to merge this for 7.13.2?

**Comment by mareknovotny** [comment]
this is not completely up to date with what is on main and 7.67.x branches :(, wait until it is cleared out on main ;)

**Comment by mareknovotny** [comment]
Closed in favor of these PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2169
* https://github.com/kiegroup/kie-soup/pull/261
* https://github.com/kiegroup/appformer/pull/1369
* https://github.com/kiegroup/kie-wb-common/pull/3794
* https://github.com/kiegroup/drools-wb/pull/1563
* https://github.com/kiegroup/jbpm-wb/pull/1580
* https://github.com/kiegroup/kie-wb-distributions/pull/1210

**Pull request closed without merging**
