### PR TITLE
Revert "[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#1565)"

### PR DESCRIPTION
**Pull request by yurloc**
This reverts commit 9a1b93bca65de8a90841d29eed21f355ffaf23b3.

#1565 was merged without green FDB and causes several issues. I'm opening a reverting PR to see whether all of the issues seen after #1565 was merged will go away. If yes, I suggest to merge this to reach a safe restore point. Then the Spring Boot upgrade should be done again. All issues discovered by FDB must be resolved before the Spring Boot upgrade PR is merged.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins run fdb.

**Comment by mareknovotny** [comment]
I agree that the issue needs to be solved, now we saw only problems in optaweb's repositories. And the FDB failed due not able download cypress docker image AFAIK.
Now could you fix optaweb's test issues? @yurloc

**Comment by mareknovotny** [comment]
please link here also related merged PRs like https://github.com/kiegroup/jbpm-work-items/pull/171 and https://github.com/kiegroup/droolsjbpm-integration/pull/2370

**Comment by mbiarnes** [comment]
Did the same #1579 but added two commits on droolsjbpm-integration and jbpm-work-items. For having all PR on the branch with the same name. I will close this.

**Comment by yurloc** [comment]
Sorry, I wasn't aware this should be a cross-repo PR because #1565 didn't list the dependent PRs.

**Pull request closed without merging**
