### PR TITLE
security vulnerability:update of commons-compress

### PR DESCRIPTION
**Pull request by mbiarnes**
GitHub: potential security vulnerabilities in dependencies

### CODE REVIEW

**Comment by mbiarnes** [comment]
found commons-compress in these reps :
droolsjbpm-integration
jbpm-work-items

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny please look at https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/150/testReport/
(failed tests)

**Comment by mareknovotny** [comment]
yes, @mbiarnes. These all failed tests I recognized as not related and happened on the other PRs too :(
fyi @MarianMacik

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

retrigerring FDB as 3 tests were fixed in kiegroup/droolsjbpm-integration/pull/1938

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
