### PR TITLE
[DROOLS-6369] Fix kie-karaf-itests failures because of guava upgrade

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6369

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-integration/pull/2495

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
one side comment if you can add a comment to that version property why it is there without dependency declaration. Thanks in advance @tkobayas

**Review by jiripetrlik — APPROVED** [review]

**Comment by tkobayas** [comment]
@mareknovotny  Thanks for merging.
> one side comment if you can add a comment to that version property why it is there without dependency declaration.
I can add a comment... Shall I do it at the next opportunity? (sorry for the late reply)
for example)
~~~
<!-- failureaccess is required for karaf features.xml to expose com.google.common.util.concurrent.internal package -->
~~~

**Comment by mareknovotny** [comment]
you can send additional change without waiting for green CI i believe if you want to not forget

**Comment by tkobayas** [comment]
Okay, filed https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1654

**Pull request merged**
