### PR TITLE
security vulnerability:update of pdfbox

### PR DESCRIPTION
**Pull request by mbiarnes**
GitHub: potential security vulnerabilities in dependencies

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
only one test https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/31/testReport/junit/org.kie.wb.selenium.ui/ProjectLibraryIntegrationTest/importAndBuildProjectFromStockRepository/ failed
I would merge this

**Pull request merged**
