### PR TITLE
[RHPAM-3489][RHDM-1623][7.52.x] duplicated version.org.apache.xmlgraphics.commons error fixed

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/RHPAM-3489

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1643

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
it seems webhooks again doesn'ŧ work to trigger Jenkins CI

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
another one with 'java.lang.NoSuchMethodError: No such DSL method 'findbugs' found among steps' :o

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
@mbiarnes @mareknovotny I think https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/94f33647e12c561e8ddbfd64f79a3db6482d40b5#diff-1a498e068a28a1be3f7366558fdafcd711aedf6a0569022f751b1cee58ca40ed needs to be backported to 7.52.x, do you agree?

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
FDB took more than 12 hours... previous executions took less than 10 hours. Should we increase timeout for it? :thinking: @mbiarnes @mareknovotny @winklerm

**Comment by mareknovotny** [comment]
i noticed that on other FDB from droolsjbpm-build-bootstrap repository PRs too :(

**Comment by mareknovotny** [comment]
i won't insist now on launching it againg and merge it

**Pull request merged**
