### PR TITLE
[RHPAM-2977] upgrade to jackson 2.10.4 + wildfly 19

### PR DESCRIPTION
**Pull request by mariofusco**
Merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2125

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
from FDB we would need also https://github.com/errai/errai/pull/388

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
@mareknovotny I send a pull request to errai with user https://github.com/errai/errai/pull/389 and retriggered the full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

errai wf distro is now released https://repository.jboss.org/nexus/index.html#nexus-search;gavorg.jboss.erraiwildfly-dist~19.1.0.Final~~

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@ruromero could you please look at ProcessMigrationIntegrationTest failure ?

**Comment by ruromero** [comment]
I've sent a PR to @mariofusco 's branch to bump Thorntail to 2.7.0 which uses the same Jackson version although is still based on Wildfly 18
Due to this change some exclusions need to be added to the process-migration-service project. See https://github.com/kiegroup/droolsjbpm-integration/pull/2131

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

I can't reproduce failure for ProcessMigrationIntegrationTest's tests, the other 2 are reported jira

**Comment by mareknovotny** [comment]
it seems we overlooked one problem with wildfly-dist and its missing X attribute in scripts zip. It is in the FDB, but haven'ŧ noticed that

**Pull request merged**
