### PR TITLE
BXMSPROD-1037: jackson upgraded to 2.11.0

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/BXMSPROD-1037

**referenced Pull Requests**:

* https://github.com/kiegroup/appformer/pull/1075
* https://github.com/kiegroup/jbpm/pull/1796

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by akoufoudakis** [comment]
jenkins do fdb

**Comment by akoufoudakis** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
closed in favour of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1557

**Pull request closed without merging**
