### PR TITLE
[JBPM-9634] Upgrade testcontainers to 1.15.2

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9634](https://issues.redhat.com/browse/JBPM-9634)

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-integration/pull/2413

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins run fdb

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by gmunozfe** [comment]
jenkins run fdb

**Comment by gmunozfe** [comment]
@mareknovotny could this be merged? Tests from droolsjbpm-integration (those using testcontainers) were executed correctly, but overall execution failed by timeout

**Pull request merged**
