### PR TITLE
[DO NOT MERGE] AF-2829 : Conscious language initiative (Design tools)

### PR DESCRIPTION
**Pull request by akumar074**
* Upgrade Errai version to 4.14.2.Final

**JIRA**: 
[AF-2829](https://issues.redhat.com/browse/AF-2829)

**referenced Pull Requests**: 
* https://github.com/kiegroup/optaplanner-wb/pull/401
* https://github.com/kiegroup/kie-wb-playground/pull/117
* https://github.com/kiegroup/kie-soup/pull/219
* https://github.com/kiegroup/appformer/pull/1178
* https://github.com/kiegroup/kie-wb-common/pull/3665
* https://github.com/kiegroup/drools-wb/pull/1509
* https://github.com/kiegroup/jbpm-designer/pull/914
* https://github.com/kiegroup/jbpm-wb/pull/1509
* https://github.com/kiegroup/kie-wb-distributions/pull/1118

**Businnes Central Distribution**: [Download](https://drive.google.com/file/d/163uatfBlK6TkiuZbbjDpx18WJv1fh2pT/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by tiagobento** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@karreiro Hi! I added you as a reviewer for `drools-wb` and `kie-wb-common`. Feel free to reassign if you think it's  better.

@barboras7 I added you as a reviewer on all the related PRs. FDB is almost finished, so after it is, you can use the WAR produced there to perform tests.

Abhishek is currently investigating some failures on the FDB tests. Please reach out if you have questions!

Thanks @akumar074 for the PR!

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
FDB failure seems random. For testing please download the attached BC distribution in PR description.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
@akumar074 HI Abhishek! All the test failures seem related to the changes on the PRs. Can you please check?

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
Jenkins run cdb

**Comment by tiagobento** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by barboras7 — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
Failures are unrelated and were already fixed here: https://github.com/kiegroup/jbpm/pull/1994

**Pull request merged**
