### PR TITLE
[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#1565)

### PR DESCRIPTION
**Pull request by elguardian**
Jira :https://issues.redhat.com/browse/JBPM-9549

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

```
exec-maven-plugin:1.5.0:exec (run-cypress-tests) @ optaweb-vehicle-routing-standalone ---
[2021-03-02T06:31:14.372Z] 
[2021-03-02T06:31:14.372Z] ====================================================================================================
[2021-03-02T06:31:14.372Z] 
[2021-03-02T06:31:14.372Z]   (Run Starting)
[2021-03-02T06:31:14.372Z] 
[2021-03-02T06:31:14.372Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-03-02T06:31:14.372Z]   │ Cypress:    4.12.1                                                                             │
[2021-03-02T06:31:14.372Z]   │ Browser:    Electron 80 (headless)                                                             │
[2021-03-02T06:31:14.372Z]   │ Specs:      1 found (fromLocationsToRoute.js)                                                  │
[2021-03-02T06:31:14.372Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[2021-03-02T06:31:14.372Z] 
[2021-03-02T06:31:14.372Z] 
[2021-03-02T06:31:14.372Z] ────────────────────────────────────────────────────────────────────────────────────────────────────
[2021-03-02T06:31:14.372Z]                                                                                                     
[2021-03-02T06:31:14.372Z]   Running:  fromLocationsToRoute.js                                                         (1 of 1)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   (Results)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-03-02T06:32:35.802Z]   │ Tests:        1                                                                                │
[2021-03-02T06:32:35.802Z]   │ Passing:      0                                                                                │
[2021-03-02T06:32:35.802Z]   │ Failing:      1                                                                                │
[2021-03-02T06:32:35.802Z]   │ Pending:      0                                                                                │
[2021-03-02T06:32:35.802Z]   │ Skipped:      0                                                                                │
[2021-03-02T06:32:35.802Z]   │ Screenshots:  1                                                                                │
[2021-03-02T06:32:35.802Z]   │ Video:        true                                                                             │
[2021-03-02T06:32:35.802Z]   │ Duration:     1 minute, 5 seconds                                                              │
[2021-03-02T06:32:35.802Z]   │ Spec Ran:     fromLocationsToRoute.js                                                          │
[2021-03-02T06:32:35.802Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   (Screenshots)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   -  /e2e/cypress/screenshots/fromLocationsToRoute.js/Locations can be added and rout     (1280x720)
[2021-03-02T06:32:35.802Z]      e is computed -- Locations added via clicking on a map are added to a route -- b               
[2021-03-02T06:32:35.802Z]      efore all hook (failed).png                                                                    
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   (Video)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   -  Started processing:  Compressing to 32 CRF                                                     
[2021-03-02T06:32:35.802Z]   -  Finished processing: /e2e/cypress/videos/fromLocationsToRoute.js.mp4                (6 seconds)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] ====================================================================================================
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]   (Run Finished)
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z]        Spec                                              Tests  Passing  Failing  Pending  Skipped  
[2021-03-02T06:32:35.802Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-03-02T06:32:35.802Z]   │ ✖  fromLocationsToRoute.js                  01:05        1        -        1        -        - │
[2021-03-02T06:32:35.802Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[2021-03-02T06:32:35.802Z]     ✖  1 of 1 failed (100%)                     01:05        1        -        1        -        -  
[2021-03-02T06:32:35.802Z] 
[2021-03-02T06:32:35.802Z] [ERROR] Command execution failed.
[2021-03-02T06:32:35.802Z] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[2021-03-02T06:32:35.802Z]     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
[2021-03-02T06:32:35.802Z]     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
[2021-03-02T06:32:35.802Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
[2021-03-02T06:32:35.802Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
[2021-03-02T06:32:35.802Z]     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2021-03-02T06:32:35.802Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2021-03-02T06:32:35.802Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2021-03-02T06:32:35.802Z]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2021-03-02T06:32:35.802Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2021-03-02T06:32:35.802Z]     at java.lang.reflect.Method.invoke (Method.java:498)
[2021-03-02T06:32:35.802Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2021-03-02T06:32:35.802Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2021-03-02T06:32:35.802Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2021-03-02T06:32:35.802Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
cypress test failed and it stopped the whole downstream build
``` [2021-03-10T16:46:36.418Z] [ERROR] Command execution failed.
[2021-03-10T16:46:36.418Z] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[2021-03-10T16:46:36.418Z]     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
[2021-03-10T16:46:36.418Z]     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
[2021-03-10T16:46:36.418Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
[2021-03-10T16:46:36.418Z]     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
[2021-03-10T16:46:36.418Z]     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2021-03-10T16:46:36.418Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2021-03-10T16:46:36.418Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2021-03-10T16:46:36.418Z]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2021-03-10T16:46:36.418Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2021-03-10T16:46:36.418Z]     at java.lang.reflect.Method.invoke (Method.java:498)
[2021-03-10T16:46:36.418Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2021-03-10T16:46:36.418Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2021-03-10T16:46:36.418Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2021-03-10T16:46:36.418Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
Is it possible to handle cypress test to not end as error but failure? what is the root cause of that error is not clear to me @yurloc @dupliaka any idea?

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by yurloc** [comment]
The test fails because optaweb-vehicle-routing-backend is broken and that's caused by the Spring Boot upgrade.

**Pull request merged**
