### PR TITLE
BXMSPROD-685: upgrade of different version of org.jboss.spec

### PR DESCRIPTION
**Pull request by mbiarnes**
upgraded version.org.jboss.spec.javax.ejb.jboss-ejb-api_3.2_spec

upgraded version.org.jboss.spec.javax.el.jboss-el-api_3.0_spec

upgraded version.org.jboss.spec.javax.enterprise.concurrent

upgraded version version.org.jboss.spec.javax.interceptor.jboss-interceptors-api_1.2_spec

upgraded version.org.jboss.spec.javax.jms

upgraded version.org.jboss.spec.javax.security.jacc.jboss-jacc-api_1.5_spec

upgraded version.org.jboss.spec.javax.servlet.jsp

upgraded version.org.jboss.spec.javax.websocket

upgraded version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/1844/consoleText
Duplicate classes found:

  Found in:
    org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
    org.jboss.spec.javax.transaction:jboss-transaction-api_1.3_spec:jar:2.0.0.Final:provided

**Comment by mareknovotny** [comment]
I think we could avoid spec upgrades for first upgrade wave. Otherwise you need to change all spec declaration in subsequent downstream repositories.

**Comment by mbiarnes** [comment]
OK

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

2 failures

* org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT - bc monitoring didn't deployed
* org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest - timed out

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
again org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest - timed out I think we can merge this

**Comment by Rikkola** [comment]
@mbiarnes @mareknovotny We might have to revert this. drools-wb is failing due to having two versions of jboss-servlet-api. I suspect this is the cause.

**Comment by mareknovotny** [comment]
there is quick fix to exclude that dep, do not revert it, I will do it quickly

**Pull request merged**
