### PR TITLE
BXMSPROD-580: version.frontend-maven-plugin property added with 1.8.0 value

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-580

### CODE REVIEW

**Comment by Ginxo** [comment]
@mareknovotny the full downstream test is required.
The frontend-maven-plugin logs should be checked

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
looks ok, maybe we should move plugin version usage to pluginManagement section definition and keep individual plugin elements in builds with managed plugin from KIE-PARENT.

**Comment by Ginxo** [comment]
@mareknovotny done for https://github.com/kiegroup/kie-wb-common/pull/3025/files and https://github.com/kiegroup/appformer/pull/850/files

**Comment by rsynek** [comment]
@Ginxo I don't see employee-rostering among the opened PRs, please have a look here:
https://github.com/kiegroup/optaweb-employee-rostering/blob/master/employee-rostering-frontend/pom.xml#L33

**Comment by Ginxo** [comment]
@rsynek good catch https://github.com/kiegroup/optaweb-employee-rostering/pull/330

**Comment by yurloc** [comment]
@Ginxo The version should be used in kie-parent's plugin management, not in each repository's root POM plugin management. @mareknovotny Is that what you proposed?

**Comment by Ginxo** [comment]
@yurloc we discussed exactly this and we agreed to have it on each frontend repo, because probably it's not a good idea to put this on kie-parent as this will be only used by frontend projects

**Comment by yurloc** [comment]
@Ginxo I've thought about it and I can't agree. I'm not saying it's wrong but it's not consistent. kie-parent's plugin management already contains several exotic plugins that don't seem like something that's used by majority of projects. For consistency reasons I would follow that.

If you're worried by polluting projects by information about plugins they don't use, please not that the plugin configuration under `<pluginManagement>` is not effective until the plugin is referenced from a child project's `<plugins>` element.

https://maven.apache.org/pom.html#Plugin_Management:
> ... this only configures plugins that are actually referenced within the plugins element in the children or in the current POM

**Comment by mareknovotny** [comment]
yes, I think pluginManagement is better to have always in a parent, as this reduce duplication of declarations and unifies the build.

**Comment by mareknovotny** [comment]
failures on FDB seems broken on master as I have seen them in the other opened PRs
tagging @MarianMacik

**Comment by yurloc** [comment]
I don't see much point in executing FDB in this case. You can't break anything by adding a property, can you? Can you???? :laughing:

Seriously, the property is [not even used](https://github.com/search?q=org%3Akiegroup+version.frontend-maven-plugin&type=Code) anywhere on master (GitHub search is fuzzy so the results are false positives).

The effect of this PR will be verified in individual PR builds in repositories where it's *going to be* used.

**Comment by mareknovotny** [comment]
@yurloc why not? FDB does cloning all branches related to this and having the same branch name so the all which are linked to this top parent PR. Look at the Jenkins and look for `Downstream repositories builder for PR builds started.`

```
Working with PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1117
Cleaning-up directory /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-build-bootstrap-downstream-pullrequests/downstream-repos
Using repository-list.txt from GitHubRepository{owner='Ginxo', name='droolsjbpm-build-bootstrap'},GitBranch{name='BXMSPROD-580'}.
GitHub repositories that will be cloned and built:
	git://github.com/kiegroup/kie-soup.git:master:master-pr-build
	git://github.com/kiegroup/appformer.git:pull/850/merge:pr850-BXMSPROD-580-merge
	git://github.com/kiegroup/droolsjbpm-knowledge.git:master:master-pr-build
	git://github.com/kiegroup/drools.git:master:master-pr-build
	git://github.com/kiegroup/optaplanner.git:master:master-pr-build
	git://github.com/kiegroup/jbpm.git:master:master-pr-build
	git://github.com/kiegroup/kie-jpmml-integration.git:master:master-pr-build
	git://github.com/kiegroup/droolsjbpm-integration.git:pull/1942/merge:pr1942-BXMSPROD-580-merge
	git://github.com/kiegroup/openshift-drools-hacep.git:master:master-pr-build
	git://github.com/kiegroup/kie-uberfire-extensions.git:master:master-pr-build
	git://github.com/kiegroup/kie-wb-playground.git:master:master-pr-build
	git://github.com/kiegroup/kie-wb-common.git:pull/3025/merge:pr3025-BXMSPROD-580-merge
	git://github.com/kiegroup/drools-wb.git:master:master-pr-build
	git://github.com/kiegroup/optaplanner-wb.git:master:master-pr-build
	git://github.com/kiegroup/jbpm-designer.git:master:master-pr-build
	git://github.com/kiegroup/jbpm-work-items.git:master:master-pr-build
	git://github.com/kiegroup/jbpm-wb.git:master:master-pr-build
	git://github.com/kiegroup/optaweb-employee-rostering.git:master:master-pr-build
	git://github.com/kiegroup/optaweb-vehicle-routing.git:pull/228/merge:pr228-BXMSPROD-580-merge
	git://github.com/kiegroup/kie-wb-distributions.git:master:master-pr-build
```

**Comment by yurloc** [comment]
@mareknovotny Nice. I didn't know FDB checks out related feature branches.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins execute full downstream build

**Comment by Ginxo** [comment]
com.github.eirslett:frontend-maven-plugin moved to pluginManagement and declaration removed from frontend projects:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap
- https://github.com/kiegroup/kie-wb-common
- https://github.com/kiegroup/appformer
- https://github.com/kiegroup/droolsjbpm-integration
- https://github.com/kiegroup/optaweb-vehicle-routing
- https://github.com/kiegroup/optaweb-employee-rostering

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by Ginxo** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Pull request merged**
