### PR TITLE
BXMSPROD-1267: upgrade of kubernetes-client to 4.7.2

### PR DESCRIPTION
**Pull request by mareknovotny**
**JIRA**: 

https://issues.redhat.com/browse/BXMSPROD-1267

**related PRs**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2558

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by AntStephenson — APPROVED** [review]
LGTM, pending green result

**Comment by mareknovotny** [comment]
jenkins do fdb
just to be sure the tests are not random failures

**Comment by mareknovotny** [comment]
so second round of FDB show only 6 failures minus 1 test failure:

- org.kie.server.controller.openshift.storage.OpenShiftServerTemplateStorageTest.testLoadWithCache
- org.kie.server.controller.openshift.storage.OpenShiftServerTemplateStorageTest.testLoadKeysWithCacheExpire
- org.kie.server.controller.openshift.storage.OpenShiftServerTemplateStorageTest.testLoadKeysWithCache
- org.kie.server.controller.openshift.storage.OpenShiftServerTemplateStorageTest.testStoreLoadAndDeleteServerTemplate
- org.kie.server.controller.openshift.storage.OpenShiftServerTemplateStorageTest.testStoreAndLoadServerTemplates
- org.kie.server.services.openshift.impl.storage.cloud.KieServerStateOpenShiftRepositoryRegularTest.testRetrieveAllKieServerIdsAndStates

**Comment by mareknovotny** [comment]
@sutaakar any what is wrong behind OpenShiftServerTemplateStorageTest's failures ?

**Comment by mareknovotny** [comment]
the link to previous FDB https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/fdb/job/droolsjbpm-build-bootstrap-master.fdb/83/#showFailuresLink

**Comment by sutaakar** [comment]
@mareknovotny Looks like the OpenShift server mock doesn't work properly on that upgraded version. With workaround from https://github.com/sutaakar/droolsjbpm-integration/commit/e0ed1f584c7ead49946de46a46d358793a433a54 it works ok.

**Comment by mareknovotny** [comment]
is there possible to use even newer version which works with labels? i don't like workarounds to keep here the version we are trying to upgrade as we should get rid of that version completely.

**Comment by sutaakar** [comment]
@mareknovotny Seems that label support in mock client is bad in general. From local experiments the label related tests usually don't work properly against mock. One option would be to ignore those tests.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
now it fails on 3 different tests not related to changed dependency :(

- org.kie.workbench.common.services.datamodel.backend.server.ModuleDataModelConcurrencyTest.testConcurrentResourceUpdates 
- org.jbpm.workitem.springboot.samples.KafkaProxySampleTest.testKafkaWIHReconnect[0: SINGLETON]
- org.guvnor.m2repo.backend.server.GuvnorM2RepositoryTest.testDeployArtifactWithDeployArtifactDistributionManagement

WDYT @sutaakar

**Comment by sutaakar** [comment]
GuvnorM2RepositoryTest - fails for several builds in a row, should be unrelated
ModuleDataModelConcurrencyTest - fails on other builds too - probably unrelated intermittent issue
KafkaProxySampleTest - I think it is unrelated
@mareknovotny I would say that we can consider FDB as green for this PR.

**Comment by mareknovotny** [comment]
thanks @sutaakar for detailed check of failed tests

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by sutaakar — APPROVED** [review]

**Pull request merged**
