### PR TITLE
Bump postgresql version to 42.2.12

### PR DESCRIPTION
**Pull request by cuijulian**
Merge with:

https://github.com/kiegroup/optaplanner/pull/796
https://github.com/kiegroup/kie-benchmarks/pull/85
https://github.com/kiegroup/kie-wb-distributions/pull/1036
https://github.com/kiegroup/jbpm/pull/1674
https://github.com/kiegroup/droolsjbpm-integration/pull/2124
https://github.com/kiegroup/optaweb-vehicle-routing/pull/322
https://github.com/kiegroup/optaweb-employee-rostering/pull/448

### CODE REVIEW

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by cuijulian** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
The full downstream build failed on these 2 tests:


```
org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup[1:  JSON KieServicesConfiguration{transport=REST,  serverUrl='http://localhost:36389/kie-server-services/services/rest/server'}] | 8 min 1 sec | 1
-- | -- | --
org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest | 1.8 sec | 4

```

Do we have any proof that they are NOT random failing tests?
These days, they are guilty for random failures until proven innocent :)

**Comment by mareknovotny** [comment]
**org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest** is known problem reported as https://issues.redhat.com/browse/DROOLS-5321
and the org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.testContainerDisposedAfterStartup timed out

Jenkins execute full downstream build

**Comment by cuijulian** [comment]
@mareknovotny The same `org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest` failed again. Should be good to merge?

**Pull request merged**
