### PR TITLE
JBPM-9208: upgrade mysql connector dependency to 5.1.49

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
[ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.7.9:stop (stop-container) on project camel-container-integration-tests: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly18xInstalledLocalContainer@385d94a7]: Failed to stop the WildFly 19.1.0.Final container. Failure when invoking CLI script, java returned 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.7.9:stop (stop-container) on project camel-container-integration-tests: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly18xInstalledLocalContainer@385d94a7]

Failed to stop the WildFly **19.1.0**.Final container AND org.codehaus.cargo.container.wildfly.**WildFly18x**InstalledLocalContainer@385d94a7
could this be a problem?

**Comment by mareknovotny** [comment]
@mbiarnes I would say that is not the root cause of problem, but I don't see why we shouldn't upgrade the cargo container https://codehaus-cargo.github.io/cargo/WildFly+19.x.html it is now available.

**Comment by mareknovotny** [comment]
so the cargo container upgrade is available as https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1390

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
closing in favor of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1381

**Pull request closed without merging**
