### PR TITLE
change of pull_request_template.dm

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

paste the link(s) from GitHub here

**How to retest or run**:

* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
  
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
  
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**

* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**

* an upstream build please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) upstream.\*]**

i.e for running a full downstream build =  **Jenkins do fdb**

### CODE REVIEW

**Comment by mareknovotny** [comment]
what is the reason of change from direct mentioning to linked document?

**Comment by mbiarnes** [comment]
@mareknovotny the space used in the template and the "interest" of people reading it: I am free for every change

**Comment by mbiarnes** [comment]
@mareknovotny @hasys This looks nice.It can be changed any time in any rep. 
image

**Comment by hasys** [comment]
@mbiarnes can we replace regexp by normal string for copy/paste?

**Comment by mbiarnes** [comment]
DONE:
image

**Pull request merged**
