### PR TITLE
RHPAM-3234 httpclient to 4.5.13

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: 
* https://issues.redhat.com/browse/RHPAM-3234
* https://issues.redhat.com/browse/RHDM-1476

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
Jenkins execute product fdb

**Comment by Ginxo** [comment]
after executing FDBP 
image

**Review by AntStephenson — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
@mareknovotny from FDB
image

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
