### PR TITLE
[DROOLS-5195] remove no longer supported integration modules

### PR DESCRIPTION
**Pull request by mariofusco**
merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2075

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
why new PR instead of #1279 ?

**Comment by mariofusco** [comment]
> why new PR instead of #1279 ?

I had to rebase against master because the old one was no longer compiling at all. It failed with a message like

Compilation failure: 
[ERROR] /home/mfusco/workspace/droolsjbpm/droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/test/java/org/kie/server/services/taskassigning/core/AbstractTaskAssigningTest.java:[3,17] package org.slf4j does not exist

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
there are again failing tests which should be fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/2073 :( @jiripetrlik any idea why  still failing?

**Comment by mariofusco** [comment]
@mareknovotny @jiripetrlik I tested the kie-camel module locally and it works for me. I believe that in CI (for some reasons) this PR its not seeing latest changes in Jiri's commit. I'll merge everything and try everything again.

**Pull request merged**
