### PR TITLE
removed Opta* projects

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/optaplanner-wb/pull/429

You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it. 

A general local execution could be the following one, where the tool clones all dependent projects starting from the `-sp` one and it locally applies the pull request (if it exists) in order to reproduce a complete build scenario for the provided *Pull Request*.

> **Note:** the tool considers multiple *Pull Requests* related to each other if their branches (generally in the forked repositories) have the same name.

``` shell
$ build-chain-action -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url <pull-request-url> -sp kiegroup/kie-wb-distributions [--skipExecution]
```

> Consider changing `kiegroup/kie-wb-distributions` with the correct starting project.

</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

* <b>for windows-specific os job</b> add the label `windows_check`
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
lgtm

**Review by Ginxo — CHANGES_REQUESTED** [review]
LGTM but I would say `removed OptaPlanner from 7.x stream` should be replaced right? since it is not 7.x stream :thinking:

**Comment by lampajr** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
> LGTM but I would say `removed OptaPlanner from 7.x stream` should be replaced right? since it is not 7.x stream thinking

What do you mean by that ? @ginxo

**Comment by lampajr** [comment]
FDB build is green, just two tests failures:
```
[2023-06-30T15:35:21.502Z] [ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.092 s <<< FAILURE! - in org.jbpm.process.workitem.email.SendHtmlTest
 [2023-06-30T15:35:21.502Z] [ERROR] testConnectionEquals(org.jbpm.process.workitem.email.SendHtmlTest)  Time elapsed: 0.004 s  <<< ERROR!
 [2023-06-30T15:35:21.502Z] java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
 [2023-06-30T15:35:21.502Z]  at org.subethamail.smtp.server.SMTPServer.start(SMTPServer.java:241)
 [2023-06-30T15:35:21.502Z]  at org.subethamail.wiser.Wiser.start(Wiser.java:90)
```

and

```
 [2023-06-30T16:18:25.883Z] [ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.316 s <<< FAILURE! - in org.kie.server.client.LoadBalancerClientTest
 [2023-06-30T16:18:25.883Z] [ERROR] testDefaultLoadBalancerNoServersAvailable(org.kie.server.client.LoadBalancerClientTest)  Time elapsed: 5.445 s  <<< ERROR!
 [2023-06-30T16:18:25.883Z] org.kie.server.common.rest.NoEndpointFoundException: No available endpoints found
 [2023-06-30T16:18:25.883Z]  at org.kie.server.client.balancer.impl.AbstractBalancerStrategy.checkEmpty(AbstractBalancerStrategy.java:27)
 [2023-06-30T16:18:25.883Z]  at org.kie.server.client.balancer.impl.RoundRobinBalancerStrategy.next(RoundRobinBalancerStrategy.java:37)
 [2023-06-30T16:18:25.883Z]  at org.kie.server.client.balancer.LoadBalancer.getUrl(LoadBalancer.java:84)
```

**Comment by lampajr** [comment]
Optaplanner and optaplanner-wb correctly removed from the list of projects to be cloned:
```
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/lienzo-core]
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/lienzo-core:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/droolsjbpm-build-bootstrap] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/droolsjbpm-build-bootstrap:main 
 [2023-06-30T13:50:49.815Z] [INFO]    Merged mbiarnes/droolsjbpm-build-bootstrap:removeOptaPlanner into branch main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-soup] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-soup:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/lienzo-tests] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/lienzo-tests:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/appformer] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/appformer:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-uberfire-extensions] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-uberfire-extensions:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/droolsjbpm-knowledge] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/droolsjbpm-knowledge:7.x 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/drools] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/drools:7.x 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/jbpm] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/jbpm:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/droolsjbpm-integration] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/droolsjbpm-integration:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-wb-playground] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-wb-playground:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-wb-common] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-wb-common:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/drools-wb] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/drools-wb:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/jbpm-work-items] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/jbpm-work-items:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/jbpm-wb] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/jbpm-wb:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-wb-distributions] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-wb-distributions:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/kie-jpmml-integration] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/kie-jpmml-integration:main 
 [2023-06-30T13:50:49.815Z] [INFO] [kiegroup/process-migration-service] 
 [2023-06-30T13:50:49.815Z] [INFO]    Project taken from kiegroup/process-migration-service:main 
```

**Comment by Ginxo** [comment]
> > LGTM but I would say `removed OptaPlanner from 7.x stream` should be replaced right? since it is not 7.x stream thinking
> 
> What do you mean by that ? @ginxo

I mean PR title which already adapted

**Review by lampajr — APPROVED** [review]

**Pull request merged**
