### PR TITLE
[7.3.x] Cherry pick of formatter changes from master branch

### PR DESCRIPTION
**Pull request by hasys**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Related PRs: https://github.com/kiegroup/droolsjbpm-knowledge/pull/269, https://github.com/kiegroup/jbpm-designer/pull/662, https://github.com/kiegroup/kie-wb-common/pull/1176

**Comment by hasys** [comment]
Hi @ge0ffrey, @manstis, @psiroky, Full Downstream build is red due to one test fail with `GC overhead limit exceeded`. Looks like it is not related to PR. Wht do you think is it ready to merge (with all related PRs listed above) or we need green build at any cost?

**Comment by hasys** [comment]
Full Downstream Build is red due to false positive test fails, not due to compilation errors:
- [GC overhead limit exceeded]:  [org.drools.workbench.services.verifier.webworker.client.SpeedTest.noConflictTable](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-build-bootstrap-downstream-pullrequests/95/testReport/junit/org.drools.workbench.screens.guided.dtree.backend.server.indexing/IndexRuleMultipleTypesTest/testIndexDrlRuleMultipleTypes/) - GC overhead limit exceeded

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Hi @manstis, it is hard to maintain this PRs. And it looks like it will never be green due to random tests fails. I guess Imports changes are OK, because everything is building. And imports rearrangements in my opinion shouldn't break anything. Can we merge this or close it? @tsurdilo and @romartin are already asking for it for some time.

**Comment by hasys** [comment]
Closing this because 7.3 branch is dead. Related PRs created for 7.4.x https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/591

**Pull request closed without merging**
