### PR TITLE
BXMSPROD-685: upgrade org.jboss.logging

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1219
https://github.com/kiegroup/droolsjbpm-integration/pull/2039

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
BUILD was unstable, two tests failed https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/1817/testReport/
+1 to merge

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
Can you please look at failures https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/droolsjbpm-build-bootstrap.downstream/89/ in kie-server @elguardian ? Are they valid failures?

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny 
failure in droolsjbpm-integration
ban-duplicated-classes 
o  'org.drools:drools-cdi'
o  'org.drools:drools-jsr94'

**Comment by mareknovotny** [comment]
:o I see there some different ban-duplicated-classes log msgs
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    com.zaxxer:HikariCP-java7:jar:2.4.13:compile
    com.zaxxer:HikariCP:jar:3.4.1:compile
  Duplicate classes:
```
https://github.com/kiegroup/droolsjbpm-integration/commit/a62f6758e1a28315f55cd3c0b874721f1bec5265#diff-2c13f0d6dc37b0068ce54c21d75b2c83

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Comment by mareknovotny** [comment]
build failed due parsing of beans.xml which is not related to this changes
issue reported as https://issues.redhat.com/browse/DROOLS-5415 and on the way to be merged

**Comment by mareknovotny** [comment]
Jenkins run full downstream build

**Pull request merged**
