### PR TITLE
undertow update to 2.0.23.Final

### PR DESCRIPTION
**Pull request by mareknovotny**
Change-Id: I93f79ce4a53473e2d1605bc378803dcdd5d8e7f0

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Can you review @mbiarnes and merge if you agree?

**Pull request merged**
