### PR TITLE
JBPM-9227: upgrade maven cargo plugin for newer Wildlfy 19 container

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/JBPM-9227

Merge together with:
- https://github.com/kiegroup/jbpm/pull/1696
- https://github.com/kiegroup/droolsjbpm-integration/pull/2150
- https://github.com/kiegroup/kie-wb-distributions/pull/1045

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
this PR depends on fixing cargo container in build command, fix in https://github.com/kiegroup/droolsjbpm-integration/pull/2148

**Comment by mbiarnes** [comment]
@mareknovotny is a rebase needed?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
> @mareknovotny is a rebase needed?

it should not be required, otherwise github would show here a conflict

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@jomarko thanks for confirmation, i still see here in FDB 61 failures, not sure if that is related or real broken tests

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
