### PR TITLE
PLANNER-1682: Remove optaplanner-core-gwt module

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Part of PR set:
https://github.com/kiegroup/optaplanner/pull/619

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Jenkins execute full downstream build

**Comment by ge0ffrey** [comment]
Full downstream build fails because of these random(?) failing tests (@porcelli  @ederign) on workbench:

Test Result (36 failures / -1)

    org.drools.workbench.screens.guided.dtable.client.editor.menu.RadarMenuBuilderTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.BoundaryTransformMediatorTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.GuidedDecisionTableModellerContextMenuSupportTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.GuidedDecisionTableModellerPresenterTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.GuidedDecisionTableViewImplTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.columns.BaseEnumSingleSelectUiColumnTest.org.drools.workbench.screens.guided.dtable.client.widget.table.columns.BaseEnumSingleSelectUiColumnTest
    org.drools.workbench.screens.guided.dtable.client.widget.table.columns.BooleanUiColumnTest.org.drools.workbench.screens.guided.dtable.client.widget.table.columns.BooleanUiColumnTest
    org.drools.workbench.screens.guided.dtable.client.widget.table.columns.DateUiColumnTest.org.drools.workbench.screens.guided.dtable.client.widget.table.columns.DateUiColumnTest
    org.drools.workbench.screens.guided.dtable.client.widget.table.columns.PriorityCellRendererTest.org.drools.workbench.screens.guided.dtable.client.widget.table.columns.PriorityCellRendererTest
    org.drools.workbench.screens.guided.dtable.client.widget.table.columns.ValueListUiColumnCellRendererTest.org.drools.workbench.screens.guided.dtable.client.widget.table.columns.ValueListUiColumnCellRendererTest
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.tabKeyCanvasActions
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.escapeKeyCanvasActions
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.enterKeyCanvasActions
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.tabKeyWithShiftMovesLeft
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.tabKeyWithoutShiftMovesRight
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.enterKeyWithShiftMovesUp
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.enterKeyWithoutShiftMovesDown
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.escapeKeyDoesNotMoveAnywhere
    org.drools.workbench.screens.guided.dtable.client.widget.table.keyboard.KeyDownHandlerDatePickerTest.keyPressStopsPropagation
    org.drools.workbench.screens.guided.dtable.client.widget.table.model.converters.column.impl.GridWidgetColumnFactoryImplTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.popovers.ColumnHeaderPopOverHandlerTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.popovers.ColumnHeaderPopOverImplTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.themes.GuidedDecisionTableRendererTest.initializationError
    org.drools.workbench.screens.guided.dtable.client.widget.table.themes.GuidedDecisionTableThemeTest.initializationError
    org.drools.workbench.screens.guided.dtree.client.widget.GuidedDecisionTreeWidgetTest.testDeleteShapeNotConfirmed
    org.drools.workbench.screens.guided.dtree.client.widget.GuidedDecisionTreeWidgetTest.testDeleteShapeConfirmedNonRootNode
    org.drools.workbench.screens.guided.dtree.client.widget.GuidedDecisionTreeWidgetTest.testDeleteShapeConfirmedRootNode
    org.kie.workbench.common.stunner.bpmn.client.shape.def.ServiceTaskShapeDefTest.testGetGlyph
    org.kie.workbench.common.stunner.bpmn.client.shape.def.ServiceTaskShapeDefTest.testViewHandler
    org.kie.workbench.common.stunner.bpmn.client.shape.def.ServiceTaskShapeDefTest.testSizeHandler
    org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.BPMNViewHandlersTest.org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.BPMNViewHandlersTest
    org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.EventCancelActivityViewHandlerTest.org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.EventCancelActivityViewHandlerTest
    org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.EventInterruptingViewHandlerTest.org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.EventInterruptingViewHandlerTest
    org.kie.workbench.common.stunner.bpmn.client.shape.view.handler.ServiceTaskShapeViewHandlerTest.testHandle
    org.kie.workbench.common.stunner.bpmn.project.client.handlers.CaseDefinitionNewResourceHandlerTest.org.kie.workbench.common.stunner.bpmn.project.client.handlers.CaseDefinitionNewResourceHandlerTest
    org.kie.workbench.common.stunner.bpmn.project.client.handlers.util.CaseHelperTest.org.kie.workbench.common.stunner.bpmn.project.client.handlers.util.CaseHelperTest

**Comment by manstis** [comment]
@ge0ffrey actually they're not random at all.. but caused by you!

See https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1124

**Comment by manstis** [comment]
But let's keep merging PRs that are not green due to DIMBY principles.

**Comment by ederign** [comment]
As @manstis already said, those tests are not random failures and IMO it's risky to classify everything that fails as "random failures" and merge the PR's anyway.

I also strongly suggest that every PR has a QE involved reviewing and approving the change and also to run FBD for every PR (looks like we did this for this one).

For sure there is some exceptions for this, i.e. when we are in a rush to fix a broken build, but I don't think that is the case.

**Pull request merged**
