### PR TITLE
Add optaweb-vehicle-routing to repository list

### PR DESCRIPTION
**Pull request by yurloc**

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by yurloc** [comment]
Please do not merge until we have a green build, ok? Currently the build fails due to an enforcer failure at `kie-wb-common-compiler-distribution`:
23:35:57 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
23:35:57 Found Banned Dependency: commons-logging:commons-logging:jar:1.1.1
23:35:57 Use 'mvn dependency:tree' to locate the source of the banned dependencies.

Due to this, the newly added repository (optaweb-vehicle-routing) wasn't built and we don't know if it will build successfully. If we keep merging changes without having them checked, we'll never get a green build.

**Comment by mareknovotny** [comment]
@yurloc there is https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/998 to fix that in kie-parent

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by yurloc** [comment]
@mareknovotny Please check again. I've upgraded `extra-enforcer-rules` so that `module-info.class`es are ignored automatically. This is needed to build `optaweb-vehicle-routing` successfully as it has a few dependencies that use Java 9 modules (byte-buddy, log4j-api). I'm gonna execute full downstream build anyway so we'll have a confirmation that this upgrade doesn't break anything.

Note that `1.0-beta-7` is not the latest version. It's the first release that contains the fix for https://github.com/mojohaus/extra-enforcer-rules/issues/42. We can upgrade to latest later, in a dedicated PR, wdyt?

**Comment by yurloc** [comment]
Jenkins execute full downstream build.

**Comment by mareknovotny** [comment]
ok, thanks!

**Comment by yurloc** [comment]
@mbiarnes Full downstream build finished and `optaweb-vehicle-routing` built successfully. There are 7 test failures, which I believe cannot be related to changes in this PR. I'll go through them nevertheless and notify responsible people if there is a good chance to improve their stability.

Please merge.

**Pull request merged**
