### PR TITLE
BXMSPROD-722 netty upgraded to 4.1.46

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-722

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
there is failure in
`org.kie.workbench.common.services.backend.compiler.DefaultMavenCompilerTest.buildWithAllDecoratorsTest` socket not open seems like random environmental issue?

Jenkins execute full downstream build

**Comment by Ginxo** [comment]
@mareknovotny let's wait to the downstream executions (old and new) and we could check the results, do you agree?

**Comment by Ginxo** [comment]
@mareknovotny relaunching BXMSPROD-710/droolsjbpm-build-bootstrap.downstream/11 since the github connection failed
```
stderr: fatal: unable to access 'https://github.com/kiegroup/jbpm.git/': Failed connect to github.com:443; Connection timed out
```

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by AntStephenson** [comment]
LGTM, pending successful run ;)

**Comment by Ginxo** [comment]
branch merged with master
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
> branch merged with master
> Jenkins execute full downstream build

:o ?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
@mareknovotny it can be merged since the droolsjbpm-build-bootstrap-downstream-pullrequests/1940 is ok
The droolsjbpm-build-bootstrap.downstream/33 job failed while checking out kiegroup/droolsjbpm-knowledge git project. Retrying that one

**Pull request merged**
