### PR TITLE
[7.67.x-blue] Update camel to 2.25.4.

### PR DESCRIPTION
**Pull request by baldimir**
Related PR: https://github.com/kiegroup/droolsjbpm-integration/pull/3060

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins run cdb

**Comment by baldimir** [comment]
jenkins run fdb

**Review by yesamer — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Comment by baldimir** [comment]
jenkins execute cdb

**Comment by baldimir** [comment]
jenkins do product cdb

**Comment by baldimir** [comment]
jenkins run cdb

**Comment by baldimir** [comment]
jenkins execute product fdb

**Comment by baldimir** [comment]
jenkins run fdb

**Comment by baldimir** [comment]
jenkins run cdb

**Comment by baldimir** [comment]
Compile downstream build is failing because it cannot build wars properly, because the war build is running a parallel Maven build, however the plugin used there (wildfly-jar-maven-plugin) doesn't support parallel builds. So it looks like the two parallel war builds are deleting files to each other. FDB build here (https://github.com/kiegroup/droolsjbpm-integration/pull/3060), that also builds those wars is green. Therefore I am skipping retrigger of the compile downstream build as the compilation works based on the linked full downstream build.

**Comment by baldimir** [comment]
Failure in full production downstream build is nor realted to the changes. It fails on LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable on InterruptedException.

**Comment by baldimir** [comment]
Full downstream build failed on java being killed by the environment.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by mareknovotny — APPROVED** [review]
lgtm, test failures or errors are not related

**Comment by baldimir** [comment]
Test failure in full downstream build not related to the changes. Merging.

**Pull request merged**
