### PR TITLE
[7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

### PR DESCRIPTION
**Pull request by hasys**
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do fdb

**Comment by jomarko** [comment]
@hasys I will approve this last part of the 7.59.x ensemble once builds are finished and war file available to do again small sanity check

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
@mareknovotny last execution of this PR was https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.59.x/job/fdb/job/droolsjbpm-build-bootstrap-7.59.x.fdb/10/
The build was UNSTABLE 5 tests failed

**Comment by hasys** [comment]
Failed tests are backend and unrelated:
<details>
  <summary>Click to expand</summary>
  <pre>    org.kie.karaf.itest.blueprint.KieBlueprintjBPMPersistenceKarafIntegrationTest.testStartProcessEnv
    org.jbpm.executor.impl.jms.JmsAvaiableJobExecutorTest.testAsyncAuditErrorProducer
    org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.testGetRepository[user: REST_PROJECT]
    org.jbpm.workbench.cm.DeploymentIT.org.jbpm.workbench.cm.DeploymentIT
    org.jbpm.workbench.DeploymentIT.testCaseManagementDeployment</pre>
</details>

@jomarko Business Central is generated. Thank you!

**Review by romartin — APPROVED** [review]

**Pull request merged**
