### PR TITLE
JDK11: Add dependencies needed by droolsjbpm-integration/kie-camel

### PR DESCRIPTION
**Pull request by cimbalek**
...to compile and run with JDK11

### CODE REVIEW

**Comment by pszubiak** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
This should be tested with openjdk 11 then on CI
Do we need to setup special slave with that version?

**Comment by pszubiak** [comment]
@mareknovotny Not yet. And we use Oracle JDK instead of OpenJDK. Adding Oracle JDK 11 should be quite easy. Probably we should switch to OpenJDK too, but it will require more work/tests.

**Comment by cimbalek** [comment]
I guess we need to merge this first and then possibly resolve Java 11 issues :) Important is that this breaks nothing for Java 8

**Comment by mareknovotny** [comment]
There is some enforcer ban-duplicated-classes rule errors

**Comment by cimbalek** [comment]
Who should I ask about these enforcer rules what to do with them? We need to resolve it somehow. Sooner = better

I guess we cannot avoid duplicities if something is present in JDK8 and is not in JDK11, correct me if I'm wrong

**Comment by mareknovotny** [comment]
We need to sort them out. Can you work on exclusions or redefinition of the dependencies to not duplicate classes? 
I haven't analysed the real duplication, but this addition reasonably adding some duplication if the enforcer reports them.

**Comment by mareknovotny** [comment]
can we close this PR or is it for rebase and update?

**Comment by cimbalek** [comment]
close it. I think it is solved already by different PR

**Pull request closed without merging**
