### PR TITLE
[DROOLS-5195] remove no longer supported integration modules

### PR DESCRIPTION
**Pull request by mariofusco**
merge with kiegroup/droolsjbpm-integration/pull/2075

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Pull request closed without merging**
