### PR TITLE
upgraded and aligned to jboss-ip-bom 8.0.0.CR2

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
My wild guess is that the test failures _are_ related to the IP BOM upgrade.

**Comment by mbarkley** [comment]
@psiroky @mbiarnes Looks like at least some of the failures are the same as the ones I fixed in Errai regarding the jboss-remoting version. Probably we should manage org.jboss.remoting:jboss-remoting to version 5.0.3.Final for now, and then update the ip-bom in the future?

**Comment by mbiarnes** [comment]
@mbarkley @psiroky 
I see in jboss-ip-bom this version <version.org.jboss.remoting3>3.3.7.Final</version.org.jboss.remoting3>
I don't see org.jboss.remoting:jboss-remoting nor in kie-parent. Should be this added there (kie-parent)?

**Comment by mbarkley** [comment]
Yes. Possibly we should remove the version for org.jboss.remoting3. It's no
longer a dependency of Errai. I haven't checked if it is used anywhere else
in the platform.

**Comment by mbarkley** [comment]
So we've had to revert the ip-bom upgrades in uberfire and dashbuilder because they broke WildFly in Super Dev Mode.

**Comment by mbarkley** [comment]
I've sent a new set of [PRs](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/615) for the ip-bom upgrade to all the relevant repositories, with several of the previous issues (like broken SDM) fixed. We should close this PR.

**Comment by psiroky** [comment]
Obsolete, closing.

**Pull request closed without merging**
