### PR TITLE
Drools 4141 - Split scesim client module in core and business central modules 

### PR DESCRIPTION
**Pull request by yesamer**
@gitgabrio @danielezonca @kkufova 

Required for PRs: 
- https://github.com/kiegroup/kie-wb-distributions/pull/939
- https://github.com/kiegroup/drools-wb/pull/1167

### CODE REVIEW

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Hi! Can you please merge it in master? Thanks!

**Comment by mareknovotny** [comment]
jenkins execute compile downstream build

wait for FDB result before merging

**Comment by yesamer** [comment]
@mareknovotny It failed for tests not related to my changes (https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/2/). I launch it again.

jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Pull request merged**
