### PR TITLE
BXMSPROD-846: upgrade cxf-core to 3.2.14

### PR DESCRIPTION
**Pull request by mareknovotny**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-846

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-integration/pull/2231

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
all 13 failures are present in daily master build too, but running to confirm it just for sure

**Review by mariofusco — APPROVED** [review]

**Review by elguardian — APPROVED** [review]
LGTM

**Pull request merged**
