### PR TITLE
[DROOLS-3868] Update antlr4-runtime version to 4.7.2

### PR DESCRIPTION
**Pull request by domhanak**
just a test if this would not break things

### CODE REVIEW

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
@etirelli Hi Edson, could you please give me some information if this upgrade would be possible? I plan to look at the test failures over the weekend (working on my community project :) ) and see if the failures are something severe.

**Comment by tarilabs** [comment]
Superseeded by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/953

@domhanak can you kindly close this PR, I needed to cherry pick your commit on another PR under my name with the same branch-name in order for the Jenkins to realize the 2 PRs (-build-bootstrap and drools with the fix/refactor) are indeed connected.

**Pull request closed without merging**
