### PR TITLE
BXMSPROD-685: upgraded version.org.ow2.asm

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
not sure why DMN selenium tests are still failing here.
@jomarko any idea?

**Comment by jomarko** [comment]
@mareknovotny  was this started after or before of https://github.com/kiegroup/kie-wb-common/pull/3224 merge?

**Comment by mareknovotny** [comment]
i see, probably not, I thought  https://github.com/kiegroup/kie-wb-common/pull/3224 was merged long before :)

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny ok, screeenshots taken but empty. No much help. I think I need your help in understanding difference between 'upstream' and 'downstream' in the context of this script https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/downstream_pr_jobs.groovy

First idea I would try is to override label for `kie-wb-common` to include `gui-testing`. However what I do not understand, when we run full down. build on other repository, for example drools-wb, tests are even not started. For example here. https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/drools-wb-downstream-pullrequests/64/testReport/

What is the algorithm that decides which repos will be built?

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mbiarnes , @mareknovotny  my apology for failing full d. build. It is caused due to no-showcase profile that is activated during full d. build. That profile skip gwt compilation and that is why screenshots are empty. Because selenium tests try to open empty/non-working page.

This PR should fix it. kiegroup/kie-wb-common#3243

**Comment by mareknovotny** [comment]
okay @jomarko, that makes sense now, even I think that profile was added in kogito showcase for some reason like showcase should not be in default build as it require a big memory https://github.com/kiegroup/kie-wb-common/pull/2968#issuecomment-546494253

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test `org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest.simpleTests` , I tried locally evn with changes form this PR and passed.

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
now different environmental failure IMO 
`org.jbpm.test.functional.timer.GlobalQuartzDBTimerServiceTest` failed on all its tests due not properly shutdown scheduler :(

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Can someone check the selenium failures @Rikkola ? @jomarko 
`org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testDecisionExpressionContextFunction
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testDecisionExpressionContextFunction
`

org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.openDMNDesigner(DMNDesignerKogitoSeleniumIT.java:142)

**Comment by jomarko** [comment]
@mareknovotny is this just this PR or do you spot the same file also elsewhere? Asking to know what branch to use for reproducing and solving.

**Comment by mareknovotny** [comment]
@jomarko right now only this PR

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
