### PR TITLE
security vulnerability:update of org.eclipse.jetty

### PR DESCRIPTION
**Pull request by mbiarnes**
GitHub: potential security vulnerabilities in dependencies

### CODE REVIEW

**Comment by mbiarnes** [comment]
found org.eclipse.jetty in following reps:
droolsjbpm-integration
jbpm-work-items

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
we use jetty as a test container only with exceptions to jbpm-work-items google's modules which can bundle/depends on some jetty, @tsurdilo can you review this upgrade?

@mbiarnes affected tests are the following:
- https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-common/src/test/java/org/kie/server/common/rest/KieServerHttpRequestTest.java 
- https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-common/src/test/java/org/kie/server/common/rest/ServerTestCase.java
- https://github.com/kiegroup/jbpm-work-items//blob/master/repository/src/test/java/org/jbpm/process/workitem/repository/HostedRepositoryIntegrationTest.java

If they are green here in CI I think we can merge it

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@mareknovotny three test failed
    org.kie.server.common.rest.KieServerHttpRequestTest.getWithResponseCharset
    org.kie.server.common.rest.KieServerHttpRequestTest.numberHeader
    org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
the selenium one fails in each FDB - the other two has to be looked at

**Comment by mareknovotny** [comment]
@mbiarnes ok, so test source code need a fix for the upgrade.

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
I looked at jetty issues, and it seems the Charset can be in different letter case in 9.x see https://bugs.eclipse.org/bugs/show_bug.cgi?id=414449 so we can fix it like in my change here https://github.com/mareknovotny/droolsjbpm-integration/commit/55baa1007b506d20e34dcc2628a653377fa160fd or find the version it is fixed. Unfortunately that bugzilla is referencing only the commit hash so I need to look for it in git repository

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/989
https://github.com/kiegroup/droolsjbpm-integration/pull/1891

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
so there is keeping `org.kie.server.common.rest.KieServerHttpRequestTest.numberHeader` failing, looking at that

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jetty vulnerability is not applicable here as we use it mainly for CI tests. And we don't have a motivation to solve the test failures in newer jetty version

**Pull request closed without merging**
