### PR TITLE
appformer removed from project-dependencies

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505
* https://github.com/kiegroup/drools/pull/3188

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
@Ginxo could we move the appformer down in repository-list.txt file too? I didn't realize when launched FDB it is no there

**Comment by Ginxo** [comment]
@mareknovotny change on repository-list.txt file done.
this is the FDB we are looking for https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdb/job/droolsjbpm-build-bootstrap-master.fdb/20 (this has to be launched by hand because of the change)

**Review by lucamolteni — APPROVED** [review]

**Comment by mareknovotny** [comment]
maybe move it even more down in the list, see my suggestion https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/26

**Comment by danielezonca** [comment]
> maybe move it even more down in the list, see my suggestion [Ginxo#26](https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/26)

Good point, what about `lienzo` repos? I think they both can be moved down just before `appformer` repo

**Comment by mareknovotny** [comment]
lienzo repos are so small that we can neglect it IMHO here. @danielezonca

**Comment by danielezonca** [comment]
> lienzo repos are so small that we can neglect it IMHO here. @danielezonca

Yes that's true, I think I like to have all engines repos together and then all tooling but still nothing big

**Comment by Ginxo** [comment]
@mareknovotny I can't see your suggestion :thinking: 
According to the [project-dependencies.yaml](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/.ci/project-dependencies.yaml) analysis automatically performed by [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader) this is the order we should follow
```
lienzo-core
lienzo-tests
droolsjbpm-build-bootstrap
kie-soup
droolsjbpm-knowledge
drools
jbpm
optaplanner
optaweb-employee-rostering
optaweb-vehicle-routing
kie-jpmml-integration
droolsjbpm-integration
openshift-drools-hacep
kie-wb-playground
jbpm-work-items
kie-wb-common
drools-wb
jbpm-designer
droolsjbpm-tools
appformer
kie-uberfire-extensions
jbpm-wb
optaplanner-wb
kie-wb-distributions
kie-docs
```
have in mind this should be automatically generated by the [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader)  in the following days and this is the list it should produce.
wdyt?

**Comment by mareknovotny** [comment]
> @mareknovotny I can't see your suggestion thinking

I sent a PR to your fork the link is in the comment before, just look at [`https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/26`](https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/26)

> According to the [project-dependencies.yaml](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/.ci/project-dependencies.yaml) analysis automatically performed by [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader) this is the order we should follow
> 
> ```
> lienzo-core
> lienzo-tests
> droolsjbpm-build-bootstrap
> kie-soup
> droolsjbpm-knowledge
> drools
> jbpm
> optaplanner
> optaweb-employee-rostering
> optaweb-vehicle-routing
> kie-jpmml-integration
> droolsjbpm-integration
> openshift-drools-hacep
> kie-wb-playground
> jbpm-work-items
> kie-wb-common
> drools-wb
> jbpm-designer
> droolsjbpm-tools
> appformer
> kie-uberfire-extensions
> jbpm-wb
> optaplanner-wb
> kie-wb-distributions
> kie-docs
> ```
> 
> have in mind this should be automatically generated by the [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader) in the following days and this is the list it should produce.
> wdyt?
yes, that is it, still the repository list should be kept for other types of jobs where we use it inside our scripts ;)

**Comment by danielezonca** [comment]
> @mareknovotny I can't see your suggestion 
> According to the [project-dependencies.yaml](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/.ci/project-dependencies.yaml) analysis automatically performed by [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader) this is the order we should follow
> 
> ```
> lienzo-core
> lienzo-tests
> droolsjbpm-build-bootstrap
> kie-soup
> droolsjbpm-knowledge
> drools
> jbpm
> optaplanner
> optaweb-employee-rostering
> optaweb-vehicle-routing
> kie-jpmml-integration
> droolsjbpm-integration
> openshift-drools-hacep
> kie-wb-playground
> jbpm-work-items
> kie-wb-common
> drools-wb
> jbpm-designer
> droolsjbpm-tools
> appformer
> kie-uberfire-extensions
> jbpm-wb
> optaplanner-wb
> kie-wb-distributions
> kie-docs
> ```
> 
> have in mind this should be automatically generated by the [build-chain-configuration-reader](https://www.npmjs.com/package/@kie/build-chain-configuration-reader) in the following days and this is the list it should produce.
> wdyt?

We cannot use this repository list, for example appformer is required by all UI projects, same for `kie-uberfire-extensions`.
If that list is produced using `project-dependencies.yaml` file we should probably review it too.
Btw @Ginxo are you sure the code to produce that list is correct?
For example if I check https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/.ci/project-dependencies.yaml I can see
`kie-wb-common` -> `droolsjbpm-integration` -> `jbpm` -> `drools` -> `appformer` but in the output list this order is not applied
In any case `project-dependencies.yaml` also contains some dependency cycle:
`kie-uberfire-extensions` -> `appformer` -> `drools` -> `optaplanner` -> `optaplanner` -> `kie-uberfire-extensions`

**Comment by Ginxo** [comment]
@danielezonca thanks for checking. First of all I was not accurate enough, the analysis I meant is based on https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/8567b8fcc8a7f2cb3916742ea8cd713162e30ebd/.ci/project-dependencies.yaml (the one from this PR) so
`kie-wb-common -> droolsjbpm-integration -> jbpm -> drools -> appformer` is based on the one from `droolsjbpm-build-bootstrap:master` and wouldn't be correct.
Additionally I can't see the dependency cycle you mean `kie-uberfire-extensions -> appformer -> drools -> optaplanner -> optaplanner-wb -> kie-uberfire-extensions` not even on `droolsjbpm-build-bootstrap:master` one.
Instead `kie-uberfire-extensions -> appformer -> drools` (which is the one we are trying to change).

Additionally @mareknovotny arrived to same conclusion about `appformer` level on https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/26/files
please @danielezonca correct me if I'm wrong

**Comment by danielezonca** [comment]
Yes you are right, there is no circular dependency :+1: 
Is it possible to move both `lienzo` repos just before `appformer`?

**Comment by Ginxo** [comment]
> Yes you are right, there is no circular dependency 
> Is it possible to move both `lienzo` repos just before `appformer`?

@danielezonca lienzo-core is needed by 
```
appformer
kie-wb-common
drools-wb
```
So, If I change project-dependencies.yml the tool generates
```
droolsjbpm-build-bootstrap
kie-soup
droolsjbpm-knowledge
drools
jbpm
optaplanner
optaweb-employee-rostering
optaweb-vehicle-routing
kie-jpmml-integration
droolsjbpm-integration
openshift-drools-hacep
kie-wb-playground
jbpm-work-items
kie-wb-common
drools-wb
jbpm-designer
droolsjbpm-tools
lienzo-core
lienzo-tests
appformer
kie-uberfire-extensions
jbpm-wb
optaplanner-wb
kie-wb-distributions
kie-docs
```
as you proposed. Modifying the PR

**Comment by Ginxo** [comment]
@danielezonca @mareknovotny please review again

**Review by ge0ffrey — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
Thanks for your PR, approving :+1:

**Pull request merged**
