### PR TITLE
Removed optaweb exclusion to make Optaplanner build from 7.x branch

### PR DESCRIPTION
**Pull request by lucamolteni**
https://github.com/kiegroup/drools/pull/3860

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
running fdb just to check checkout summary

**Comment by Ginxo** [comment]
fdb not a proper test, can you please @lucamolteni open a PR for drools (same author, same source branch) in order to test it (it can/should be draft)

**Review by tkobayas — APPROVED** [review]
Sorry, I'm not knowledgeable around this configuration so it would be okay if other reviewers approve.

**Comment by ge0ffrey** [comment]
I don't know this part well enough, but Radovan does.
Radovan can you do the review in my place?

Note: At least until now, droolsjbpm-build-bootstrap's main branch builds optaplanner's 7.x branch.
(the optaplanner main branch is build by the kogito release pipeline.)
I presume that stays the same?

**Comment by Ginxo** [comment]
> I don't know this part well enough, but Radovan does. Radovan can you do the review in my place?
> 
> Note: At least until now, droolsjbpm-build-bootstrap's main branch builds optaplanner's 7.x branch. (the optaplanner main branch is build by the kogito release pipeline.) I presume that stays the same?

it does, we are just modifying here the mapping between drools and optaplanner (not the opposite)

**Review by ge0ffrey — APPROVED** [review]

**Review by Ginxo — APPROVED** [review]
LGTM

**Pull request merged**
