### PR TITLE
[AF-2058] Provide alternative implementation of uberfire-nio2-impl backed by OCP/K8S

### PR DESCRIPTION
**Pull request by rhtevan**
As a prerequisite to this PR:
https://github.com/kiegroup/appformer/pull/799
https://github.com/kiegroup/kie-wb-common/pull/2916

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

### CODE REVIEW

**Comment by kie-ci10** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar One integration test fail. I don't think that's related to the kube client upgrade. wdyt?

**Comment by sutaakar** [comment]
seems unrelated

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
same failure which should be unrelated to this PR.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar Are those test failures having being fixed by this PR? Or something else

https://github.com/kiegroup/drools/pull/2578

**Comment by sutaakar** [comment]
Yes, should be fixed now.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar Failed with just 1 test case failure which is kind of familiar.

**Comment by sutaakar** [comment]
Yes, should be unrelated to this PR, but to be sure...

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar Failed again with other test case failures, so fragile.

**Comment by mareknovotny** [comment]
@rhtevan these 6 failures in Selenium tests are actually real issues on master branch of kie-wb-distribution, see our bsig ML for that. So this is not related to your change, but until someone fix them you will see it there again.

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Seems that the test failures in FDB are not related to this change.

**Comment by mareknovotny** [comment]
@sutaakar do we need to file the jira for failing test?

**Comment by sutaakar** [comment]
One test failure is fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1957
The second one looks like some instability.

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by rhtevan** [comment]
@sutaakar a failure from running integration test for this component. Could be intermittent.

`[INFO] Employee Rostering as a Service Distribution ....... FAILURE [01:21 min]`

**Comment by sutaakar** [comment]
Seems intermittent to me.

**Pull request merged**
