### PR TITLE
BXMSPROD-685: upgrade of org.jboss.resteasy

### PR DESCRIPTION
**Pull request by mbiarnes**
this depends on merging first #1203

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@mbiarnes there is kiegroup/droolsjbpm-build-bootstrap/pull/120 which handles the exclusion of duplicated classes which here fails in `uberfire-security-api`:

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.0.Final:provided
    org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:1.0.1.Final:compile
  Duplicate classes:
    javax/annotation/ManagedBean.class
    javax/annotation/PreDestroy.class
    javax/annotation/Generated.class
    javax/annotation/Resource$AuthenticationType.class
    javax/annotation/security/DeclareRoles.class
    javax/annotation/Priority.class
    javax/annotation/Resource.class
    javax/annotation/security/DenyAll.class
    javax/annotation/security/RunAs.class
    javax/annotation/sql/DataSourceDefinitions.class
    javax/annotation/security/PermitAll.class
    javax/annotation/security/RolesAllowed.class
    javax/annotation/Resources.class
    javax/annotation/PostConstruct.class
    javax/annotation/sql/DataSourceDefinition.class
```
I think we need to hold off this PR or add it into existing #1203

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
